### PR TITLE
#5011 - Re-add primary phone number and primary email address to impo…

### LINKED ISSUE #5011: Re-add primary phone number and primary email address to import templates [1]
### Bug Description
personContactDetails cannot be imported since respective columns are missing in the templates. The table is also missing in the data dictionary.
### Steps to Reproduce
1. Download an import template (e.g. for cases)
2. Check columns for person contact details

### Expected Behavior
personContactDetails should be able to be imported. The personContactDetails table should also be displayed in the data dictionary.
### Screenshots
personContactDetails
### System Details
* Device:
* SORMAS version: 1.58.2
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### Development Specifications
* Add primary phone number and primary email address to the person sections of import templates for cases, contacts and event participants
* During the import, when these are not empty, use the helper methods in PersonDto (setEmailAddress and setPhoneNumber) to automatically create contact details when the person is saved
* Align with the export

### PR DESCRIPTION
**Pull request by cazacmarin**
…rt templates

Fixes #5011

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java [hunk 1]
```diff
@@ -221,10 +221,16 @@ public void generateCaseImportTemplateFile() throws IOException {
 		appendListOfFields(importColumns, CaseDataDto.class, "", separator);
 		appendListOfFields(importColumns, SampleDto.class, "", separator);
 		appendListOfFields(importColumns, PathogenTestDto.class, "", separator);
+		addPrimaryPhoneAndEmail(separator, importColumns, PersonDto.PHONE, PersonDto.EMAIL_ADDRESS);
 
 		writeTemplate(Paths.get(getCaseImportTemplateFilePath()), importColumns, true);
 	}
 
+	private void addPrimaryPhoneAndEmail(char separator, List<ImportColumn> importColumns, String phone, String emailAddress) {
```
Comment (vidi42) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java:229]: Since the method specifies that it adds the phone and email column why is it needed to also specify the `phone` and `emailAddress` strings?

**Review by vidi42 — CHANGES_REQUESTED** [review]

**Review by vidi42 — CHANGES_REQUESTED** [review]
