### PR TITLE
#9623 - Validate age groups gracefully

### LINKED ISSUE #9623: Conversion of age groups should not throw exception [0.5]
### Problem Description
Currently loading the disease configuration during startup the server does not start when there is an invalid age group defined for a disease, because the used converted validates the age group which throws an exception.

### Proposed Change

- [x] The converter should still validate each age group, but should catch the exception, log a warning and ignore the invalid age group

This will also make sure that the mSers module in the UI and app does not throw exceptions, but instead just doesn't show invalid age groups.

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #9623

### CODE REVIEW

File: sormas-api/src/main/java/de/symeda/sormas/api/utils/AgeGroupUtils.java [hunk 1]
```diff
@@ -75,38 +83,46 @@ private static String getAgeGroupTimeUnitCaption(String ageGroupTimeUnit) {
...
-			ageGroupList.forEach(s -> validateAgeGroup(s));
-			return ageGroupList;
-		} catch (IllegalArgumentException e) {
-			throw new RuntimeException(
-				"Content of ageGroupsString is not a valid list of ageGroups, or one of the ageGroups in the String does not match a valid ageGroup: "
-					+ ageGroupsString);
-		}
+		final List<String> ageGroupList = Stream.of(ageGroupsString.split(",")).collect(Collectors.toList());
+		final List<String> invalidAgeGroupsList = new ArrayList<>();
+		ageGroupList.forEach(s -> {
```
Comment (MartinWahnschaffe) [inline sormas-api/src/main/java/de/symeda/sormas/api/utils/AgeGroupUtils.java:93]: I'd suggest to user removeIf: https://www.geeksforgeeks.org/arraylist-removeif-method-in-java/

**Review by MartinWahnschaffe — APPROVED** [review]

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]

File: sormas-api/src/main/java/de/symeda/sormas/api/utils/AgeGroupUtils.java [hunk 2]
```diff
@@ -75,38 +82,46 @@ private static String getAgeGroupTimeUnitCaption(String ageGroupTimeUnit) {
...
-		try {
-			final List<String> ageGroupList = Stream.of(ageGroupsString.split(",")).collect(Collectors.toList());
-			ageGroupList.forEach(s -> validateAgeGroup(s));
-			return ageGroupList;
-		} catch (IllegalArgumentException e) {
-			throw new RuntimeException(
-				"Content of ageGroupsString is not a valid list of ageGroups, or one of the ageGroups in the String does not match a valid ageGroup: "
-					+ ageGroupsString);
-		}
+		final List<String> ageGroupList = Stream.of(ageGroupsString.trim().split(",")).collect(Collectors.toList());
```
Comment (MartinWahnschaffe) [inline sormas-api/src/main/java/de/symeda/sormas/api/utils/AgeGroupUtils.java:90]: The trimming has to be done very every single age group.  E.g. "D0_D30, D31_M2" should be a valid age groups string.

**Review by MartinWahnschaffe — APPROVED** [review]
