### PR TITLE
Bug/10525 multiple cases from pathogen test in contacts and event partic

### LINKED ISSUE #10525: Multiple cases can be created based on the same sample and pathogen test
### Bug Description

Multiple cases can be created starting from the same sample and pathogen test, even if a case has already been created starting from the same sample and pathogen test.

### Steps to Reproduce

1. Create a Covid-19 case;
2. Add to the case a sample with a positive pathogen test result of Anthrax;
3. 'Generate new case for Anthrax?' pop-up is triggered;
4. Click 'Yes' in the pop-up and create the new case;
5. Navigate to the case created at step 1 and open the sample associated;
6. Open the pathogen test and edit some information on it, or edit nothing, and just click 'Save'.

### Actual Behavior

Pop-up to 'Generate a new case for Anthrax?' is triggered again, even though a case was already created based on the same pathogen test and sample. If a new case is created, no duplicate detection for cases is triggered.

### Expected Behavior

If a case was already created based on the respective pathogen test, the pop-up to generate another case should no longer be triggered.

### Screenshots

GIF of the steps to reproduce and the behavior:
Multiple Cases from the same Pathogen Test

### System Details

* Device: Windows 10 
* SORMAS version: 1.76.0-SNAPSHOT(5111f71); also on 1.75.3.
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### PR DESCRIPTION
**Pull request by dinua**
Fixes #10525

### CODE REVIEW

File: sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java [hunk 1]
```diff
@@ -205,7 +205,7 @@ void saveBulkEditWithFacilities(
 
 	List<CasePersonDto> getDuplicates(@Valid CasePersonDto casePerson);
 
-	List<CaseDataDto> getDuplicatesWithPathogenTest(@Valid CaseDataDto caseDataDto, PathogenTestDto pathogenTestDto);
+	List<CaseDataDto> getDuplicatesWithPathogenTest(@Valid String casePersonUuid, PathogenTestDto pathogenTestDto);
```
Comment (syntakker) [inline sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java:208]: To make this method's signature more concise, do not use parameter type `String casePersonUuid`, but `PersonReferenceDto personReference` instead.
This avoids calling the method with an arbitrary `String` and also avoids extracting the person's UUID before calling the method in various places.

File: sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java [hunk 2]
```diff
@@ -3146,7 +3146,7 @@ public void testDuplicatesWithPathogenTest() {
 		covidCase.setDisease(Disease.ANTHRAX);
 		CaseDataDto anthraxCase = getCaseFacade().cloneCase(covidCase);
 
-		List<CaseDataDto> duplicatedCases = getCaseFacade().getDuplicatesWithPathogenTest(covidCase, pathogenTestDto);
+		List<CaseDataDto> duplicatedCases = getCaseFacade().getDuplicatesWithPathogenTest(covidCase.getPerson().getUuid(), pathogenTestDto);
 		assertEquals(1, duplicatedCases.size());
```
Comment (syntakker) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/caze/CaseFacadeEjbTest.java:3150]: `getUuid()` can then be omitted here.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 3]
```diff
@@ -258,7 +258,7 @@ private void handleAssociatedCase(
 						}
 					});
 				} else {
-					List<CaseDataDto> duplicatedCases = FacadeProvider.getCaseFacade().getDuplicatesWithPathogenTest(caze, dto);
+					List<CaseDataDto> duplicatedCases = FacadeProvider.getCaseFacade().getDuplicatesWithPathogenTest(caze.getPerson().getUuid(), dto);
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:261]: Following the refactoring describe above, `getUuid()` can be omitted here.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 4]
```diff
@@ -374,11 +378,15 @@ private void handleAssociatedEventParticipant(
 						showChangeAssociatedSampleResultDialog(dto, null);
 					}
 				} else {
-					showConvertEventParticipantToCaseDialog(eventParticipant, dto.getTestedDisease(), caseCreated -> {
-						if (eventDisease == null) {
-							handleCaseCreationFromContactOrEventParticipant(caseCreated, dto);
-						}
-					});
+					List<CaseDataDto> duplicatedCases =
+						FacadeProvider.getCaseFacade().getDuplicatesWithPathogenTest(eventParticipant.getPerson().getUuid(), dto);
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:382]: After refactoring, convert the `EventParticipantDto`'s person to a reference using `toReference()`.

**Review by syntakker — CHANGES_REQUESTED** [review]

File: sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java [hunk 5]
```diff
@@ -205,7 +205,7 @@ void saveBulkEditWithFacilities(
 
 	List<CasePersonDto> getDuplicates(@Valid CasePersonDto casePerson);
 
-	List<CaseDataDto> getDuplicatesWithPathogenTest(@Valid CaseDataDto caseDataDto, PathogenTestDto pathogenTestDto);
+	List<CaseDataDto> getDuplicatesWithPathogenTest(@Valid PersonReferenceDto casePersonReferenceDto, PathogenTestDto pathogenTestDto);
```
Comment (syntakker) [inline sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseFacade.java:208]: rename `casePersonReferenceDto` to `personReferenceDto` as this method has been extended to handle persons from other entities, too.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 6]
```diff
@@ -4199,7 +4199,7 @@ public List<CasePersonDto> getDuplicates(@Valid CasePersonDto casePerson, int re
 	}
 
 	@Override
-	public List<CaseDataDto> getDuplicatesWithPathogenTest(@Valid CaseDataDto caseDataDto, PathogenTestDto pathogenTestDto) {
+	public List<CaseDataDto> getDuplicatesWithPathogenTest(@Valid PersonReferenceDto casePersonReferenceDto, PathogenTestDto pathogenTestDto) {
```
Comment (syntakker) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:4202]: rename `casePersonReferenceDto` to `personReferenceDto` here, too.

**Review by syntakker — CHANGES_REQUESTED** [review]
Approved for merge after the renaming of the `getDuplicatesWithPathogenTest` method's parameter to `personReferenceDto`.

**Review by syntakker — APPROVED** [review]
