### PR TITLE
Bugfix 6715 task reassignment android

### LINKED ISSUE #6715: Task reassignment in Android app differs from Vaadin app
### Bug Description
In the Vaadin app, task reassigment is triggered by a change of any infrastructure related to a case (see `CasefFacadeEjb.updateTasksOnCaseChanged`). In the Android app, however, tasks are reassigned only if a case's `responsibleDistrict` or `district` is changed (see `CaseDao.onCaseChanged`).

### Expected Behavior
Both implementations should behave consistently. Additionally, tests should reflect the intended behaviour (see also #6714)

Please make sure that the implemented behaviour is depicted by a meaningful test (see `CaseBackendTest.shouldUpdateCaseAndAssociatedEntitiesOnMove`).

### System Details

* Device:
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by syntakker**
Fixes #6715

### CODE REVIEW

File: sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java [hunk 1]
```diff
@@ -553,6 +539,41 @@ private void onCaseChanged(Case existingCase, Case changedCase) {
 		}
 	}
 
+	private void assignOfficerOrSupervisorToTask(Case changedCase, Task task) {
+		if (changedCase.getSurveillanceOfficer() != null) {
+			task.setAssigneeUser(changedCase.getSurveillanceOfficer());
+		} else {
+			// TODO roles? what happens when there are no supervisors? assignee user cannot be null
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java:546]: Please have a look at the task assignment process in the onCaseChanged method in the web backend and adjust the task assignment here accordingly, i.e. when there is no officer assigned to the case, use a random officer from the responsible district or, if there's none, from the place of stay district before falling back to supervisors.

File: sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java [hunk 2]
```diff
@@ -474,8 +474,19 @@ private void onCaseChanged(Case existingCase, Case changedCase) {
...
+
+			boolean responsibleCommunityChanged = !DataHelper.isSame(changedCase.getResponsibleCommunity(), existingCase.getResponsibleCommunity());
+			boolean communityChanged = !DataHelper.isSame(changedCase.getCommunity(), existingCase.getCommunity());
+
+			boolean facilityChanged = !DataHelper.isSame(changedCase.getHealthFacility(), existingCase.getHealthFacility());
+
 			// If the district has changed, assign a new surveillance officer and re-assign tasks
-			if (!DataHelper.isSame(changedCase.getResponsibleDistrict(), existingCase.getResponsibleDistrict())
+			if (responsibleDistrictChanged
 				|| (changedCase.getResponsibleDistrict() == null && !DataHelper.isSame(changedCase.getDistrict(), existingCase.getDistrict()))) {
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java:490]: This code does not apply to the current logic anymore; the responsible district of a case can never be null. Also, please make sure to ONLY re-assign the surveillance officer of the case here if the current responsible officer's district is NEITHER the responsible district NOR the place of stay district anymore

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

File: sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java [hunk 3]
```diff
@@ -474,27 +474,41 @@ private void onCaseChanged(Case existingCase, Case changedCase) {
...
+			boolean districtChanged = !DataHelper.isSame(changedCase.getDistrict(), existingCase.getDistrict());
+
+			boolean responsibleCommunityChanged = !DataHelper.isSame(changedCase.getResponsibleCommunity(), existingCase.getResponsibleCommunity());
+			boolean communityChanged = !DataHelper.isSame(changedCase.getCommunity(), existingCase.getCommunity());
+
+			boolean facilityChanged = !DataHelper.isSame(changedCase.getHealthFacility(), existingCase.getHealthFacility());
+
+			// If the case is moved from the surveillance officer's jurisdiction, assign a new surveillance officer
+			if (changedCase.getSurveillanceOfficer() == null
+				|| (responsibleDistrictChanged
```
[the remark this answers is not in the document]
Comment (syntakker) [reply sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java]: done.

**Review by MateStrysewske — APPROVED** [review]
