### PR TITLE
#4864 correctly display districts in statistics map

### LINKED ISSUE #4864: Improve Statistics Map, Districts overlap each other
### Bug Description

Currently, some districts are not correctly mapped in the statistics map section. The main reason for that is that in germany, some districts have the same name but are either a Landkreis (LK) or Stadtkreis (SK). 

### Steps to Reproduce
1. Create Cases in a LK and SK which are "inside" each other. Example: LK & SK Würzburg
2. Go to the statistics section, and generate the district map. the LK will overlap the SK.

### Expected Behavior

It should look like this: 

image

### Additional Information

This is a followup of #4565

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
Fixes #4864 , followup of #4565

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeHelper.java [hunk 1]
```diff
@@ -134,21 +138,21 @@ public static MultiPolygon getPolygon(SimpleFeature feature, MathTransform trans
 	 * @return
 	 *         The name of the feature, null if no name could be found.
 	 */
-	public static String sniffShapeName(SimpleFeature feature, List<String> list) {
-		String shapeName = null;
+	public static String sniffShapeAttribute(SimpleFeature feature, List<String> list) {
```
Comment (MartinWahnschaffe) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeHelper.java:141]: Rename list to attributeNames.
I think the old comment also needs to be adjusted. It's returning the value of the found feature attribute, not the attribute name.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/statistics/StatisticsView.java [hunk 2]
```diff
@@ -973,11 +969,50 @@ public void generateMap() {
...
+		// sort polygon array, so that polygons which are completely contained by another appear on top
+		List<Integer[]> indexesToSwap = new ArrayList<>();
+		int poly1index = 0, poly2index = 0;
+		for (LeafletPolygon poly1 : resultPolygons) {
+			for (LeafletPolygon poly2 : resultPolygons) {
+				if (poly1index == poly2index) {
+					continue;
+				}
+				// determine maximum latitude and longitude of each polygon
+				List<double[]> poly1LatLons = Arrays.asList(poly1.getLatLons());
```
Comment (MartinWahnschaffe) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/statistics/StatisticsView.java:988]: I suggest to give the LeaftletPolygon two fields minLatLon and maxLatLon and a getter method. Whenever the getter is called the first time, calculate the values. Reset them to null, when setLatLons is called.

Thisway the min/max does not have to be calculated for every combination of polygons, but just for every single polygon.

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeProviderEjb.java [hunk 3]
```diff
@@ -266,23 +269,53 @@ private void loadDistrictData(String countryName) {
...
+					String shapeDistrictId = GeoShapeHelper.sniffShapeAttribute(feature, Arrays.asList("ARS"));
+					if (shapeDistrictId == null) {
+						continue;
+					}
+					districtResult = districts.stream().filter(r -> {
+						String districtExtID = r.getExternalId();
+						if (districtExtID == null) {
+							return false;
+						}
+						return districtExtID.contains(shapeDistrictId)
```
Comment (MartinWahnschaffe) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeProviderEjb.java:285]: I'm not sure about using similarity here. From my understanding we are looking at IDs that should be an exact match. It would not be acceptable to use the shape for a district, when the ID is different. E.g. 142421323 vs. 142421324

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeProviderEjb.java (hunk 3 above)
Comment (DavidBaldsiefen) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeProviderEjb.java:285]: Hmm yes you're right. The problem is that (of course :P) the shapefiles we use use a slightly different approach. I think the shapefiles provide 5-digit-ID's and the external IDs in SORMAS are usually 7 digits. (something like the first two digits always being 11). I can look into this

Comment (DavidBaldsiefen) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/region/GeoShapeProviderEjb.java:285]: I've removed the similarity check, and added a custom check for the external ID being "110<shapefile ID>", e.g. `11012345` for the district with shapefile-ID `12345`, as that seems to be common for germany.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/statistics/StatisticsView.java [hunk 4]
```diff
@@ -726,22 +731,12 @@ public void generateChart() {
 		}
 		hcjs.append("],");
 
-		hcjs.append("exporting: {\n" +
```
Comment (MartinWahnschaffe) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/statistics/StatisticsView.java:729]: @DavidBaldsiefen Didn't notice this before. Please add a tag to keep the original formatting, because it is much easier to read.

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]
@DavidBaldsiefen Just one small fix. Afterwards you can merge
