### PR TITLE
#8210 Fix disease variant field not being displayed

### LINKED ISSUE #8210: The 'Disease Variant' field is hidden in the 'Create new case' form of a Travel Entry
### Bug Description
When a Case is created for a Travel Entry, the 'Disease Variant' field is missing from the 'Create new case' form.

### Steps to Reproduce

1. Open or create a Travel Entry which has 'COVID-19' set as 'Disease' and also has a Disease Variant selected;
2. Create a Case for the Travel Entry;
3. Inspect the 'Create new case' form.

### Expected Behavior
Disease Variant field should be visible and populated according to the Travel Entry.

### Screenshots
image

### System Details

* Device: Window 10
* SORMAS version: 1.69.0-SNAPSHOT (f6fa042)
* Android version/Browser: Chrome
* Server URL: test-de1.sormas.netzlink.com, test-de2.sormas.netzlink.com, test-de3.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information
- This issue is reproducible only on the testing instances; it's not reproducible on my local machine.
- I found this issue while testing #8105

### PR DESCRIPTION
**Pull request by vidi42**
Fixes #8210

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java [hunk 1]
```diff
@@ -824,44 +824,6 @@ public void selectOrCreateCase(CaseDataDto caseDto, PersonDto person, Consumer<S
 		}
 	}
 
-//	public CommitDiscardWrapperComponent<? extends Component> getCaseCombinedEditComponent(final String caseUuid,
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java:827]: Please delete commented code

**Review by leventegal-she — CHANGES_REQUESTED** [review]

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java (hunk 1 above)
Comment (vidi42) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java:827]: That's what I did. Or am I missing something? 😄

Comment (leventegal-she) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java:827]: yeah, sorry. I had the feeling that you've commented the code :D

**Review by leventegal-she — APPROVED** [review]
