### PR TITLE
#10451 - Allow users without sample rights to view contacts

### LINKED ISSUE #10451: Users with access to contacts but no access to samples can't open contacts
### Bug Description
When a user with a configured user role (with 'View existing contact' and 'Create new contact' user rights) opens a Contact, he cannot see the Contact page information, and he gets 'A problem has occurred' error message when he creates a new Contact, because he is missing the SAMPLE_VIEW user right.
[logs for opening an existing Contact.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9646590/logs.for.opening.an.existing.Contact.txt)
[logs for creating Contact.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9646592/logs.for.creating.Contact.txt)

### Steps to Reproduce

1. Navigate to the Users Directory, select the 'User Roles' tab and click on 'New User Role';
2. In the 'Create new user role' form, leave the 'User role template' empty', fiil in the Caption and set the 'Jurisdiction Level' to 'Nation'; Save;
3. Select the User Rights as in the screenshots from the Additional Information section;
4. Create a user with the User Role from step 2&3;
5. Log in with the user with the configured user role and open the Contacts Directory;
6. Open an existing Contact;
   -> the user doesn't see the content of the page:
image
7. Go back to the Contacts and click on 'New Contact';
8. Fill in the mandatory fields and Save;
  -> the following warning message is thrown:
image

### Expected Behavior
Probably the user should not have been able to save the User Role with that specific combination of user rights in the first place (the expected behavior needs to be discussed though)

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.76.0-SNAPSHOT (138c03e)
* Android version/Browser: Chrome
* Server URL: local environment 
* User Role: see the screenshots

### Additional Information
<details>
<summary>Screenshots with the User Rights of the used User Role</summary> 

image
image
image
image

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #10451

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java [hunk 1]
```diff
@@ -304,6 +306,25 @@ public List<SampleDto> getByLabSampleId(String labSampleId) {
 		return em.createQuery(cq).getResultList().stream().distinct().map(SampleFacadeEjb::toDto).collect(Collectors.toList());
 	}
 
+	@Override
+	@PermitAll
```
Comment (sergiupacurariu) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java:310]: shouldn't we use a narrower range of permissions here? We only need Case, Contact and Event Participant view.

Comment (MateStrysewske) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java:310]: Good point, will change it accordingly

**Comment by MateStrysewske** [comment]
@sergiupacurariu Made the change and also fixed some user right issues connected to tasks that I stumbled upon.

**Review by sergiupacurariu — APPROVED** [review]
