### PR TITLE
#5930 - add back Berlin / Bayern / Bremen to the list of polygons to …

### LINKED ISSUE #5930: Hide other countries hides Bavaria, Bremen and Berlin
### Bug Description

If you select "hide other countries" in the map of the dashboard it also hides Bavaria, Bremen and Berlin:

image

### Steps to Reproduce

1. Open the map
2. choose the layer "Hide other countries"
image

### System Details

* SORMAS version: 1.59.2

### PR DESCRIPTION
**Pull request by BarnaBartha**
…be used for the country coordinates - as they are wrongly removed / not merged correctly with their neighbouring polygon

Fixes #5930

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/geo/GeoShapeProviderEjb.java [hunk 1]
```diff
@@ -382,6 +383,14 @@ private void buildCountryShape() {
 			}
 		}
 
+		// fixme: this should be removed if the above logic is rewritten/fixed
```
Comment (MartinWahnschaffe) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/geo/GeoShapeProviderEjb.java:386]: Something like: "fixme: Remove when the shapefiles are no longer part of the resources. In this case the logic to build country shapes will have to be checked again to fix the problem is workarround by this."
