### PR TITLE
Bug/8768 tasks displayed to users with no rights

### LINKED ISSUE #8768: [Tasks] Tasks associated with contacts are displayed for users that do not have 'CONTACT_VIEW' or 'CONTACT_EDIT' rights
### Bug Description

In the 'Tasks' directory, tasks associated with contacts are displayed for users that do not have 'CONTACT_VIEW' or 'CONTACT_EDIT' rights, if the tasks are associated with contacts from within the users' responsible jurisdiction.

### Steps to Reproduce

1. Log in with an 'Admin+NatUser' user; 
2. Create a 'Case Officer' user and a 'Community Informant' user;
3. Create a contact and set its 'Responsible jurisdiction' within the jurisdiction of the users created at step 2;
4. Create a task for the contact from step 3;
5. Log in with the 'Case Officer' user and then with the 'Community Informant' user, and observe the list of tasks in the 'Tasks' directory.

### Actual Behavior

Tasks associated with contacts are displayed in the 'Tasks' directory for users that do not have the 'CONTACT_VIEW' or 'CONTACT_EDIT' rights.

### Expected Behavior

Tasks associated with contacts should not be displayed in the 'Tasks' directory for users that do not have the 'CONTACT_VIEW' or 'CONTACT_EDIT' rights, unless those users have already been assigned to the tasks.

### Screenshots

image

### System Details

* Device: Windows 10 
* SORMAS version: 1.71.0-SNAPSHOT(edacd95)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser; Community Informant; Case Officer

### Additional Information

Note regarding the expected behavior: the assignation of tasks associated with contacts to users that do not have 'CONTACT_VIEW' OR 'CONTACT_EDIT' rights will be addressed in a change request.

### PR DESCRIPTION
**Pull request by dinua**
Fixes #8768

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java [hunk 1]
```diff
@@ -440,6 +444,11 @@ public long count(TaskCriteria taskCriteria) {
 			filter = CriteriaBuilderHelper.and(cb, filter, criteriaFilter);
 		}
 
+		Predicate contactPredicate = this.contactRightsPredicate(cb ,task, joins.getAssignee(), joins.getTaskObservers());
+		if(contactPredicate != null){
+			filter = CriteriaBuilderHelper.and(cb, filter, contactPredicate);
+		}
```
Comment (sergiupacurariu) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskFacadeEjb.java:450]: please move the contactPredicate under createUserFilter. This way you will also cover the exports and the Android app synchronization.
