### PR TITLE
#10050 - Remove case from external message when deleting

### LINKED ISSUE #10050: [Deletion] Update or delete on table 'cases' violates foreign key constraint 'fk_externalmessage_caze_id' on table 'externalmessage'
### Bug Description

When trying to run the automatic deletion job, an exception is thrown:
image

### Steps to Reproduce

1. In the Data Base, in the 'deleteconfiguration' table, edit the deletion period for the entities to '7' days;
2. In the 'CronService.java' edit the coreEntityDeletionService to run sooner (so that this can be tested easily);
3. Wait for the job to run and observe the server logs and the entities in the DB and the UI.

### Expected Behavior

Deletion job should run successfully; no exception should be thrown.

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(59b6b90)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### Additional Information

Logs from the local machine:
[Exception thrown.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9266053/Exception.thrown.txt)

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #10050

### CODE REVIEW

**Review by leventegal-she — APPROVED** [review]

**Review by leventegal-she — CHANGES_REQUESTED** [review]
The case field in ExternalMessageCriteria is not handled in ExternalMessageService::buildCriteriaFilter

**Review by leventegal-she — APPROVED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java [hunk 1]
```diff
@@ -1110,6 +1114,12 @@ private void deleteCaseLinks(Case caze) {
 
 		// Remove the case as the related case of immunizations
 		immunizationService.unlinkRelatedCase(caze);
+
+		// Remove the case from any external message referencing it
+		externalMessageService.getForCase(new CaseReferenceDto(caze.getUuid())).forEach(labMessage -> {
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java:1119]: There is a small naming issue with this. 
SORMAS has external messages now, which can be of type lab message or physician's report. Actually, external messages with a case reference are always phisycan's reports, never lab messages. Thus, the parameter name labMessage is misleading here. @MateStrysewske Shall I just push a small fix of this (tagging #10050) to development?
