### PR TITLE
#5383 - transfer primary contact details to person from case create f…

### LINKED ISSUE #5383: contact>contact-to-case conversion> contact details on creation form get lost
### Bug Description
Contact details from creation from during converting a contact into a case get lost. True for email and phone number.

### Steps to Reproduce

1. convert a contact into case, document phone number and email on creation form
2.check for contact details in case person data --> none of both is displayed

### Expected Behavior
Documented contact details should appear at the case person contact information table. 

### Screenshots
image
image

### System Details

* Device:
* SORMAS version: 1.58.3 and 1.59.1
* Android version/Browser: Chrome
* Server URL: https://test1401.sormas-oegd.de/
* User Role: admin

### PR DESCRIPTION
**Pull request by BarnaBartha**
…orm when converting contact to case

Fixes #5383

### CODE REVIEW

File: sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java [hunk 1]
```diff
@@ -466,6 +466,9 @@ public void setDeathDate(Date deathDate) {
 	private void setPersonContactInformation(String contactInfo, PersonContactDetailType personContactDetailType) {
 		for (PersonContactDetailDto contactDetailDto : getPersonContactDetails()) {
 			if (contactDetailDto.getPersonContactDetailType() == personContactDetailType && contactDetailDto.isPrimaryContact()) {
+				if (contactInfo.equals(contactDetailDto.getContactInformation())){
```
Comment (MateStrysewske) [inline sormas-api/src/main/java/de/symeda/sormas/api/person/PersonDto.java:469]: Code formatting; apart from that, everything's fine, you can merge the PR after applying code formatting

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
