### PR TITLE
#4964 Refine caseOutcome/personCondition update mechanism

### LINKED ISSUE #4964: Refine the update mechanism between case outcome and person death date [2]
### Bug Description
This is a continuation of #4248
-  When outcome == death, date of date of outcome is set to current date and present condition of person is set to death and date of death == current date.  This make up data that may not be real. 
### Steps to Reproduce
1. creat a case
2. set the outcome to death and provide no date of outcome
3. save and check the case and case person

### Expected Behavior
How logic should work:

Validation between outcome of case and present condition of person should be activated only if (outcome = diseased) AND (present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case)
If outcome of a case == death or buried then set present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case. If date of outcome is know, then assign it to date of death of person. You can override previous data.
if present condition == death or buried & cause of death == epidemic disease & responsible disease == same disease as that of the case, then set outcome = diseased. If date of death in not null, then assign it to date of outcome.
else do not validate outcome or date of outcome with present condition of person.

- If there are multiple cases of the same disease linked to the person, then this should apply only to the most recent case based on report date
### System Details
* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Development Specifications (Confirmed 11-6-2021)
Refine the logic that is responsible for updating the case outcome / present condition of the associated person as follows. Most of that logic will already work this way, but something seems off.
* Do not set the `outcomeDate` automatically to the current date anymore
* If `caseOutcome` is updated to `DECEASED`, always update `presentCondition` of the person to `DEAD`, set `deathDate` to the `outcomeDate` of the case, `causeOfDeath` to `EPIDEMIC_DISEASE` and `causeOfDeathDisease` to the disease of the case.
* If the `caseOutcome` of a case is later changed to `RECOVERED` or `NO_OUTCOME` again, change the `presentCondition` of the person back to `ALIVE` (and clear all fields that depend on it) ONLY if:
    * there is NO other case associated with this person in the system with outcome `DECEASED`
    * the `causeOfDeath` is filled in and set to `EPIDEMIC_DISEASE`
    * the `causeOfDeathDisease` matches the disease of the case
    * the `deathDate` is within the threshold of the `reportDate` according to the formula below
* If `presentCondition` is updated to `DEAD` or `BURIED` AND there is a `deathDate` AND the `causeOfDeath` is set to `EPIDEMIC_DISEASE` AND `causeOfDeathDisease` is filled in, check if there is a case within the time threshold defined below (only retrieve the newest case with this condition) with `caseOutcome` != `DECEASED` - if there is one, set `caseOutcome` of that case to `DECEASED` and `outcomeDate` to the `deathDate` of the person
* Time threshold used for the calculations: `reportDate <= (deathDate + 30 days) && reportDate >= (deathDate - 30 days)`
* If a persons condition is changed back to alive:
   * Take the latest case, and if it is deceased change the value back to "No Outcome Yet" and set the outcomeDate to null, IF the case disease equals the old `causeOfDeathDisease`
* If only the `outcomeDate` of a deceased case is changed:
   * ONLY update the death date of the person if `outcomeDate != null && causeOfDeath==EPIDEMIC_DISEASE && causeOfDeathDisease=CaseDisease`
* If only the `deathDate` of a dead Person is changed;
   * ONLY update the `outcomeDate` of the most recent case if ` deathDatea != NULL && causeOfDeath==EPIDEMIC_DISEASE && causeOfDeathDisease=CaseDisease`
* Add unit tests for all of the above

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
Closes #4964 according to the developer specifications

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 1]
```diff
@@ -2094,24 +2092,60 @@ private void updatePersonAndCaseByOutcome(CaseDataDto existingCase, Case newCase
...
-			&& (newCase.getPerson().getDeathDate() == null
-				? newCase.getOutcomeDate() != null
-				: !newCase.getPerson().getDeathDate().equals(newCase.getOutcomeDate()))) {
-			PersonDto existingPerson = PersonFacadeEjb.toDto(newCase.getPerson());
-			newCase.getPerson().setDeathDate(newCase.getOutcomeDate());
-			personFacade.onPersonChanged(existingPerson, newCase.getPerson());
+			&& existingCase.getOutcomeDate() != newCase.getOutcomeDate()
+			&& newCase.getOutcomeDate() != null) {
+			// outcomeDate of a deceased case was changed, but person is already considered dead
+			if (newCase.getOutcomeDate() != null
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:2128]: Redundant check

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 2]
```diff
@@ -2094,24 +2092,60 @@ private void updatePersonAndCaseByOutcome(CaseDataDto existingCase, Case newCase
...
+				&& newCase.getPerson().getCauseOfDeath() == CauseOfDeath.EPIDEMIC_DISEASE
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:2129]: Move these checks to the if clause above to prevent unnecessary nested if clauses

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 3]
```diff
@@ -954,26 +962,66 @@ public void onPersonChanged(PersonDto existingPerson, Person newPerson) {
...
 		if (existingPerson != null) {
+			// sort cases based on recency
+			Collections.sort(
+				personCases,
+				(c1, c2) -> CaseLogic.getStartDate(c1.getSymptoms().getOnsetDate(), c1.getReportDate())
+					.before(CaseLogic.getStartDate(c2.getSymptoms().getOnsetDate(), c2.getReportDate())) ? 1 : -1);
+
 			if (newPerson.getPresentCondition() != null && existingPerson.getPresentCondition() != newPerson.getPresentCondition()) {
 				// Update case list after previous onCaseChanged
-				personCases = caseService.findBy(new CaseCriteria().person(new PersonReferenceDto(newPerson.getUuid())), true);
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:959]: If I'm not mistaken, you still need to refresh the personCases here because onCaseChanged might have changed something about these cases, and you won't know these changes without querying for them again - or is that incorrect?

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 4]
```diff
@@ -954,26 +962,66 @@ public void onPersonChanged(PersonDto existingPerson, Person newPerson) {
...
-						}
-					} else if (personCase.getOutcome() == CaseOutcome.DECEASED) {
+				Case personCase = personCases.isEmpty() ? null : personCases.get(0);
+				if (newPerson.getPresentCondition().isDeceased()
+					&& newPerson.getDeathDate() != null
+					&& newPerson.getCauseOfDeath() == CauseOfDeath.EPIDEMIC_DISEASE
+					&& newPerson.getCauseOfDeathDisease() != null) {
+
+					// update the latest associated case
+					if (personCase != null
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:980]: I think I wasn't specific enough in the development specifications - this logic should ONLY consider cases with disease == causeOfDeathDisease

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 5]
```diff
@@ -954,26 +962,66 @@ public void onPersonChanged(PersonDto existingPerson, Person newPerson) {
...
+						&& personCase.getOutcome() != CaseOutcome.DECEASED
+						&& (personCase.getReportDate().before(DateHelper.addDays(newPerson.getDeathDate(), 30))
+							&& personCase.getReportDate().after(DateHelper.subtractDays(newPerson.getDeathDate(), 30)))) {
+						CaseDataDto existingCase = CaseFacadeEjbLocal.toDto(personCase);
+						personCase.setOutcome(CaseOutcome.DECEASED);
+						personCase.setOutcomeDate(newPerson.getDeathDate());
+						caseFacade.onCaseChanged(existingCase, personCase);
+					}
+				} else if (!newPerson.getPresentCondition().isDeceased()
+					&& (existingPerson.getPresentCondition() == PresentCondition.DEAD
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:990]: You can use `isDeceased` here as well as a shortcut (probably in other places of the code as well)

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 6]
```diff
@@ -954,26 +962,66 @@ public void onPersonChanged(PersonDto existingPerson, Person newPerson) {
...
+					// Person was put "back alive"
+					// make sure other values are set to null
+					newPerson.setCauseOfDeath(null);
+					newPerson.setCauseOfDeathDisease(null);
+					newPerson.setDeathPlaceDescription(null);
+					newPerson.setDeathPlaceType(null);
+					newPerson.setBurialDate(null);
+					newPerson.setCauseOfDeathDisease(null);
+					// update the latest associated case, if it was set to deceased && and if the case-disease was also the causeofdeath-disease
+					if (personCase != null
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:1001]: I think this as well should probably always take the latest case of the specified disease that is within the threshold, not strictly the latest case if it is of a different disease

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 7]
```diff
@@ -954,26 +962,66 @@ public void onPersonChanged(PersonDto existingPerson, Person newPerson) {
...
 						caseFacade.onCaseChanged(existingCase, personCase);
 					}
 				}
+			} else if (newPerson.getPresentCondition() != null
+				&& newPerson.getPresentCondition().isDeceased()
+				&& newPerson.getDeathDate() != existingPerson.getDeathDate()
+				&& newPerson.getDeathDate() != null) {
+				// only Deathdate has changed
+				// update the latest associated case to the new deathdate, if causeOfDeath matches
+				Case personCase = personCases.isEmpty() ? null : personCases.get(0);
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:1016]: Here as well (again not formulated well enough in the dev specifications) - always do this for the latest case within the threshold of the specified disease (i.e. the condition is not "latest case if it has this disease" but "latest case of this disease")

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 5 above)
Comment (DavidBaldsiefen) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:990]: The `PresentCondition` of a person can also be `null`, which would lead to NPE if used with `isDeceased`

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 6 above)
Comment (DavidBaldsiefen) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:1001]: So should I just filter the `personCases` List based on `disease==causeOfDeathDisease` before doing any of the other logic?

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 8]
```diff
@@ -2094,24 +2092,60 @@ private void updatePersonAndCaseByOutcome(CaseDataDto existingCase, Case newCase
...
+				// Case was put "back alive"
+				PersonDto existingPerson = PersonFacadeEjb.toDto(newCase.getPerson());
+				boolean dateThreshold = newCase.getReportDate().before(DateHelper.addDays(existingPerson.getDeathDate(), 30))
+					&& newCase.getReportDate().after(DateHelper.subtractDays(existingPerson.getDeathDate(), 30));
+
+				if (existingPerson.getCauseOfDeath() == CauseOfDeath.EPIDEMIC_DISEASE
+					&& existingPerson.getCauseOfDeathDisease() == newCase.getDisease()
+					&& dateThreshold) {
+					// Make sure no other case associated with the person has Outcome=DECEASED
+					if (getAllCasesOfPerson(existingPerson.getUuid()).stream()
```
[the remark this answers is not in the document]
Comment (MateStrysewske) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java]: Yeah sorry, the second part was outdated, forgot to delete it :)

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Tested, works fine! Once you've implemented the remaining small change request you can merge the issue into the development branch!
