### PR TITLE
[#8674] validate shares after building them

### LINKED ISSUE #8674: Person can be shared via S2S that cannot be updated afterwards
### Bug Description
This case https://release-sormas-x.sormas.netzlink.com/sormas-ui/#!cases/data/SPUZDY-CDXBOO-XDKHIO-2C6V2A3M
was successfully shared, however, updating it (e.g., changing the birthday) won't be synchronized to the other release instance as the server will receive a bad request from the remote.

The reported error in the receiver side (i.e., which returns the 400 status code), we see thanks to #8548 the following log:

```
Formatting the human readable message failed. I18nTag: sormasToSormasSaveException, arguments: [Sie müssen mindestens eine Einrichtungsart für die Adresse angeben, für die Sie die Ansprechpartner Kontaktdaten angegeben haben.] ([de.symeda.sormas.api.sormastosormas.SormasToSormasI18nMessageError.java:50](http://de.symeda.sormas.api.sormastosormas.sormastosormasi18nmessageerror.java:50/))
```

There are two bugs here:
1. `sormasToSormasSaveException` is used in `ValidationHelper.handleValidationError` however, it contains two `%s` format strings in the German version (I did not check the others), however, only the one argument is provided which causes the formatting to fail.
2. The failed validation string is `importPersonContactDetailsWithoutFacilityType` which is used [here](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java#L628) in `PersonFacadeEjb`. Somehow it is possible to share a case successfully with another instance via S2S, however, when we sync changes, the validation kicks in when the remote tries to call back the sharer wants to get back with us.
See this log: [log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8398487/log.txt)

Probably this can be fixed by mirroring the validation logic in S2S validation before sending? But duplication is in general a bad idea, so maybe there is away to reuse it. 

### Steps to Reproduce
This is the exported case causing the problem [spudzy_repro.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/8398422/spudzy_repro.csv). Share it  with excluding personal data and observe that updating it (e.g., changing the birthday) won't be synchronized to the other release instance as the server will receive a bad request from the remote.

### Expected Behavior
Error formatting works correct and synchronization works/invalid cases are prevented from being shared in the first place

### System Details
* SORMAS version: 1.70.1
*  Release test environment

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #8674

This PR ensures that the validation logic of the EJBs runs after the shares have been built to ensure that the remote instance can process them correctly (recall that the save method on the remote will call `validate` as well, so we avoid a network round trip other problems as well).

The underlying issue is that our pseudonymizers can return data which does not pass the `validate` method of the EJBs. I made  some adjustments and I would appreciate @MateStrysewske to comment on the changes to
* LocationDto.java (more PersonalData )
* ShareDataBuilderHelper (i.e., should a valid `ContactDto` contain a reporting user?)
* SormasToSormasContactFacadeEjbTest: same w.r.t. `ContactDto`

I'm quite certain that more pseudonymizers show this behaviour and I'm going to file an issue about it tomorrow.

### CODE REVIEW

**Comment by MateStrysewske** [comment]
@JonasCir Not gonna approve/disapprove this PR, just commenting on what you wanted me to have a look at:

- Adding the annotations to the fields in LocationDto is correct
- Contacts requiring a reporting user is correct as well

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilder.java [hunk 1]
```diff
@@ -51,6 +64,8 @@ public SHARED buildShareData(ADO data, ShareRequestInfo requestInfo) throws Sorm
 		return shared;
 	}
 
+	protected abstract void validateWithEjbShared(SHARED shared) throws ValidationRuntimeException;
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilder.java:67]: I think `doBusinessValidation` would be a better name

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java [hunk 2]
```diff
@@ -98,7 +98,8 @@ public void pseudonymiePerson(PersonDto personDto, boolean pseudonymizedPersonal
 	public ContactDto getContactDto(Contact contact, Pseudonymizer pseudonymizer) {
 		ContactDto contactDto = contactFacade.convertToDto(contact, pseudonymizer);
 
-		contactDto.setReportingUser(null);
+		// reporting user is not set to null here as it would not pass the validation
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java:101]: Please create a ticket to cleanup the reporting user validation.

It's strange that only contact validation fails if it has no reporting user.

**Review by leventegal-she — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilder.java (hunk 1 above)
Comment (JonasCir) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilder.java:67]: updated

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java (hunk 2 above)
Comment (JonasCir) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/sormastosormas/share/ShareDataBuilderHelper.java:101]: filed #9701

**Review by leventegal-she — APPROVED** [review]

**Comment by JonasCir** [comment]
Hm test fails

**Review by leventegal-she — APPROVED** [review]
