### PR TITLE
#7368 - update task visibility for combination user that is both nati…

### LINKED ISSUE #7368: Tasks can be created, but are not visible by a combination user: ReST User, Admin, Sormas to Sormas Client, National User, External Visits User
### Bug Description
When logged with a combination user like this (ReST User, Admin, Sormas to Sormas Client, National User, External Visits User), the user can create new tasks but he cannot see them.

### Steps to Reproduce

1. Create a user: ReST User, Admin, Sormas to Sormas Client, National User, External Visits User
2. Log in with the user and open a case.
3. Create a task.

### System Details

* Device: Windows 10
* SORMAS version: 1.66.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: ReST User, Admin, Sormas to Sormas Client, National User, External Visits User

### Additional Information
I found this when I was testing ticket #7327

### PR DESCRIPTION
**Pull request by BarnaBartha**
…onal and user with the user right to see data outside the jurisdiction

Fixes #7368

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java [hunk 1]
```diff
@@ -499,7 +496,8 @@ public Predicate createJurisdictionFilter(CriteriaBuilder cb, From<?, User> from
 			jurisdictionFilter = cb.equal(from.get(User.REGION), currentUser.getRegion());
 		}
 
-		return CriteriaBuilderHelper.or(cb, regionalOrNationalFilter, jurisdictionFilter);
+		Predicate seePersonalDataOutsideJurisdiction = hasRight(UserRight.SEE_PERSONAL_DATA_OUTSIDE_JURISDICTION) ? cb.conjunction() : cb.disjunction();
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java:499]: Instead of doing this, return `cb.conjunction()` in the if block that you removed at the start of the method and leave the rest of the method untouched (avoids unnecessary code execution)

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Review by MateStrysewske — APPROVED** [review]
