### PR TITLE
#6144 Import module should not consider white spaces for infrastructure data names

### LINKED ISSUE #6144: Import module should not consider white spaces for infrastructure data names
### Bug Description

Region name with white spaces after the name on import data are not mapped with the same region in the system.

### Steps to Reproduce

1. Create a region in the sytem
2. Import a hospital in the region, on import template, use region name with space at the end, eg "Berlin "
3. System does not map the region with the "Berlin" in the system

### Expected Behavior

- Delete white spaces before of after the name before matching
- I think we should not delete white spaces within the name, eg "New Berlin" should not be mapped with "NewBerlin"
- Character case should not also matter berlin == BerLin
### System Details

* Device:
* SORMAS version: 1.60.3
* Android version/Browser:
* Server URL: https://test-inhp-ci.sormas.netzlink.com/sormas-ui/#!about
* User Role:

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #6144

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/caseimport/CaseImportFacadeEjb.java [hunk 1]
```diff
@@ -351,7 +351,7 @@
 		List<String> invalidColumns = new ArrayList<>();
 
 		for (int i = 0; i < values.length; i++) {
-			String value = values[i];
+			String value = values[i] != null ? values[i].trim() : values[i];
```
Comment (vidi42) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/caseimport/CaseImportFacadeEjb.java:354]: Just a suggestion. `StringUtils.trimToNull(values[i])` achieves the same and maybe it's easier to read.

**Review by Alexandru-Pirvu — APPROVED** [review]

**Review by vidi42 — APPROVED** [review]
