### PR TITLE
#8946 Improve performance of PersonService.getAllAfter

### LINKED ISSUE #8946: Improve performance of PersonService.getAllAfter method [3]
### Problem Description
In the REST API, `getAllAfter` methods tend to be slow for large numbers of entities to be sent, up to possible timeouts.
See **Additional Information** for a detailed analysis.

### Proposed Change

For this issue we should only work on improving PersonService.getAllAfter.

- [x] Instead of directly querying the whole Person, only query for id, uuid and changeDate in PersonService.getAllAfter for immunizations, cases, etc. Unify, sort, distinct and limit the combined results of those queries. Use the ids to query for the actual persons - here try to fetch all needed data directly to mitigate lazy loading queries.
- [x] Add the following indices. Make sure cases, etc. also have the index for person_id
```
  CREATE INDEX idx_person_changedate_uuid_id ON public.person USING btree (changedate ASC, uuid ASC, id ASC);
  CREATE INDEX idx_immunization_person ON public.immunization USING btree (person_id);
```
- [x] If this works out correct, get in contact with @StefanKock or @MartinWahnschaffe to create a follow-up issue for getAllAfter methods of other entities. -> #9320

### System Details

* Device:
* SORMAS version: 1.71.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role: Rest User

### Additional Information

Also check this comment for an analysis including explain analyze results: https://github.com/hzi-braunschweig/SORMAS-Project/issues/8946#issuecomment-1129937176

See first analysis for an overview on runtimes for different REST methods.

Some additional research on `PersonService.getAllAfter` shows:
- joins on large tables (> 1000000 entries) result in exceptional query runtimes, increased by factor ~2 by redundancies introduced by hibernate
- adding indexes results in medium improvement
- hibernate fetching has a relevant effect for  large batch sizes, even without single queries with exceptional runtimes

**Note:** testes version has progressed to 1.72.0-SNAPSHOT

<details><summary>First Analysis</summary>

Dataset:
- 1225343 persons
- 85677 cases
- 114782 contacts
- 236583 tasks
- 2600890 immunizations
- 1991 vaccinations
- 15693 samples
- 11846 events
- 534 eventparticipants

The following measurements were taken from backend logs (EJB methods) and the Postgres logs.
Observations:
- the actual SQL queries are executed in few seconds while the EJB methods take minutes to complete
- a relevant contribution to runtime comes from `inJurisdictionOrOwned` methods, here mainly the number of calls
- batch size is relevant. Some requests did not complete within reasonable time for a batch size of 10000, these were measured for batch size 1000.

Requests:
- `http://localhost:6080/sormas-rest/persons/all/1637090372005/10000/NO_LAST_SYNCED_UUID`: 3 min 5 sec
server: 2 min 58 sec
image
SQL queries:
duration: 948.716 ms
duration: 2297.275 ms
duration: 4012.220 ms
duration: 4393.538 ms
duration: 696.277 ms
~ 12.5 sec
**Note:** SQL query times are inaccurate, either due to an error in the analysis or changes introduced later, see later analysis of this method.

- `http://localhost:6080/sormas-rest/cases/all/1637090372005/10000/NO_LAST_SYNCED_UUID`: 8 min 21 sec
server: 8 min 18 sec
image
SQL queries:
duration: 787.011 ms
duration: 449.616 ms
duration: 146.224 ms
duration: 178.515 ms
duration: 154.552 ms
duration: 136.836 ms
duration: 142.597 ms
duration: 143.688 ms
duration: 150.584 ms
duration: 152.298 ms
duration: 133.814 ms
duration: 147.687 ms
~ 3 sec

- `http://localhost:6080/sormas-rest/contacts/all/1637090372005/10000/NO_LAST_SYNCED_UUID`: 35 sec
server: 35 sec
image
SQL queries:
duration: 151.413 ms
duration: 143.237 ms
duration: 152.661 ms
duration: 144.054 ms
duration: 145.374 ms
duration: 155.861 ms
duration: 177.212 ms
duration: 153.647 ms
duration: 201.516 ms
duration: 187.382 ms
~ 1.6 sec

- `http://localhost:6080/sormas-rest/tasks/all/1637090372005/1000/NO_LAST_SYNCED_UUID`: 1 min 27 sec
server: 1 min 24 sec
image
SQL queries:
duration: 466.097 ms
duration: 154.093 ms
duration: 132.150 ms
duration: 137.751 ms
duration: 140.757 ms
duration: 135.526 ms
duration: 136.612 ms
duration: 126.399 ms
duration: 124.695 ms
duration: 127.888 ms
duration: 133.940 ms
~1.9 sec

- `http://localhost:6080/sormas-rest/samples/all/1637090372005/10000/NO_LAST_SYNCED_UUID`: 27 sec
server: 27 sec
image
SQL queries:
duration: 129.587 ms

- `http://localhost:6080/sormas-rest/immunizations/all/1637090372005/1000/NO_LAST_SYNCED_UUID` (1min 50 sec)
server: 1 min 48 sec
image
SQL queries:
duration: 6985.128 ms
duration: 106.608 ms
~ 7 sec
</details>

<details><summary>Analysis of `PersonService.getAllAfter`</summary>

Analysis of `PersonService.getAllAfter`: Instrumented the method with a stop watch for individual steps (persons are associated to either district, case, contact, event participant, immunization or travel entry and are retrieved as such). The instrumented version was executed to fetch 10, 1000 or 10000 entries.
(Note: tested version has been progressed to 1.72.0-SNAPSHOT, some of the database entries have been deleted by automated deletion)

Result:
image

Notable is that the times spent for immunization are much closer for the different batch sizes (70470 to 83377 ms) while the other steps show greater variations (e.g., 2409 to 38397 ms for district) which can likely be attributed to hibernate fetching, i.e., after identifying the entities to be retrieved (which is usually a longer running query) to fetch dependent subentities and fill missing data.

Analysis of the SQL log for the run of 1000 entries shows one particularly long running query (70913.899 ms) while all others remain in a range clearly below 10000 ms (or 10 seconds). The total number of queries is 11913 (~10 per entry), supporting the hypothesis of prolonged hibernate fetching for larger batch sizes.

The outstanding query - accounting for most of the time spent for immunizations - is identified as:
```sql
select
        distinct person1_.id as id1_42_0_,
        location3_.id as id1_37_1_,
        person1_.changeDate as changeda2_42_0_,
        person1_.change_user_id as change_51_42_0_,
        person1_.creationDate as creation3_42_0_,
        person1_.uuid as uuid4_42_0_,
        person1_.additionalDetails as addition5_42_0_,
        person1_.address_id as address52_42_0_,
        person1_.approximateAge as approxim6_42_0_,
        person1_.approximateAgeReferenceDate as approxim7_42_0_,
        person1_.approximateAgeType as approxim8_42_0_,
        person1_.armedForcesRelationType as armedfor9_42_0_,
        person1_.birthCountry_id as birthco53_42_0_,
        person1_.birthName as birthna10_42_0_,
        person1_.birthWeight as birthwe11_42_0_,
        person1_.birthdate_dd as birthda12_42_0_,
        person1_.birthdate_mm as birthda13_42_0_,
        person1_.birthdate_yyyy as birthda14_42_0_,
        person1_.burialConductor as burialc15_42_0_,
        person1_.burialDate as buriald16_42_0_,
        person1_.burialPlaceDescription as burialp17_42_0_,
        person1_.causeOfDeath as causeof18_42_0_,
        person1_.causeOfDeathDetails as causeof19_42_0_,
        person1_.causeOfDeathDisease as causeof20_42_0_,
        person1_.changeDateOfEmbeddedLists as changed21_42_0_,
        person1_.citizenship_id as citizen54_42_0_,
        person1_.covidCodeDelivered as covidco22_42_0_,
        person1_.deathDate as deathda23_42_0_,
        person1_.deathPlaceDescription as deathpl24_42_0_,
        person1_.deathPlaceType as deathpl25_42_0_,
        person1_.educationDetails as educati26_42_0_,
        person1_.educationType as educati27_42_0_,
        person1_.externalId as externa28_42_0_,
        person1_.externalToken as externa29_42_0_,
        person1_.fathersName as fathers30_42_0_,
        person1_.firstName as firstna31_42_0_,
        person1_.gestationAgeAtBirth as gestati32_42_0_,
        person1_.hasCovidApp as hascovi33_42_0_,
        person1_.internalToken as interna34_42_0_,
        person1_.lastName as lastnam35_42_0_,
        person1_.mothersMaidenName as mothers36_42_0_,
        person1_.mothersName as mothers37_42_0_,
        person1_.namesOfGuardians as namesof38_42_0_,
        person1_.nationalHealthId as nationa39_42_0_,
        person1_.nickname as nicknam40_42_0_,
        person1_.occupationDetails as occupat41_42_0_,
        person1_.occupationType as occupat42_42_0_,
        person1_.otherSalutation as othersa43_42_0_,
        person1_.passportNumber as passpor44_42_0_,
        person1_.placeOfBirthCommunity_id as placeof55_42_0_,
        person1_.placeOfBirthDistrict_id as placeof56_42_0_,
        person1_.placeOfBirthFacility_id as placeof57_42_0_,
        person1_.placeOfBirthFacilityDetails as placeof45_42_0_,
        person1_.placeOfBirthFacilityType as placeof46_42_0_,
        person1_.placeOfBirthRegion_id as placeof58_42_0_,
        person1_.presentCondition as present47_42_0_,
        person1_.salutation as salutat48_42_0_,
        person1_.sex as sex49_42_0_,
        person1_.symptomJournalStatus as symptom50_42_0_,
        location3_.changeDate as changeda2_37_1_,
        location3_.change_user_id as change_23_37_1_,
        location3_.creationDate as creation3_37_1_,
        location3_.uuid as uuid4_37_1_,
        location3_.additionalInformation as addition5_37_1_,
        location3_.addressType as addresst6_37_1_,
        location3_.addressTypeDetails as addresst7_37_1_,
        location3_.areaType as areatype8_37_1_,
        location3_.city as city9_37_1_,
        location3_.community_id as communi24_37_1_,
        location3_.contactPersonEmail as contact10_37_1_,
        location3_.contactPersonFirstName as contact11_37_1_,
        location3_.contactPersonLastName as contact12_37_1_,
        location3_.contactPersonPhone as contact13_37_1_,
        location3_.continent_id as contine25_37_1_,
        location3_.country_id as country26_37_1_,
        location3_.details as details14_37_1_,
        location3_.district_id as distric27_37_1_,
        location3_.facility_id as facilit28_37_1_,
        location3_.facilityDetails as facilit15_37_1_,
        location3_.facilityType as facilit16_37_1_,
        location3_.houseNumber as housenu17_37_1_,
        location3_.latLonAccuracy as latlona18_37_1_,
        location3_.latitude as latitud19_37_1_,
        location3_.longitude as longitu20_37_1_,
        location3_.postalCode as postalc21_37_1_,
        location3_.region_id as region_29_37_1_,
        location3_.street as street22_37_1_,
        location3_.subcontinent_id as subcont30_37_1_,
        location3_1_.person_id as person_i1_43_1_ 
    from
        immunization immunizati0_ 
    inner join
        Person person1_ 
            on immunizati0_.person_id=person1_.id 
    inner join
        Location location2_ 
            on person1_.address_id=location2_.id 
    left outer join
        person_locations location2_1_ 
            on location2_.id=location2_1_.location_id 
    inner join
        Location location3_ 
            on person1_.address_id=location3_.id 
    left outer join
        person_locations location3_1_ 
            on location3_.id=location3_1_.location_id 
    where
        (
            (
                immunizati0_.reportingUser_id is not null
            ) 
            and immunizati0_.reportingUser_id=31 
            or immunizati0_.responsibleDistrict_id=2
        ) 
        and (
            person1_.changeDate>='1970-01-01 01:00:00.001' 
            and (
                person1_.changeDate is not null
            ) 
            or location2_.changeDate>='1970-01-01 01:00:00.001' 
            and (
                location2_.changeDate is not null
            )
        ) 
    order by
        person1_.changeDate asc,
        person1_.uuid asc limit 10000
```
To be noted is that the (smallest) number of entries in any of the tables in inner joins is a magnitude larger than in other steps (persons: 1087743, immunizations: 2600890, locations: 1103758, whereas, e.g., case is at 85677

For further examination, missing indexes on the key columns for joins are added, reducing the query time to 59704 ms:
```sql
CREATE INDEX idx_person_changedate ON public.person USING btree (changedate DESC);

CREATE INDEX idx_location_changedate ON public.location USING btree (changedate DESC);

CREATE INDEX idx_immunization_reportinguser ON public.immunization USING btree (reportingUser_id, responsibleDistrict_id);

CREATE INDEX idx_immunization_person ON public.immunization USING btree (person_id);

CREATE INDEX idx_personlocation_location ON public.person_locations  USING btree (location_id);
```

The query was then cut down by hand to identify expensive parts.

Notable are redundant joins on `location` and `person_locations`, where the join is alway on `location.id`:
```sql
...
    inner join
        Location location2_ 
            on person1_.address_id=location2_.id 
    left outer join
        person_locations location2_1_ 
            on location2_.id=location2_1_.location_id 
    inner join
        Location location3_ 
            on person1_.address_id=location3_.id 
    left outer join
        person_locations location3_1_ 
            on location3_.id=location3_1_.location_id 
```

Removing the redundancy, query time is reduced to 27633 ms:
```sql
	select
	        distinct person1_.id as id1_42_0_,
	        person1_.changeDate as changeda2_42_0_,
	        person1_.change_user_id as change_51_42_0_,
	        person1_.creationDate as creation3_42_0_,
	        person1_.uuid as uuid4_42_0_,
	        person1_.additionalDetails as addition5_42_0_,
	        person1_.address_id as address52_42_0_,
	        person1_.approximateAge as approxim6_42_0_,
	        person1_.approximateAgeReferenceDate as approxim7_42_0_,
	        person1_.approximateAgeType as approxim8_42_0_,
	        person1_.armedForcesRelationType as armedfor9_42_0_,
	        person1_.birthCountry_id as birthco53_42_0_,
	        person1_.birthName as birthna10_42_0_,
	        person1_.birthWeight as birthwe11_42_0_,
	        person1_.birthdate_dd as birthda12_42_0_,
	        person1_.birthdate_mm as birthda13_42_0_,
	        person1_.birthdate_yyyy as birthda14_42_0_,
	        person1_.burialConductor as burialc15_42_0_,
	        person1_.burialDate as buriald16_42_0_,
	        person1_.burialPlaceDescription as burialp17_42_0_,
	        person1_.causeOfDeath as causeof18_42_0_,
	        person1_.causeOfDeathDetails as causeof19_42_0_,
	        person1_.causeOfDeathDisease as causeof20_42_0_,
	        person1_.changeDateOfEmbeddedLists as changed21_42_0_,
	        person1_.citizenship_id as citizen54_42_0_,
	        person1_.covidCodeDelivered as covidco22_42_0_,
	        person1_.deathDate as deathda23_42_0_,
	        person1_.deathPlaceDescription as deathpl24_42_0_,
	        person1_.deathPlaceType as deathpl25_42_0_,
	        person1_.educationDetails as educati26_42_0_,
	        person1_.educationType as educati27_42_0_,
	        person1_.externalId as externa28_42_0_,
	        person1_.externalToken as externa29_42_0_,
	        person1_.fathersName as fathers30_42_0_,
	        person1_.firstName as firstna31_42_0_,
	        person1_.gestationAgeAtBirth as gestati32_42_0_,
	        person1_.hasCovidApp as hascovi33_42_0_,
	        person1_.internalToken as interna34_42_0_,
	        person1_.lastName as lastnam35_42_0_,
	        person1_.mothersMaidenName as mothers36_42_0_,
	        person1_.mothersName as mothers37_42_0_,
	        person1_.namesOfGuardians as namesof38_42_0_,
	        person1_.nationalHealthId as nationa39_42_0_,
	        person1_.nickname as nicknam40_42_0_,
	        person1_.occupationDetails as occupat41_42_0_,
	        person1_.occupationType as occupat42_42_0_,
	        person1_.otherSalutation as othersa43_42_0_,
	        person1_.passportNumber as passpor44_42_0_,
	        person1_.placeOfBirthCommunity_id as placeof55_42_0_,
	        person1_.placeOfBirthDistrict_id as placeof56_42_0_,
	        person1_.placeOfBirthFacility_id as placeof57_42_0_,
	        person1_.placeOfBirthFacilityDetails as placeof45_42_0_,
	        person1_.placeOfBirthFacilityType as placeof46_42_0_,
	        person1_.placeOfBirthRegion_id as placeof58_42_0_,
	        person1_.presentCondition as present47_42_0_,
	        person1_.salutation as salutat48_42_0_,
	        person1_.sex as sex49_42_0_,
	        person1_.symptomJournalStatus as symptom50_42_0_,
	        location2_.longitude as longitu20_37_1_,
            location2_.postalCode as postalc21_37_1_,
            location2_.region_id as region_29_37_1_,
            location2_.street as street22_37_1_,
            location2_.subcontinent_id as subcont30_37_1_
    from
        immunization immunizati0_ 
    inner join
        Person person1_ 
        on immunizati0_.person_id=person1_.id 
    inner join
        Location location2_ 
            on person1_.address_id=location2_.id
    where
        (
            (
                immunizati0_.reportingUser_id is not null
            ) 
            and immunizati0_.reportingUser_id=31 
            or immunizati0_.responsibleDistrict_id=2
        ) 
        and (
            person1_.changeDate>='1970-01-01 01:00:00.001' 
            and (
                person1_.changeDate is not null
            )
            or location2_.changeDate>='1970-01-01 01:00:00.001' 
            and (
                location2_.changeDate is not null
            )
            ) 
	    order by
	        person1_.id asc,
	        person1_.uuid asc limit 10000;
```

For further examination, I also cut out the join on location, leaving a join of `immunization` and `person`, which cuts down query time to 11102 ms:
```sql
	select
	        distinct person1_.id as id1_42_0_,
	        person1_.changeDate as changeda2_42_0_,
	        person1_.change_user_id as change_51_42_0_,
	        person1_.creationDate as creation3_42_0_,
	        person1_.uuid as uuid4_42_0_,
	        person1_.additionalDetails as addition5_42_0_,
	        person1_.address_id as address52_42_0_,
	        person1_.approximateAge as approxim6_42_0_,
	        person1_.approximateAgeReferenceDate as approxim7_42_0_,
	        person1_.approximateAgeType as approxim8_42_0_,
	        person1_.armedForcesRelationType as armedfor9_42_0_,
	        person1_.birthCountry_id as birthco53_42_0_,
	        person1_.birthName as birthna10_42_0_,
	        person1_.birthWeight as birthwe11_42_0_,
	        person1_.birthdate_dd as birthda12_42_0_,
	        person1_.birthdate_mm as birthda13_42_0_,
	        person1_.birthdate_yyyy as birthda14_42_0_,
	        person1_.burialConductor as burialc15_42_0_,
	        person1_.burialDate as buriald16_42_0_,
	        person1_.burialPlaceDescription as burialp17_42_0_,
	        person1_.causeOfDeath as causeof18_42_0_,
	        person1_.causeOfDeathDetails as causeof19_42_0_,
	        person1_.causeOfDeathDisease as causeof20_42_0_,
	        person1_.changeDateOfEmbeddedLists as changed21_42_0_,
	        person1_.citizenship_id as citizen54_42_0_,
	        person1_.covidCodeDelivered as covidco22_42_0_,
	        person1_.deathDate as deathda23_42_0_,
	        person1_.deathPlaceDescription as deathpl24_42_0_,
	        person1_.deathPlaceType as deathpl25_42_0_,
	        person1_.educationDetails as educati26_42_0_,
	        person1_.educationType as educati27_42_0_,
	        person1_.externalId as externa28_42_0_,
	        person1_.externalToken as externa29_42_0_,
	        person1_.fathersName as fathers30_42_0_,
	        person1_.firstName as firstna31_42_0_,
	        person1_.gestationAgeAtBirth as gestati32_42_0_,
	        person1_.hasCovidApp as hascovi33_42_0_,
	        person1_.internalToken as interna34_42_0_,
	        person1_.lastName as lastnam35_42_0_,
	        person1_.mothersMaidenName as mothers36_42_0_,
	        person1_.mothersName as mothers37_42_0_,
	        person1_.namesOfGuardians as namesof38_42_0_,
	        person1_.nationalHealthId as nationa39_42_0_,
	        person1_.nickname as nicknam40_42_0_,
	        person1_.occupationDetails as occupat41_42_0_,
	        person1_.occupationType as occupat42_42_0_,
	        person1_.otherSalutation as othersa43_42_0_,
	        person1_.passportNumber as passpor44_42_0_,
	        person1_.placeOfBirthCommunity_id as placeof55_42_0_,
	        person1_.placeOfBirthDistrict_id as placeof56_42_0_,
	        person1_.placeOfBirthFacility_id as placeof57_42_0_,
	        person1_.placeOfBirthFacilityDetails as placeof45_42_0_,
	        person1_.placeOfBirthFacilityType as placeof46_42_0_,
	        person1_.placeOfBirthRegion_id as placeof58_42_0_,
	        person1_.presentCondition as present47_42_0_,
	        person1_.salutation as salutat48_42_0_,
	        person1_.sex as sex49_42_0_,
	        person1_.symptomJournalStatus as symptom50_42_0_
/*	        location2_.longitude as longitu20_37_1_,
            location2_.postalCode as postalc21_37_1_,
            location2_.region_id as region_29_37_1_,
            location2_.street as street22_37_1_,
            location2_.subcontinent_id as subcont30_37_1_ */
    from
        immunization immunizati0_ 
    inner join
        Person person1_ 
        on immunizati0_.person_id=person1_.id 
/*    inner join
        Location location2_ 
            on person1_.address_id=location2_.id */
    where
        (
            (
                immunizati0_.reportingUser_id is not null
            ) 
            and immunizati0_.reportingUser_id=31 
            or immunizati0_.responsibleDistrict_id=2
        ) 
        and (
            person1_.changeDate>='1970-01-01 01:00:00.001' 
            and (
                person1_.changeDate is not null
            ) /*
            or location2_.changeDate>='1970-01-01 01:00:00.001' 
            and (
                location2_.changeDate is not null
            ) */
            ) 
	    order by
	        person1_.id asc,
	        person1_.uuid asc limit 10000;
``` 

For comparison: a fetch on persons only with the condition on `changeDate` is 1725 ms:
```sql
	select
	        distinct person1_.id as id1_42_0_,
	        person1_.changeDate as changeda2_42_0_,
	        person1_.change_user_id as change_51_42_0_,
	        person1_.creationDate as creation3_42_0_,
	        person1_.uuid as uuid4_42_0_,
	        person1_.additionalDetails as addition5_42_0_,
	        person1_.address_id as address52_42_0_,
	        person1_.approximateAge as approxim6_42_0_,
	        person1_.approximateAgeReferenceDate as approxim7_42_0_,
	        person1_.approximateAgeType as approxim8_42_0_,
	        person1_.armedForcesRelationType as armedfor9_42_0_,
	        person1_.birthCountry_id as birthco53_42_0_,
	        person1_.birthName as birthna10_42_0_,
	        person1_.birthWeight as birthwe11_42_0_,
	        person1_.birthdate_dd as birthda12_42_0_,
	        person1_.birthdate_mm as birthda13_42_0_,
	        person1_.birthdate_yyyy as birthda14_42_0_,
	        person1_.burialConductor as burialc15_42_0_,
	        person1_.burialDate as buriald16_42_0_,
	        person1_.burialPlaceDescription as burialp17_42_0_,
	        person1_.causeOfDeath as causeof18_42_0_,
	        person1_.causeOfDeathDetails as causeof19_42_0_,
	        person1_.causeOfDeathDisease as causeof20_42_0_,
	        person1_.changeDateOfEmbeddedLists as changed21_42_0_,
	        person1_.citizenship_id as citizen54_42_0_,
	        person1_.covidCodeDelivered as covidco22_42_0_,
	        person1_.deathDate as deathda23_42_0_,
	        person1_.deathPlaceDescription as deathpl24_42_0_,
	        person1_.deathPlaceType as deathpl25_42_0_,
	        person1_.educationDetails as educati26_42_0_,
	        person1_.educationType as educati27_42_0_,
	        person1_.externalId as externa28_42_0_,
	        person1_.externalToken as externa29_42_0_,
	        person1_.fathersName as fathers30_42_0_,
	        person1_.firstName as firstna31_42_0_,
	        person1_.gestationAgeAtBirth as gestati32_42_0_,
	        person1_.hasCovidApp as hascovi33_42_0_,
	        person1_.internalToken as interna34_42_0_,
	        person1_.lastName as lastnam35_42_0_,
	        person1_.mothersMaidenName as mothers36_42_0_,
	        person1_.mothersName as mothers37_42_0_,
	        person1_.namesOfGuardians as namesof38_42_0_,
	        person1_.nationalHealthId as nationa39_42_0_,
	        person1_.nickname as nicknam40_42_0_,
	        person1_.occupationDetails as occupat41_42_0_,
	        person1_.occupationType as occupat42_42_0_,
	        person1_.otherSalutation as othersa43_42_0_,
	        person1_.passportNumber as passpor44_42_0_,
	        person1_.placeOfBirthCommunity_id as placeof55_42_0_,
	        person1_.placeOfBirthDistrict_id as placeof56_42_0_,
	        person1_.placeOfBirthFacility_id as placeof57_42_0_,
	        person1_.placeOfBirthFacilityDetails as placeof45_42_0_,
	        person1_.placeOfBirthFacilityType as placeof46_42_0_,
	        person1_.placeOfBirthRegion_id as placeof58_42_0_,
	        person1_.presentCondition as present47_42_0_,
	        person1_.salutation as salutat48_42_0_,
	        person1_.sex as sex49_42_0_,
	        person1_.symptomJournalStatus as symptom50_42_0_
    from
        Person person1_ 
    where
            person1_.changeDate>='1970-01-01 01:00:00.001' 
            and (
                person1_.changeDate is not null
            )
	    order by
	        person1_.id asc,
	        person1_.uuid asc limit 10000;
```

Summary: for the above examinations, the following query times for this particular database resulted:
- original query executed from the SORMAS server: ~ 70 sec
- adding indexes: ~ 60 sec
- removing redundancies on location joins: ~ 28 sec
- dropping join on locations altogether, leaving `immunization` joined on `person`: ~ 11 sec
- fetch on `person` only: ~1.7 sec 
</details>

### PR DESCRIPTION
**Pull request by StefanKock**
Fixes #8946

### CODE REVIEW

**Review by MateStrysewske — COMMENTED** [review]
Looks good to me - not approving because the PR is still set as a draft and I haven't tested it yet because of that.

**Review by BarnaBartha — APPROVED** [review]
looks good, do you have also some measurement results?

**Review by syntakker — APPROVED** [review]

**Comment by syntakker** [comment]
Error when updating the database schema. Reproducible with a fresh database.
Exception:
```
[2022-06-01T09:43:35.854+0200] [Payara 5.2021.10] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=126 _ThreadName=admin-thread-pool::admin-listener(1)] [timeMillis: 1654069415854] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbApplication start method
javax.ejb.EJBException: javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:689)
	at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:421)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
	at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:159)
	at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:171)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:123)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:292)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:361)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.initialize(ApplicationLifecycle.java:623)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:592)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:552)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:551)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:582)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:574)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:573)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1497)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:120)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1879)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1755)
	at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:409)
	at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
	at org.glassfish.admin.rest.adapter.JerseyContainerCommandService$3.service(JerseyContainerCommandService.java:179)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:189)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.ejb.CreateException: Initialization failed for Singleton StartupShutdownService
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:542)
	at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:81)
	at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:687)
	... 69 more
Caused by: java.util.NoSuchElementException: 461
	at de.symeda.sormas.backend.common.StartupShutdownService.upgrade(StartupShutdownService.java:753)
	at de.symeda.sormas.backend.common.StartupShutdownService.startup(StartupShutdownService.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1022)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:978)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:204)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:978)
	at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:418)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:381)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:2071)
	at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:529)
	... 71 more
]]
```

File: sormas-backend/src/main/resources/sql/sormas_schema.sql [hunk 1]
```diff
@@ -11525,4 +11525,18 @@ CREATE TRIGGER delete_history_trigger_userroles_smsnotificationtypes
...
+DROP INDEX IF EXISTS idx_eventparticipant_person_id;
+DROP INDEX IF EXISTS idx_contact_person_id;
+CREATE INDEX IF NOT EXISTS idx_person_changedate_uuid_id ON person USING btree (changedate ASC, uuid ASC, id ASC);
+CREATE INDEX IF NOT EXISTS idx_cases_person_id ON cases USING btree (person_id);
+CREATE INDEX IF NOT EXISTS idx_contact_person_id ON contact USING btree (person_id);
+CREATE INDEX IF NOT EXISTS idx_eventparticipant_person_id ON eventparticipant USING btree (person_id);
+CREATE INDEX IF NOT EXISTS idx_immunization_person_id ON immunization USING btree (person_id);
+CREATE INDEX IF NOT EXISTS idx_travelentry_person_id ON travelentry USING btree (person_id);
+
+INSERT INTO schema_version (version_number, comment, upgradeNeeded) VALUES (461, 'Add hash indices to improve person fetch #8946', true);
```
Comment (StefanKock) [inline sormas-backend/src/main/resources/sql/sormas_schema.sql:11539]: upgradeNeeded has to be false, because there is no Java migration part
