### PR TITLE
#7533 - Exclude events without disease from vaccination migration

### LINKED ISSUE #7533: Exclude events without a disease from the vaccination migration script
### Bug Description

Vaccination information gathered during the migration includes events without a disease, which leads to problems when inserting immunizations (because a disease is required for those). Vaccination information connected to event participants without a disease are not of any use anyway because there's no information for which disease the event participant has been vaccinated.

### Steps to Reproduce

1.
2.

### Expected Behavior

Exclude events without a disease from the data collection part of the migration script.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #7533

### CODE REVIEW

File: sormas-backend/src/main/resources/sql/sormas_schema.sql [hunk 1]
```diff
@@ -8108,7 +8108,7 @@ UNION
              LEFT JOIN events ON eventparticipant.event_id = events.id
              LEFT JOIN location ON events.eventlocation_id = location.id
              LEFT JOIN vaccinationinfo ON eventparticipant.vaccinationinfo_id = vaccinationinfo.id
-    WHERE vaccinationinfo.vaccination = 'VACCINATED' AND eventparticipant.deleted = false
+    WHERE vaccinationinfo.vaccination = 'VACCINATED' AND eventparticipant.deleted = false AND events.disease IS NOT NULL
```
Comment (BarnaBartha) [inline sormas-backend/src/main/resources/sql/sormas_schema.sql:8111]: this should be done not only for tmp_vaccinated_entities but also for tmp_earlier_vaccinated_entities

**Review by BarnaBartha — CHANGES_REQUESTED** [review]

**Review by BarnaBartha — APPROVED** [review]
