### PR TITLE
#10188 - show the configuration page only to users having user right …

### LINKED ISSUE #10188: A user with a configured User Role gets an error message when opening the Configuration Directory
### Bug Description
A user with a configured User Role (Infrastructure = Yes to all and Configuration = No to all) gets an error message when he opens the Configuration Directory. 

### Steps to Reproduce

1. Logged in with an Admin, navigate to the Users Directory;
2. Create a new User Role with the following User Rights: General (Access Sormas UI: Yes); Infrastructure (Yes all); Configuration (No all); the other ones are all No;
3. Create a user with the newly created user role;
4. Log in with that user;

### Actual Behavior
The Configuration Directory is shown and if the user opens it, he receives an error.

### Expected Behavior
The Configuration Directory should show only the tabs that have the corresponding user right set to 'true' (eg.  'View regions/districts/communities/facilities in the system' = true; 'View outbreaks' = false)

### Screenshots
image

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.75.0-SNAPSHOT (68389ec)
* Android version/Browser: Chrome
* Server URL: local instance
* User Role:

### Additional Information
The error was triggered because 'View outbreaks' was set to 'false'

### PR DESCRIPTION
**Pull request by BarnaBartha**
…of the group configuration

Fixes #10188

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/UserProvider.java [hunk 1]
```diff
@@ -86,7 +80,7 @@ public JurisdictionLevel getJurisdictionLevel() {
 
 	public boolean hasConfigurationAccess() {
 		Set<UserRight> currentUserRights = getUserRights();
-		return configurationUserRoles.stream().anyMatch(currentUserRights::contains);
+		return UserRight.getUserRightsOfGroup(UserRightGroup.CONFIGURATION).stream().anyMatch(currentUserRights::contains);
```
Comment (sergiupacurariu) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/UserProvider.java:83]: Configuration menu should be shown if Infrastructure rights are active

**Review by sergiupacurariu — APPROVED** [review]
