### PR TITLE
bug/9382_poe_natuser_place_of_stay

### LINKED ISSUE #9382: 'Place of Stay' shouldn't be mandatory in the Case Creation form for the POE NatUser
### Bug Description
The 'Place of Stay' field is mandatory in the Case Creation form for the POE National User, even though it shouldn't be.
For other users, this section is not mandatory.

### Steps to Reproduce

1. Log in with POE National User.
2. Navigate to the Cases Directory and click on the 'New Case' button.
3. Inspect the 'Place of Stay' section.

### Expected Behavior
The 'Place of Stay' field shouldn't be mandatory.

### Screenshots
POE NatUser
image

Other users (eg. NatUser, Admin etc.)
image

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.72.1
* Android version/Browser: Chrome
* Server URL: test1402.sormas.netzlink.com and local machine
* User Role: POE National User

### Additional Information

The user role dependent behaviour is defined here: `CaseCreateForm:391ff` It's mostly dependent on the user not to be a "portHealth" user and `CaseOrigin.IN_COUNTRY`.

### PR DESCRIPTION
**Pull request by dinua**
Fixes #9382

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java [hunk 1]
```diff
@@ -435,8 +435,11 @@ protected void addFields() {
 
 		// Set initial visibilities & accesses
 		initializeVisibilitiesAndAllowedVisibilities();
-
-		setRequired(true, CaseDataDto.REPORT_DATE, CaseDataDto.DISEASE, FACILITY_OR_HOME_LOC, FACILITY_TYPE_GROUP_LOC, CaseDataDto.FACILITY_TYPE);
+		
+		setRequired(true, CaseDataDto.REPORT_DATE, CaseDataDto.DISEASE, FACILITY_TYPE_GROUP_LOC, CaseDataDto.FACILITY_TYPE);
+		if (!UserProvider.getCurrent().isPortHealthUser()) {
```
Comment (sergiupacurariu) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java:440]: this condition can be found in the class twice. Please add your changes under the other already existing condition.

**Review by sergiupacurariu — APPROVED** [review]
