### PR TITLE
#9857: Added visit user info to visit export

### LINKED ISSUE #9857: User name from the 'Visit Origin' column is missing when exporting visits
### Bug Description

When generating an export file of case follow-up visits or contact follow-up visits, the 'Visit Origin' column is showing only the 'Created by user' information but not the actual user as well, as it is displayed in the UI.

### Steps to Reproduce

1. Open a case or a contact and create a follow-up visit for it;
2. Generate an export excel file from the 'Follow-up visits' tab of the case or contact;
3. Observe the 'Visit origin' column of the excel file.

### Actual Behavior

The name of the user that created the visit is not visible in the export file.

### Expected Behavior

The name of the user that created the visit should be visible in the export file.

### Screenshots

Follow-up visits list in the web-app:
image

Follow-up export excel file:
image

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(7e4e9eb)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### PR DESCRIPTION
**Pull request by ChristopherRiedel**
Fixes #9857

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java [hunk 1]
```diff
@@ -462,9 +465,25 @@ public List<VisitExportDto> getVisitsExportList(
 			if (resultList.size() > 0) {
 
 				Pseudonymizer pseudonymizer = Pseudonymizer.getDefault(userService::hasRight);
+				Map<Long, UserReference> visitUsers =
+					userService
+						.getUserReferencesByIds(
+							resultList.stream()
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java:471]: Please do `.map(VisitExportDto:: getVisitUserId)` instead of `.map(c -> Arrays.asList(c.getVisitUserId())).flatMap(Collection::stream)`

There is no need to create a stream of lists with a single item than flatMap on it

File: sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java [hunk 2]
```diff
@@ -462,9 +465,25 @@ public List<VisitExportDto> getVisitsExportList(
...
+						.stream()
+						.collect(Collectors.toMap(UserReference::getId, Function.identity()));
 				for (VisitExportDto exportDto : resultList) {
 					boolean inJurisdiction = exportDto.getInJurisdiction();
 
+					UserReference user = visitUsers.get(exportDto.getVisitUserId());
+
+					exportDto.setVisitUserName(user.getName());
+					exportDto.setVisitUserRoles(
+						user.getUserRoles().stream().map(userRole -> UserRoleFacadeEjb.toReferenceDto(userRole)).collect(Collectors.toSet()));
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java:485]: `userRole -> UserRoleFacadeEjb.toReferenceDto(userRole) ` can be simplified to `UserRoleFacadeEjb::toReferenceDto `

**Review by leventegal-she — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java (hunk 1 above)
Comment (ChristopherRiedel) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java:471]: True

File: sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java (hunk 2 above)
Comment (ChristopherRiedel) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/visit/VisitFacadeEjb.java:485]: true

**Review by leventegal-she — APPROVED** [review]

**Review by leventegal-she — APPROVED** [review]
