### PR TITLE
#8895: Fixed sonaqube findings

### LINKED ISSUE #8895: [DEMIS2SORMAS] Create a dedicated menu for messages [3]
### Feature Description

Samples > Lab Messages / DEMIS interface
### Problem Description

Thus far, external messages in regards to case surveillance, especially in association with the DEMIS interface, have been managed in the lab messages directory. Recently, more message types have been introduced to DEMIS which requires users in SORMAS to not only receive and process lab messages but also other kinds of messages, e.g. physician reports.
In order to make the management of external messages more generic and clear, the lab messages directory should become its own menu item and serve as a general location to process any type of message that report cases to users.

### Proposed Change

- [x] Move the lab messages directory out of the sample menu and create a separate menu item called 'Messages'. Place this menu item in between Tasks and Persons. Use the notepad icon as seen elsewhere.
    - [x] Rename the directory title to 'Message Directory'
    - [x] Rename 'Fetch lab messages' to 'Fetch messages'
    - [x] Rename 'Lab name' to 'Reporter name' (included in search field placeholder)
    - [x] Rename 'Lab postal code' to 'Reporter postal code' (included in search field placeholder)
    - [x] Rename the pop-up header 'Lab message' to 'Message' (visible when viewing the message details)

- [x] Rename some further strings associated with general messages by replacing 'lab message(s)' with just 'message(s)' in the following contexts:
    - [x] labMessageLabMessagesList
    - [x] confirmationDeleteLabMessages
    - [x] confirmationUnclearLabMessage
    - [x] confirmationManuallyForwardedLabMessage
    - [x] confirmationFetchLabMessages
    - [x] confirmationSinceLabMessages
    - [x] headingLabMessageDownload
    - [x] headingNoLabMessagesSelected
    - [x] headingLabMessagesDeleteProcessed
    - [x] headingLabMessagesDeleted
    - [x] headingFetchLabMessages
    - [x] messageLabMessagesAssigned
    - [x] messageForwardedLabMessageFound
    - [x] messageNoLabMessagesSelected
    - [x] messageLabMessagesDeleteProcessed
    - [x] messageLabMessagesDeleted
    - [x] labMessageAlreadyProcessedError
    - [x] labMessagePdfConversionError

- [x] Rename the feature configurations `LAB_MESSAGES` to `EXTERNAL_MESSAGES` and adjust related descriptions
- [x] Change the `LAB_MESSAGES` user right to become generic MESSAGES rights
    - [x] Introduce the user right `EXTERNAL_MESSAGES_VIEW` - users with this right should be able to view the Messages directory, message details of the contained messages and download messages
    - [x] Introduce the user right `EXTERNAL_MESSAGE_PROCESS` - users with this right should be able to fetch messages, edit the assignee and status of a message as well as process them
    - [x] Introduce the user right `EXTERNAL_MESSAGE_DELETE` user right - users with this right should be able to delete messages
    - [x] Only users should be able to be set as assignees that also have the `EXTERNAL_MESSAGE_PROCESS`

### Additional Information

Message menu

Message Directory

### PR DESCRIPTION
**Pull request by ChristopherRiedel**
Fixes #8895

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageController.java [hunk 1]
```diff
@@ -266,14 +266,14 @@ private HorizontalLayout getExternalMessageButtonsPanel(ExternalMessageDto exter
...
+			e -> VaadinUiUtil.showConfirmationPopup(
 				I18nProperties.getString(Strings.headingConfirmManuallyForwardedLabMessage),
 				new Label(I18nProperties.getString(Strings.confirmationManuallyForwardedExternalMessage)),
 				I18nProperties.getString(Strings.yes),
 				I18nProperties.getString(Strings.no),
 				null,
-				(confirmed) -> {
-					if (confirmed) {
+				confirmed -> {
+					if (confirmed != null && confirmed) {
```
Comment (StefanKock) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/externalmessage/ExternalMessageController.java:276]: Better use `lang3.BooleanUtils.isTrue`

**Review by StefanKock — CHANGES_REQUESTED** [review]

**Review by StefanKock — APPROVED** [review]
