### PR TITLE
#4941 If no primary contact details, try to get a singular non-primary email and phone number

### LINKED ISSUE #4941: Symptom journals do not work without contact details marked as primary
### Bug Description
When trying to register persons for the symptom journals, single contact details per type are not enough for the registration. However, the attempt results in a generic error, so users don't know what went wrong and that they have to set the contact details to primary.
### Steps to Reproduce
1. Create a case or contact
2. Enter contacts details without setting them as primary
3. Try registering the person in Climedo and PIA

### Expected Behavior
The error message should be meaningful and inform the user that they need to define contact details as primary before registering persons in the symptom journals. 

Otherwise, if only one contact detail exists for the respective type, use this information as long as it belongs to the person without specifically having to check them as primary.
### Screenshots
piaError
climedoError

### System Details
* Device:
* SORMAS version: 1.58.0
* Android version/Browser: firefox, chrome
* Server URL: test1402.sormas-oegd.de (climedo), release-de.sormas.netzlink.com (PIA)
* User Role: admin, national user

### PR DESCRIPTION
**Pull request by Alexandru-Pirvu**
Closes #4941

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 1]
```diff
@@ -311,6 +304,38 @@ public JournalPersonDto getPersonForJournal(String uuid) {
...
+
+			if (configFacade.getPatientDiaryConfig().isActive()) {
+				PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
+				Phonenumber.PhoneNumber numberProto = phoneUtil.parse(phoneNumber, "DE");
+				return phoneUtil.format(numberProto, PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL);
+			} else {
+				return phoneNumber;
+			}
+		} catch (PersonDto.SeveralNonPrimaryContactDetailsException e) {
+			logger.error("Error retrieving phone number", e);
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:332]: I don't think we should log those as errors. It does refer to an invalid system state and will create further noise in the logs. The probleme here is rather something that should be displayed to the user.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 2]
```diff
@@ -311,6 +304,38 @@ public JournalPersonDto getPersonForJournal(String uuid) {
 			return null;
 		}
 	}
+	
+	private String getJournalEmailAddress(PersonDto person) {
+		try {
+			return person.getEmailAddress(false);
+		} catch (PersonDto.SeveralNonPrimaryContactDetailsException e) {
+			logger.error("Error retrieving email address", e);
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:312]: I don't think we should log those as errors. It does refer to an invalid system state and will create further noise in the logs. The probleme here is rather something that should be displayed to the user.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 3]
```diff
@@ -311,6 +304,38 @@ public JournalPersonDto getPersonForJournal(String uuid) {
...
+				Phonenumber.PhoneNumber numberProto = phoneUtil.parse(phoneNumber, "DE");
+				return phoneUtil.format(numberProto, PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL);
+			} else {
+				return phoneNumber;
+			}
+		} catch (PersonDto.SeveralNonPrimaryContactDetailsException e) {
+			logger.error("Error retrieving phone number", e);
+			return StringUtils.EMPTY;
+		} catch (NumberParseException e) {
+			logger.error("Error while trying to parse phone number as INTERNATIONAL", e);
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:335]: Why did you change the behaviour from 
`exportPerson.setPhone(detailedPerson.getPhone());` to logging an error message here?

**Review by FredrikSchaeferVitagroup — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 2 above)
Comment (FredrikSchaeferVitagroup) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:312]: For climedo,  this is done already:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/6aeae8e9ac554b09c5dee74920dc01024945d8be/sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java#L367

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 1 above)
Comment (FredrikSchaeferVitagroup) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:332]: For climedo,  this is done already:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/6aeae8e9ac554b09c5dee74920dc01024945d8be/sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java#L367

**Comment by FredrikSchaeferVitagroup** [comment]
Please fix failing tests (probably by merging latest development into this feature branch).

**Comment by FredrikSchaeferVitagroup** [comment]
Why do you divert from the pattern used for climedo that I proposed in my comments?
https://github.com/hzi-braunschweig/SORMAS-Project/blob/6aeae8e9ac554b09c5dee74920dc01024945d8be/sormas-backend/src/main/java/de/symeda/sormas/backend/externaljournal/ExternalJournalService.java#L367

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 4]
```diff
@@ -50,6 +50,8 @@
 
 import org.apache.commons.collections.CollectionUtils;
 import org.apache.commons.lang3.StringUtils;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:54]:
```suggestion

```

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 5]
```diff
@@ -128,6 +130,8 @@
 @Stateless(name = "PersonFacade")
 public class PersonFacadeEjb implements PersonFacade {
 
+	private final Logger logger = LoggerFactory.getLogger(getClass());
+
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:134]:
```suggestion

```

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 6]
```diff
@@ -284,11 +288,11 @@ public JournalPersonDto getPersonForJournal(String uuid) {
 		if (detailedPerson != null) {
 			JournalPersonDto exportPerson = new JournalPersonDto();
 			exportPerson.setUuid(detailedPerson.getUuid());
-			exportPerson.setEmailAddress(detailedPerson.getEmailAddress());
+			exportPerson.setEmailAddress(detailedPerson.getEmailAddress(false));
 			if (configFacade.getPatientDiaryConfig().isActive()) {
 				try {
 					PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
-					Phonenumber.PhoneNumber numberProto = phoneUtil.parse(detailedPerson.getPhone(), "DE");
+					Phonenumber.PhoneNumber numberProto = phoneUtil.parse(detailedPerson.getPhone(false), "DE");
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:295]: This one can now throw a SeveralNonPrimaryContactDetailsException as well, or? SORMAS should catch it here.

Comment (FredrikSchaeferVitagroup) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:295]: Also, when catching the NumberParseException a few linew below, and in the else { } below that, the SeveralNonPrimaryContactDetailsException can be thrown.

Comment (FredrikSchaeferVitagroup) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:295]: I case of a SeveralNonPrimaryContactDetailsException being thrown, null should be returned.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 7]
```diff
@@ -284,11 +288,11 @@ public JournalPersonDto getPersonForJournal(String uuid) {
 		if (detailedPerson != null) {
 			JournalPersonDto exportPerson = new JournalPersonDto();
 			exportPerson.setUuid(detailedPerson.getUuid());
-			exportPerson.setEmailAddress(detailedPerson.getEmailAddress());
+			exportPerson.setEmailAddress(detailedPerson.getEmailAddress(false));
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:291]: This one can no throw a SeveralNonPrimaryContactDetailsException, right? In that case, null should be returned here.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 8]
```diff
@@ -312,6 +316,16 @@ public JournalPersonDto getPersonForJournal(String uuid) {
 		}
 	}
 
+	public String getInternationalPhoneNumber(String phoneNumber) {
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:319]: Is this method used anywhere?

**Review by FredrikSchaeferVitagroup — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 8 above)
Comment (Alexandru-Pirvu) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:319]: No, I will remove it

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 7 above)
Comment (Alexandru-Pirvu) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:291]: It should not be the case, as all persons registered in journals should have the correct contact information.
Registering with multiple email addresses is not allowed.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 6 above)
Comment (Alexandru-Pirvu) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:295]: It should not be the case, as all persons registered in journals should have the correct contact information.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 7 above)
Comment (FredrikSchaeferVitagroup) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:291]: Yes, but that's a trap: For patient diaries it's different. And for patient diaries it can happen.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 8 above)
Comment (FredrikSchaeferVitagroup) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:329]: You did not remove it. If you want to keep it, please comment accordingly in this thread and explain why. 
I find the method misleading, because it does not always return an internationalized phone number. So I would suggest to either change the method behaviour, write a javadoc, or remove the method.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java [hunk 9]
```diff
@@ -312,6 +301,41 @@ public JournalPersonDto getPersonForJournal(String uuid) {
...
+
+	public String getJournalPhoneNumber(PersonDto person) {
+		try {
+			String phoneNumber = person.getPhone(false);
+			if (StringUtils.EMPTY.equals(phoneNumber)) {
+				return StringUtils.EMPTY;
+			}
+
+			if (configFacade.getPatientDiaryConfig().isActive()) {
+				return getInternationalPhoneNumber(phoneNumber);
```
Comment (FredrikSchaeferVitagroup) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java:320]: Just always try to return the international format.

**Review by FredrikSchaeferVitagroup — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java (hunk 6 above)
Comment (FredrikSchaeferVitagroup) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/person/PersonFacadeEjb.java]: It can be the case, but the new commits take this into account.

**Review by FredrikSchaeferVitagroup — APPROVED** [review]
