### PR TITLE
[#8815] rest failed login audit

### LINKED ISSUE #8790: We need a separate mechanism for failed logins, as this is handled before any backend or rest activity [2]
### Description
Failed logins and login activity in general cannot be handled easily as part of backend or REST logging, therefore, we need to provide a separate logger for it. 

### How to implement 

- [ ] Add method to `AuditLogger`
- [ ] Define log format
- [ ] Identify where to put the logger, likely the multi auth mechanism

Split into:
- [ ] #8815
- [ ] #8816

### LINKED ISSUE #8815: [Audit] log REST login fail
### Login failure for REST API

Split from #8790  as implementation is a little bit trickier than expected.

- [ ] Add method to `AuditLogger`
- [ ] Define log format
- [ ] audit placed in `MultiAuthenticationMechanism`

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #8815 
Fixes #8790
~~Do not merge yet, blocked on #8021 and #8816. Needs rebase and branch change.~~

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerEjb.java [hunk 1]
```diff
@@ -40,6 +40,7 @@
 import javax.ejb.Singleton;
 import javax.ejb.Stateless;
 
+import org.apache.commons.codec.binary.Base64;
```
Comment (JonasCir) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerEjb.java:43]: remove

Comment (JonasCir) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/audit/AuditLoggerEjb.java:43]: outdated

**Review by vidi42 — APPROVED** [review]
Tried it locally. LGTM
