### PR TITLE
#10793 Make JUnit4 available for testcontainers, avoid other usage

### LINKED ISSUE #10793: Update to JUnit5
### Problem Description
JUnit5 is out since 2017 and brings the following benefits:

* we get more granularity, and can import only what's necessary
* JUnit 5 allows multiple runners to work simultaneously
* JUnit5 allows Java8+ language features like lambda functions, making tests more powerful and easier to maintain.
* new features for describing, organizing, and executing tests. For instance, tests get better display names and can be organized hierarchically (e.g. https://medium.com/@boonkeat/android-unit-testing-with-junit5-d1b8f9c620b6)
* Allows combination of multiple extensions

Furthermore JUnit5 gives us more freedom of choice and comfort related to replacing our CDI unit testing framework.
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/10074#issuecomment-1294691128

### Proposed Change
Update to JUnit5. This means replacing imports and few clean ups.
The whole process should be done in one step.
Check whether Android app should be updated as-well or separately. -> Separately

### Implementation Details

- [x] org.unit.Test -> org.junit.jupiter.api.Test
- [x] org.junit.Assert.* -> org.junit.jupiter.api.Assertions.*
- [x] org.junit.Assert.assertThat -> org.hamcrest.MatcherAssert.assertThat
- [x] Before -> BeforeEach
- [x] BeforeClass -> BeforeAll
- [x] After -> AfterEach
- [x] ArchUnitRunner no longer needed
- [x] Test(expected=Exception) -> assertThrows
- [x] Some assertions currently have string message first -> is last param instead now
- [x] Use latest WireMock version for Junit5
- [x] CaseFacadeEjbTest: Extract wire mock related tests
- [x] TestContainers Junit5 extension + workaround: https://github.com/testcontainers/testcontainers-java/issues/970#issuecomment-625044008
- [x] Move tests for external surveillance functionality from CaseServiceTest and EventServiceTest into ExternalSurveillanceToolGatewayFacadeEjbTest
- [x] Remove sharing logic from testArchive... test in CaseFacadeEjbTest and EventFacadeEjbTest

### PR DESCRIPTION
**Pull request by StefanKock**
Fixes #10793

### CODE REVIEW

File: sormas-backend/src/test/java/de/symeda/sormas/backend/JUnitFrameworkTest.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+		"org.junit.runner.RunWith", };
+
+	/**
+	 * {@code org.testcontainers} still relies on JUnit4 ({@code junit:junit}), therefore the dependency is not excludeable.
+	 * This test checks that no (regular used) JUnit4 classes are used in tests.
+	 */
+	@ArchTest
+	public void testThatJUnit4IsNotUsed(JavaClasses classes) {
+
+		for (String junit4Classes : JUNIT4_CLASSES) {
```
Comment (BarnaBartha) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/JUnitFrameworkTest.java:30]: the variable should be named junit4Class

**Review by BarnaBartha — APPROVED** [review]
