### PR TITLE
fixed #6579

### LINKED ISSUE #6579: Additional tests cannot be deleted
### Bug Description

Trying to delete additional tests does not work properly.
### Steps to Reproduce

1. Create or open an additional test in any sample
2. Try deleting the additional test
3. Confirm the deletion

### Expected Behavior

The additional test should get deleted
### Screenshots

additionalTestDeleteBug

### System Details

* Device:
* SORMAS version: 1.63.0
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

### PR DESCRIPTION
**Pull request by ChristopherRiedel**
Fixes #6579

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AdditionalTestController.java [hunk 1]
```diff
@@ -57,9 +57,8 @@ public void onCommit() {
 
 	public void openEditComponent(AdditionalTestDto dto, Runnable callback) {
 
-		AdditionalTestDto newDto = FacadeProvider.getAdditionalTestFacade().getByUuid(dto.getUuid());
 		AdditionalTestForm form = new AdditionalTestForm(FacadeProvider.getSampleFacade().getSampleByUuid(dto.getSample().getUuid()), false);
-		form.setValue(newDto);
+		form.setValue(dto);
```
Comment (MartinWahnschaffe) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AdditionalTestController.java:61]: Why was this switched to dto instead of newDto?
Getting the latest version of the dto is what we are always doing when starting to edit an entry, so if there is a reason to do it differently here, we need to at least have a comment. In this case it would also not be necessary to do the getByUuid call, done above.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sample/AdditionalTestService.java [hunk 2]
```diff
@@ -141,4 +138,10 @@ public void delete(List<String> additionalTestUuids) {
 
 		em.createQuery(cd).executeUpdate();
 	}
+
+	@Override
+	public void delete(AdditionalTest deleteme) {
+		em.remove(em.contains(deleteme) ? deleteme : em.merge(deleteme));
```
Comment (MartinWahnschaffe) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/sample/AdditionalTestService.java:144]: It's super strange. I also did not manage to find out why deleteme is no longer attached.
Since we don't understand it, it could also happen for other entities, so I think we should move this code to the BaseAdoService and a comment there that the passed entity may be detached.

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AdditionalTestController.java (hunk 1 above)
Comment (BarnaBartha) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AdditionalTestController.java:61]: we were doing some testing if it affects the detached entity issues and forgot to revert it
will revert it now

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sample/AdditionalTestService.java (hunk 2 above)
Comment (BarnaBartha) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/sample/AdditionalTestService.java]: ok
