### PR TITLE
Bugfix 11017 fix person merging issue

### LINKED ISSUE #11017: Persons with incomplete home addresses from different jurisdictions can not be merged
### Problem Description

When using the person merge #5606 to try and merge persons that are from different jurisdictions (in their home address section) a warning appears if one of the persons has an incomplete home address.

A separate ticket has been created as in #5606 it was specified that information from the fields that are not filled in for the leading person should be filled with information from the discarded person. But it was not specified what should be done when the information is conflicting.

The scenario proposed considers 2 persons that are duplicates, one entry could be from a while ago when the person had an incomplete home address from jurisdiction 1, and the second entry for that person in their latest one, and has a complete home address from jurisdiction 2.

Steps:
1. Create a person that has the following home address:
image

2. Create a second person that would be considered a duplicate of the one from step1, but use the following home address:
image

3. Try to merge the 2 persons and have the person from step 1 as the leading person;
-> the merge is not possible, as the information from the community field from the discarded person can not be migrated into the leading person.
image

### Proposed Change

Two options for the proposed change:

1. Would it be desired for the whole home address to be updated for the leading person when the home address information is from different jurisdictions (different districts, and/or different communities)?

2. Would it be desired for the whole home address to be transferred into the leading person in the form of a 'New entry' in the 'Addresses' section of the leading person?

### PR DESCRIPTION
**Pull request by sergiupacurariu**
Fixes #11017

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java [hunk 1]
```diff
@@ -172,13 +172,26 @@ public boolean areDifferentLocation(LocationDto firstAddress, LocationDto second
...
+
 		if (firstAddress.getFacility() != null) {
 			Facility firstAddressFacilityDto = facilityService.getByUuid(firstAddress.getFacility().getUuid());
 			if (secondAddress.getCommunity() != null
 				&& firstAddressFacilityDto.getCommunity() != null
 				&& !firstAddressFacilityDto.getCommunity().getUuid().equals(secondAddress.getCommunity().getUuid())) {
 				return true;
 			}
+			if (secondAddress.getFacility() != null) {
+				if (!DataHelper.equal(firstAddress.getFacility(), secondAddress.getFacility())) {
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java:187]: You should use `DataHelper.isSame` for comparing facilities

File: sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java [hunk 2]
```diff
@@ -172,13 +172,26 @@ public boolean areDifferentLocation(LocationDto firstAddress, LocationDto second
...
 
+		if (Boolean.TRUE.equals(!DataHelper.equal(firstAddress.getFacilityType(), secondAddress.getFacilityType()))) {
+			return true;
+		}
+
 		if (firstAddress.getFacility() != null) {
 			Facility firstAddressFacilityDto = facilityService.getByUuid(firstAddress.getFacility().getUuid());
 			if (secondAddress.getCommunity() != null
 				&& firstAddressFacilityDto.getCommunity() != null
 				&& !firstAddressFacilityDto.getCommunity().getUuid().equals(secondAddress.getCommunity().getUuid())) {
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java:183]: please use `DataHelper.isSame(firstAddressFacilityDto.getCommunity(), secondAddress.getCommunity()) ` instead of comparing the uuids

File: sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java [hunk 3]
```diff
@@ -172,13 +172,26 @@ public boolean areDifferentLocation(LocationDto firstAddress, LocationDto second
 			return true;
 		}
 
+		if (Boolean.TRUE.equals(!DataHelper.equal(firstAddress.getFacilityType(), secondAddress.getFacilityType()))) {
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java:175]: `DataHelper.equal` is not nullable so there is no need to compare to `Boolean.TRUE`

**Review by leventegal-she — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java (hunk 1 above)
Comment (sergiupacurariu) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java:187]: changed

File: sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java (hunk 2 above)
Comment (sergiupacurariu) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java:183]: changed

File: sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java (hunk 3 above)
Comment (sergiupacurariu) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/location/LocationFacadeEjb.java:175]: changed

**Review by leventegal-she — APPROVED** [review]
