### PR TITLE
#6062 Fix NPEs when creating case as Hospital Informant

### LINKED ISSUE #6062: Hospital Informant: Create a case leads to an unexpected error
### Bug Description
If you try to create a new case with a hospital informant, an expected error occured. 

### Steps to Reproduce

1. Go to cases
2. Click on "new case" 

### Expected Behavior
No error occurs. 

### Screenshots
image

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
image

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
Fixes #6062

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java [hunk 1]
```diff
@@ -548,6 +554,10 @@ private void updateFacility() {
 		final DistrictReferenceDto district;
 		final CommunityReferenceDto community;
 
+		if (UserRole.getJurisdictionLevel(UserProvider.getCurrent().getUserRoles()) == JurisdictionLevel.HEALTH_FACILITY) {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java:557]: please move this if statement the fist line in in the method.

The field declarations belong to the if statement below, it's not a good idea to insert something not related between the declaration and value assignment.

**Review by leventegal-she — CHANGES_REQUESTED** [review]

**Review by leventegal-she — APPROVED** [review]
