### PR TITLE
Bugfix/bug 8671 contact and event participant export should contain relevant vaccine data

### LINKED ISSUE #8671: Contact and Event Participant detailed export contains data from last vaccine done even if is not a relevant vaccine
### Bug Description
When National user makes a detailed export for contacts and for events and at least one contact/event participant has 3 vaccinations, but only one is relevant but not last done, the export file contains data(Vaccine type, Info source, Inn, Unii code, batch number, Atc code, Date of first vaccine, Date of last vaccine) from the last vaccine done, which in this case is a vaccine not relevant

### Steps to Reproduce

1. System has reduced immunisation enable
2. Contact/Event participant has 2 vaccines not relevant and one vaccine relevant, all vaccines having all the fields completed(Vaccine type, Vaccine dose, Info source, Inn, Unii code, batch number, Atc code)
3. The not relevant vaccines are done after the contact/event was reported
4. The relevant vaccine was done before the case was reported
5. Export detailed report about contacts and events

### Expected Behavior
The exported file should contain vaccine data related to the last relevant Vaccine: Vaccine type,Vaccine dose,  Info source, Inn, Unii code, batch number, Atc code,
Date of first vaccine - should be taken from the first relevant vaccine done
Date of last vaccine - should be taken from the last relevant vaccine done
In case that are no relevant vaccines, then the fields will remain empty

### Actual Behavior
At this point the vaccine data(Vaccine type, Vaccine dose, Info source, Inn, Unii code, batch number, Atc code, Date of first vaccine, Date of last vaccine) of the not relevant vaccine is present in the report file. 

### System Details

* Device:
* SORMAS version: 1.71.0
* Android version/Browser:
* Server URL:
* User Role: Nat User

### PR DESCRIPTION
**Pull request by carina29**
Fixes #8671

### CODE REVIEW

File: sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java [hunk 1]
```diff
@@ -1750,4 +1866,27 @@ public void testGetContactUsersWithoutUsersLimitedToOthersDiseses() {
 		Assert.assertTrue(userReferenceDtos.contains(limitedCovidNationalUser));
 		Assert.assertFalse(userReferenceDtos.contains(limitedDengueNationalUser));
 	}
+
+	private CaseDataDto getCaze(UserDto user, PersonDto cazePerson, RDCFEntities rdcf) {
```
Comment (BarnaBartha) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java:1870]: this is a bit misleading, would be better to rename these methods to createCaze...

File: sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java [hunk 2]
```diff
@@ -233,4 +302,27 @@ public void testExistEventParticipantWithDeletedTrue(){
 		boolean exist = getEventParticipantFacade().exists(person.getUuid(), event.getUuid());
 		Assert.assertFalse(exist);
 	}
+
+	private UserDto getUser(TestDataCreator.RDCF rdcf) {
+		return creator
+			.createUser(rdcf.region.getUuid(), rdcf.district.getUuid(), rdcf.facility.getUuid(), "Surv", "Sup", UserRole.SURVEILLANCE_SUPERVISOR);
+	}
+
+	private EventDto getEvent(UserDto user, TestDataCreator.RDCF rdcf) {
```
Comment (BarnaBartha) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/event/EventParticipantFacadeEjbTest.java:311]: same here, would be better to rename to create

**Review by BarnaBartha — CHANGES_REQUESTED** [review]

**Review by BarnaBartha — APPROVED** [review]
