### PR TITLE
#7798 - Don't iterate over null lists

### LINKED ISSUE #7798: Initial synchronisation fails when areas are active but table is empty
### Bug Description

When initially syncing infrastructure data on a system that has the `INFRASTRUCTURE_TYPE_AREA` feature enabled, but no areas in the database, the synchronisation fails:

```
01-27 14:20:57.309 15087 22933 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
01-27 14:20:57.309 15087 22933 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: 	at de.symeda.sormas.app.backend.common.AdoDtoHelper.lambda$handlePulledList$0(AdoDtoHelper.java:183)
01-27 14:20:57.309 15087 22933 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: 	at de.symeda.sormas.app.backend.common.AdoDtoHelper.$r8$lambda$hCzJ3sszF_oP3vgBtfucOv2jnwg(Unknown Source:0)
01-27 14:20:57.309 15087 22933 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: 	at de.symeda.sormas.app.backend.common.AdoDtoHelper$$ExternalSyntheticLambda0.call(Unknown Source:6)
01-27 14:20:57.309 15087 22933 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: 	at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:237)
01-27 14:20:57.309 15087 22933 E de.symeda.sormas.app.rest.SynchronizeDataAsync$1: 	... 15 more
```

### Steps to Reproduce

1. Set up a server with the feature configuration enabled, but don't create any area in the database
2. Install the mobile app and log in with a user to trigger the initial synchronization.

### Expected Behavior

The Android app should be able to handle empty or null lists here; check whether this problem might also appear for other infrastructure data (e.g. regions, districts, etc.) and if so, fix it there as well.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #7798

### CODE REVIEW

File: sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/AdoDtoHelper.java [hunk 1]
```diff
@@ -177,6 +177,11 @@ protected int handlePullResponse(final boolean markAsRead, final AbstractAdoDao<
 
 	public int handlePulledList(AbstractAdoDao<ADO> dao, List<DTO> result)
 		throws DaoException, NoConnectionException, ServerConnectionException, ServerCommunicationException {
+
+		if (result == null) {
```
Comment (MartinWahnschaffe) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/AdoDtoHelper.java:181]: Let's add a comment to the method that mentions that it returns the number handled results.

**Comment by MartinWahnschaffe** [comment]
Please add the comment. Besides that it's approved.
