### PR TITLE
#7608 - Properly set user rights in task edit form

### LINKED ISSUE #7608: Edit and create rights not initialised in task edit form
### Bug Description

The edit and create rights are not properly initialised in the task edit form.

### Steps to Reproduce

1.
2.

### Expected Behavior

The variable should be set to TASK_CREATE or TASK_EDIT, depending on whether `create` is true or not.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by alexcaruntu-vita**
Fixes #7608

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java [hunk 1]
```diff
@@ -331,7 +338,8 @@ private void updateByCreatingAndAssignee() {
 				discard(TaskDto.ASSIGNEE_REPLY, TaskDto.TASK_STATUS);
 			}
 
-			if (UserProvider.getCurrent().hasUserRight(editOrCreateUserRight)) {
+			UserProvider currentUser = UserProvider.getCurrent();
+			if (currentUser.hasUserRight(UserRight.TASK_CREATE) || currentUser.hasUserRight(UserRight.TASK_EDIT)) {
```
Comment (MateStrysewske) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java:342]: Please use the user right in compliance with the `create` field, i.e. if we're in a create form, use TASK_CREATE, otherwise use TASK_EDIT

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Review by MateStrysewske — APPROVED** [review]
