### PR TITLE
#5816 rework pathogentest/sample result updates 

### LINKED ISSUE #5816: Unify pathogen test saving logic between cases, contacts and event participants [1]
### Bug Description

Process a positive pathogen tests on contacts does not trigger the question of whether the entire sample is updated to positive.
### Steps to Reproduce

1. Proceess a positive pathogen test via LBDS with creating a contact
2. Save the positive pathogen test
3. The sample result stays pending and updating window does not appear.

### Expected Behavior

With cases it works fine, that the systems ask whether you want to update the sample to positive as well or not.
### Screenshots

bug Probe Ausstehend

### System Details

* Device:
* SORMAS version: 1.60/1.61 (test-de1)
* Android version/Browser:
* Server URL:
* User Role: admin, National User

### Developer Specifications

The implementation follows the rules of [this comment](https://github.com/hzi-braunschweig/SORMAS-Project/issues/5816#issuecomment-909094352)

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
Closes #5816

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 1]
```diff
@@ -161,120 +162,238 @@ public static void showCaseUpdateWithNewDiseaseVariantDialog(CaseDataDto existin
...
+		// a) Tested disease == case disease AND test result != sample pathogen test result: Ask user whether to update the sample pathogen test result
+		// b) Tested disease != case disease: Do nothing
+
+		// Positive test result AND test result verified
+		// a) Tested disease == case disease: Ask user whether to update the sample pathogen test result
+		// a.1) Tested disease variant != case disease variant: Ask user to change the case disease variant
+		// a.2) Case classification != confirmed: Ask user whether to confirm the case
+		// b) Tested disease != case disease: Ask user to create a new case for the tested disease
+
 		CaseDataDto preSaveCaseDto = FacadeProvider.getCaseFacade().getCaseDataByUuid(associatedCase.getUuid());
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:204]: This does not make sense. `preSaveCaseDto` is used here to be compared against `postSaveCaseDto` to determine which notification to show.
However, there is no chance of `preSaveCaseDto` being different from (or more specifically: "having a different classification than", see `showSaveNotification`) `postSaveCaseDto`, since both are freshly retrieved from the database.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 2]
```diff
@@ -161,120 +162,238 @@ public static void showCaseUpdateWithNewDiseaseVariantDialog(CaseDataDto existin
...
+				sample.setPathogenTestResult(pathogenTest.getTestResult());
+				FacadeProvider.getSampleFacade().saveSample(sample);
+			}
+		} else {
+			changeAssociatedSampleResult(pathogenTest, handleChanges -> {
+			});
+		}
+	}
+
+	private void changeAssociatedSampleResult(PathogenTestDto dto, Consumer<Boolean> callback) {
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:380]: To clarify the intention, rename to `showChangeAssociatedSampleResultDialog`.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 3]
```diff
@@ -161,120 +162,238 @@ public static void showCaseUpdateWithNewDiseaseVariantDialog(CaseDataDto existin
...
+				} else {
 					showCreateContactCaseDialog(contact, dto.getTestedDisease());
 				}
 			}
 		};
+
 		if (onSavedPathogenTest != null) {
-			onSavedPathogenTest.accept(dto, contactConvertToCaseCallback);
+			onSavedPathogenTest.accept(dto, () -> {
+				positiveTestCallback.run();
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:297]: Technically, there is no need to provide two separate callbacks here for positive and negative test results.
However, it is okay if it is supposed to be more readable like this.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 4]
```diff
@@ -161,120 +162,238 @@ public static void showCaseUpdateWithNewDiseaseVariantDialog(CaseDataDto existin
...
+				}
 			}
 		};
 
 		if (onSavedPathogenTest != null) {
 			onSavedPathogenTest.accept(dto, () -> {
-				confirmCaseCallback.run();
-				caseCloningCallback.run();
-				caseDiseaseVariantCallback.run();
+				positiveTestCallback.run();
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:244]: Technically, there is no need to provide two separate callbacks here for positive and negative test results.
However, it is okay if it is supposed to be more readable like this.

**Review by syntakker — CHANGES_REQUESTED** [review]
See comments.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 5]
```diff
@@ -201,52 +203,43 @@ private void handleAssociatedCase(
...
+		Runnable callback = () -> {
 			if (equalDisease && PathogenTestResultType.NEGATIVE.equals(dto.getTestResult()) && dto.getTestResultVerified()) {
-				changeAssociatedSampleResult(dto, handleChanges -> {
+				showChangeAssociatedSampleResultDialog(dto, handleChanges -> {
 				});
 			}
-		};
 
-		Runnable positiveTestCallback = () -> {
 			if (PathogenTestResultType.POSITIVE.equals(dto.getTestResult()) && dto.getTestResultVerified()) {
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:216]: Only minor, but for better readability (complexity makes this code hard to read anyways): `else if`

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 6]
```diff
@@ -268,22 +261,20 @@ private void handleAssociatedContact(
...
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:270]: `else if` (as above)

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java [hunk 7]
```diff
@@ -325,22 +312,20 @@ private void handleAssociatedEventParticipant(
...
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestController.java:321]: `else if` (as above)

**Review by syntakker — CHANGES_REQUESTED** [review]

**Review by syntakker — APPROVED** [review]
