### PR TITLE
bug/10528_error_message_dashboard

### LINKED ISSUE #10528: Contact Dashboard runs into parameter limit with many contacts
### Bug Description

When and Admin+NatUser or a Contact Supervisor(with the jurisdiction in 'Voreingestellte Bundesländer') filter contacts on the dashboard based on 'Custom' - 'By date', an error message is displayed.

The issue could not be reproduced on my local machine, or on test-de.sormas.netzlink.com, with any of the 2 users; could only reproduce it on test-autom.sormas.netzlink.com.

### Steps to Reproduce

1. Log into the app with an Admin+NatUser, or a Contact Supervisor (with the jurisdiction in 'Voreingestellte Bundesländer');
2. Navigate to the 'Dashboard' directory;
3. In the first Epi week related filter, select 'Custom'; for 'Custom persion' select 'By date'; in the 'From' field select the 1st of September 2021;
4. Click 'Apply Custom Filter' then 'Apply filters'.

### Actual Behavior

An error message is displayed:
image

### Expected Behavior

No error message should be displayed.

### Screenshots

GIF of the behavior and the steps to reproduce:
Custom error

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0SNAPSHOT(5111f71)
* Android version/Browser: Chrome
* Server URL: https://test-auto.sormas.netzlink.com/
* User Role: Admin+NatUser; Contact Supervisor (with the jurisdiction in 'Voreingestellte Bundesländer')

### Additional Information

Observed while testing for #10381. 

Could not provide server logs as I do not have access to them for this specific testing instance.
---> I put the error log here
[logs.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9771804/logs.txt)

### PR DESCRIPTION
**Pull request by dinua**
Fixes #10528.

@StefanKock I converted it to a draft to create awareness that this PR should be squash merged.

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java [hunk 1]
```diff
@@ -1315,6 +1308,31 @@ public int[] getContactCountsByCasesForDashboard(List<Long> contactIds) {
 		}
 	}
 
+	private List<Long> getCaseIdsFromContacts(List<Long> contactIds) {
+		CriteriaBuilder cb = em.getCriteriaBuilder();
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java:1312]: Please leave empty line here after method declaration

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java [hunk 2]
```diff
@@ -1315,6 +1308,31 @@ public int[] getContactCountsByCasesForDashboard(List<Long> contactIds) {
...
+
+		cq.where(contact.get(Contact.ID).in(contactIds));
+		cq.select(caseJoin.get(Case.ID));
+		cq.distinct(true);
+
+		return em.createQuery(cq).getResultList();
+	}
+
+	private List<Long> countContactsAssignToCases(List<Long> caseIds) {
+		CriteriaBuilder cb = em.getCriteriaBuilder();
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java:1325]: Please leave empty line here after method declaration

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java [hunk 3]
```diff
@@ -1283,29 +1283,22 @@ public List<ContactIndexDetailedDto> getIndexDetailedList(
...
-		CriteriaQuery<Long> cq = cb.createQuery(Long.class);
-		Root<Contact> contact = cq.from(Contact.class);
-		Join<Contact, Case> caseJoin = contact.join(Contact.CAZE);
-
-		cq.where(contact.get(Contact.ID).in(contactIds));
-		cq.select(caseJoin.get(Case.ID));
-		cq.distinct(true);
-
-		List<Long> caseIds = em.createQuery(cq).getResultList();
+		List<Long> caseIds = new ArrayList<>();
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java:1286]: Better use a `Set` for caseIds because they can duplicate between batches

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java [hunk 4]
```diff
@@ -681,6 +671,25 @@ public List<DashboardContactDto> getContactsForDashboard(Region region, District
 		return Collections.emptyList();
 	}
 
+	private List<DashboardVisit> getContactDashboardVisits(List<Long> dashboardContactIds, Root<Contact> contact) {
+		CriteriaBuilder cb = em.getCriteriaBuilder();
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java:675]: Please leave empty line here after method declaration

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java [hunk 5]
```diff
@@ -681,6 +671,25 @@ public List<DashboardContactDto> getContactsForDashboard(Region region, District
...
+		CriteriaQuery<DashboardVisit> visitsCq = cb.createQuery(DashboardVisit.class);
+		Root<Contact> visitsCqRoot = visitsCq.from(getElementClass());
+		Join<Contact, Visit> visitsJoin = visitsCqRoot.join(Contact.VISITS, JoinType.LEFT);
+		Join<Visit, Symptoms> visitSymptomsJoin = visitsJoin.join(Visit.SYMPTOMS, JoinType.LEFT);
+
+		visitsCq.where(
+			CriteriaBuilderHelper
+				.and(cb, contact.get(AbstractDomainObject.ID).in(dashboardContactIds), cb.isNotEmpty(visitsCqRoot.get(Contact.VISITS))));
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java:683]: Change `AbstractDomainObject.ID` to `Contact.ID`

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java [hunk 6]
```diff
@@ -681,6 +671,25 @@ public List<DashboardContactDto> getContactsForDashboard(Region region, District
...
+		visitsCq.multiselect(
+			visitsCqRoot.get(AbstractDomainObject.ID),
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java:685]: Change `AbstractDomainObject.ID` to `Visit.ID`

File: sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java [hunk 7]
```diff
@@ -980,6 +981,17 @@ public void testGetContactCountsByCasesForDashboard() {
 		assertThat(result[2], equalTo(1));
 	}
 
+	@Test
+	public void testGetContactCountsByCasesForDashboardWithHugeList() {
+
```
Comment (StefanKock) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java:986]: Please amend the existing unit test for that method. A new test also puts several seconds of additional execution time that can be avoided.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java [hunk 8]
```diff
@@ -634,22 +635,11 @@ public List<DashboardContactDto> getContactsForDashboard(Region region, District
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java:635]: Could you please add a small unit test for ContactService.getContactsForDashboard with zero data and with one contact and visit to check that the queries are working?

**Review by StefanKock — CHANGES_REQUESTED** [review]
Several findings commented: Nothing wrong, but some code formatting and amendments

**Review by StefanKock — CHANGES_REQUESTED** [review]
I documented some findings and rewrote the code myself to speed it up

**Review by StefanKock — APPROVED** [review]

**Comment by StefanKock** [comment]
@dinua pls review my changes
