### PR TITLE
Bug/10113 automatic deletion event participant error

### LINKED ISSUE #10113: ERROR: update or delete on table "eventparticipant" violates foreign key constraint "fk_samples_associatedeventparticipant_id" on table "samples"
### Bug Description

Error displayed and the deletion job is not successful as 'update or delete on table "eventparticipant" violates foreign key constraint "fk_samples_associatedeventparticipant_id" on table "samples"'.

### Steps to Reproduce

1. Create an event participant for an event that has the disease Covid-19;
2. Add to the event participant a sample for Covid-19 (with a positive test result) and create a resulting Covid-19 case;
3. In the DB - update the 'creationdate' of the event participant (to fit within the deletion period).
4. Wait for the deletion job to run.
 
### Actual Behavior

Deletion job is not successful. Error is displayed:
image

### Expected Behavior

Deletion job should be successful.

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(d312652)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser
 
### Additional Information

Logs from the local machine:
[event participant.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/9309360/event.participant.txt)

#7930 - observed while testing; created a separate ticket as #7930 is from Sprint 118.

### PR DESCRIPTION
**Pull request by dinua**
Fixes #10113

### CODE REVIEW

File: sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java [hunk 1]
```diff
@@ -274,6 +276,88 @@ public void testEventAutomaticDeletion() {
 		assertEquals(0, getEventParticipantService().count());
 	}
 
+	@Test
+	public void testEventParticipantWithEvnSampleAutomaticDeletion() {
```
Comment (MateStrysewske) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java:280]:
```suggestion
	public void testEventParticipantWithEventSampleAutomaticDeletion() {
```

Comment (MateStrysewske) [reply sormas-backend/src/test/java/de/symeda/sormas/backend/deletionconfiguration/CoreEntityDeletionServiceTest.java:280]: I guess that's what you meant?

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
