### PR TITLE
fixed #8013

### LINKED ISSUE #8013: [Lab messages] Using the 'Person search' option when creating new entities, via processing lab messages, creates a new person
### Bug Description

When processing lab messages to create new entities (cases and contacts), if the user uses the 'Person Search' option, the newly created entity is not associated with the selected person, but instead a new person gets created.

### Steps to Reproduce

1. Create a person by creating a new entity (i.e. 'person1');
2. Navigate to 'Lab messages' in the 'Samples' directory and click 'Process' on an unprocessed lab message;
3. In the first pop-up for 'Pick or create person' select 'Create new person' and click 'Confirm';
4. In the second pop-up for 'Pick or create entry' select 'Create new case' or 'Create new contact';
5. In the 'Create new case/contact' form, for the person related fields, use the 'Person search' option to select the person created at step1 ('person1');
6. Save the new entity (case or contact);
7. Navigate to the 'Persons' directory and observe the entities.

### Actual Behavior

There are 2 persons with the details of 'person1', but one of them is associated with the entity created at step1 and one of them is associated with the entity created at step6.

### Expected Behavior

There is 1 person with the details of 'person1' and it has 2 entities associated: the entity created at step1 and the entity created at step6.

### Screenshots

image

image

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

Note 1: When processing a lab message and choosing to create a new event participant, the behavior described in the ticket does not reproduce.

Note 2: This issue might be related to ticket #8012

### PR DESCRIPTION
**Pull request by ChristopherRiedel**
Fixes #8013

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java [hunk 1]
```diff
@@ -310,7 +312,10 @@ private void pickOrCreatePerson(LabMessageDto labMessage) {
 
 					pickOrCreateEntry(labMessage, similarCases, similarContacts, similarEventParticipants, selectedPersonDto);
 				}
-			}, false);
+			},
+				false,
+				personSearchActive,
+				personSearchActive ? I18nProperties.getString(Strings.infoSelectOrCreatePersonForLabMessageWithoutMatches) : null);
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java:318]: The call of the method ControllerProvider.getPersonController().selectOrCreatePerson(...) is 38 lines long now.
This is hardly readable. Maybe define the resultConsumer before the method call, and split into several parts with meaningful names.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java [hunk 2]
```diff
@@ -80,13 +80,23 @@ public TitleLayout getPersonViewTitleLayout(PersonDto personDto) {
...
 	public void selectOrCreatePerson(final PersonDto person, String infoText, Consumer<PersonReferenceDto> resultConsumer, boolean saveNewPerson) {
+		selectOrCreatePerson(person, infoText, resultConsumer, saveNewPerson, false, null);
+	}
+
+	public void selectOrCreatePerson(
+		final PersonDto person,
+		String infoText,
+		Consumer<PersonReferenceDto> resultConsumer,
+		boolean saveNewPerson,
+		boolean showWithoutMatches,
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java:91]: It seems to me that this boolean is not necessary. It can be determined via `StringUtils.isEmpty(infoTextWithoutMatches)`.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java [hunk 3]
```diff
@@ -80,13 +80,23 @@ public TitleLayout getPersonViewTitleLayout(PersonDto personDto) {
...
+		String infoTextWithoutMatches) {
 		// This builds a selection field for all potential similar persons if any.
 		// The user can choose to merge or create a new person in case there is a similar person in the system.
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java:94]: These comments (as well as the ones further below) seem to be outdated and don't match the method logic. 
With this large amount of parameters, a Javadoc comment explaining the logic would be appropriate.

Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java:94]: These comments (as well as the ones further below) seem to be outdated and don't match the method logic. 
With this large amount of parameters, a Javadoc comment explaining the logic would be appropriate.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java [hunk 4]
```diff
@@ -56,6 +56,11 @@
 	private RadioButtonGroup<String> rbCreatePerson;
 	protected PersonSelectionFilterForm filterForm;
 	private PersonDto referencePerson;
+	private boolean hasMatches;
+
+	public PersonSelectionField(PersonDto referencePerson, String infoText) {
+		this(referencePerson, infoText, null);
+	}
 
 	/**
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java:65]: Outdated Javadoc

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java [hunk 5]
```diff
@@ -65,11 +70,17 @@
...
-		this.infoText = infoText;
 
 		initializeGrid();
+
+		this.hasMatches = this.hasMatches();
+		if (infoTextWithoutMatches == null) {
+			this.infoText = infoText;
+		} else {
+			this.infoText = hasMatches ? infoText : infoTextWithoutMatches;
+		}
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java:83]: I find the logic quite disadvantegous:
1. It invokes `this.hasMatches()` in scenarios where it was not called before the change and calling it probably still is not necessary. That is bad because it's an expensive call. One could circumvent this like that:

```suggestion
		if (infoTextWithoutMatches == null) {
			this.infoText = infoText;
		} else {
			this.infoText = this.hasMatches() ? infoText : infoTextWithoutMatches;
		}
```

2. The personSelectionField is mostly managed from outside (e.g. whether the field is shown or not is decided outside of this class). This logic makes a decision inside the class now.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java [hunk 6]
```diff
@@ -80,13 +80,23 @@ public TitleLayout getPersonViewTitleLayout(PersonDto personDto) {
...
-		PersonSelectionField personSelect = new PersonSelectionField(person, infoText);
+		PersonSelectionField personSelect = new PersonSelectionField(person, infoText, infoTextWithoutMatches);
 		personSelect.setWidth(1024, Unit.PIXELS);
 
 		// check if we have duplicate persons for the given PersonDto
-		if (personSelect.hasMatches()) {
+		if (personSelect.hasMatches() || showWithoutMatches) {
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java:99]: `personSelect.hasMatches()` is an expensive call. 
```suggestion
		if (showWithoutMatches || personSelect.hasMatches()) {
```

**Review by FredrikSchaeferVitagroup — CHANGES_REQUESTED** [review]

File: sormas-api/src/main/resources/strings.properties [hunk 7]
```diff
@@ -829,6 +829,7 @@ infoSelectOrCreatePersonForImmunization = The database already contains at least
...
 infoSelectOrCreatePersonForLabMessage = The database already contains at least one person that seems to be very similar to the personal details of the lab message.<br/><br/>Please look through the list of persons. If you feel certain that one of those persons matches the lab message person, select it and click on the <i>Confirm</i> button. Otherwise, click on <i>Create New Person</i> to create a new person for the lab message.<br/><br/>If you are unsure, you can discard this window and cancel the process.
+infoSelectOrCreatePersonForLabMessageWithoutMatches = The database contains no person that seems to be very similar to the personal details of the lab message.<br/><br/>If you feel certain that the lab message person is already in the database, please search for it and if you find the matching person, select it and click on the <i>Confirm</i> button. Otherwise, click on <i>Create New Person</i> to create a new person for the lab message.<br/><br/>If you are unsure, you can discard this window and cancel the process.
```
[the remark this answers is not in the document]
Comment (ChristopherRiedel) [reply sormas-api/src/main/resources/strings.properties:832]: But this message only comes when there are no matches. And the window appears when there are no matches only when the feature is active.

[the remark this answers is not in the document]
Comment (FredrikSchaeferVitagroup) [reply sormas-api/src/main/resources/strings.properties:832]: Ah, okay. I missed that. The bulkiness remains.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java (hunk 2 above)
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java:91]: makes sense

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java (hunk 3 above)
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonController.java:94]: makes sense

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java [hunk 8]
```diff
@@ -127,14 +127,15 @@
...
+	private final boolean showPersonSearchButton;
 
 	// If a case is created form a TravelEntry, the variable convertedTravelEntry provides the
 	// necessary extra data. This variable is expected to be replaced in the implementation of
 	// issue #5910.
 	private final TravelEntryDto convertedTravelEntry;
 
 	//@formatter:off
-    private static final String HTML_LAYOUT = fluidRowLocs(CaseDataDto.CASE_ORIGIN, "")
+    private static final String HTML_LAYOUT_PART_1 = fluidRowLocs(CaseDataDto.CASE_ORIGIN, "")
```
[the remark this answers is not in the document]
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java:138]: I don't want to claim that my approach can't be improved, but I find this suggestion much more confusing than the current situation.

[the remark this answers is not in the document]
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java:138]: See discussion about CaseCreateForm

File: sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java [hunk 9]
```diff
@@ -77,31 +77,35 @@
...
-	private static final String HTML_LAYOUT =
-			LayoutUtil.loc(PERSON_NAME_LOC) +
-			LayoutUtil.fluidRowLocs(6, PersonDto.FIRST_NAME, 4, PersonDto.LAST_NAME, 2, PERSON_SEARCH_LOC) +
+	private static final String HTML_LAYOUT_PART_1 =
+			LayoutUtil.loc(PERSON_NAME_LOC);
+	private static final String HTML_LAYOUT_PART_2_WITH_PERSON_SEARCH =
+			fluidRowLocs(6, PersonDto.FIRST_NAME, 4, PersonDto.LAST_NAME, 2, PERSON_SEARCH_LOC);
+	private static final String HTML_LAYOUT_PART_2_WITHOUT_PERSON_SEARCH =
+			fluidRowLocs(PersonDto.FIRST_NAME, PersonDto.LAST_NAME);
+	private static final String HTML_LAYOUT_PART_3 =
```
[the remark this answers is not in the document]
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactCreateForm.java:86]: See discussion about CaseCreateForm

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (FredrikSchaeferVitagroup) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java:138]: Well, I find it clearer. The names give information about the usage (COMMON is always used, the other ones are not) and the content (SNIPPET is a small part). Should we maybe discuss it in a call?

File: sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java (hunk 1 above)
Comment (FredrikSchaeferVitagroup) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java]: I don't see any related changes in the last commit.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java [hunk 10]
```diff
@@ -56,6 +56,11 @@
 	private RadioButtonGroup<String> rbCreatePerson;
 	protected PersonSelectionFilterForm filterForm;
 	private PersonDto referencePerson;
+	private boolean hasMatches;
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonSelectionField.java:59]: This variable is never assigned.

**Review by FredrikSchaeferVitagroup — CHANGES_REQUESTED** [review]

**Review by FredrikSchaeferVitagroup — APPROVED** [review]
