### PR TITLE
#11509 users without edit but with delete role should have delete button enabled

### LINKED ISSUE #11509: Enable the 'Delete' button for users that have deletion rights but no edit rights over entities [5]
### Problem Description
Have a User role configured like this:
Screenshot 2023-02-15 at 10 11 36
 The user having the role above cannot delete user roles because it has disable the delete button

As discussed with @carina29 and @MartinWahnschaffe the current ticket has been converted from bug report to change request. There is a use case for the change requested, from a data security point of view - a user might be created that is only tasked with deleting data from SORMAS, and no edit rights over the respective data.

#### Steps to Reproduce

1. Login with the user explained in the Bug description section
2. Go to User Role tab
3. Choose a Role from he list
4. Edit the role
5. Check the delete button

### Actual Behavior
The delete button is disable

### Expected Behavior
The delete buttons should be **enabled** to be able to delete the entity for which the user has delete rights, but no edit rights. (View rights over the entity are a prerequisite).

### Additional Information
The same happens also for other entities. This scenario will be extended also to the rest of the entities, to support the deletion action without having the right to edit.

Entities that should support delete right without edit right:

- [x] Users
- [x]  Case
- [x]  Contact
- [x] Task
- [x] Event - Added by @carina29 - https://github.com/hzi-braunschweig/SORMAS-Project/issues/8868 should be retested by QA Team too because of the change on EditDataView component
- [x] Event Participant
- [x] Event Groups (added by @adinaflorea9 and @carina29)
- [x] Event Actions (added by @adinaflorea9  and @carina29  )
- [x] Samples
- [x] Additional Test  (added by @adinaflorea9 and @carina29)
- [x] Immunization - Added by @carina29 :  https://github.com/hzi-braunschweig/SORMAS-Project/issues/6639 should be rechecked since here was added that without IMMUNIZATION_EDIT right the returned EditPermissitonType will be REFUSED.
- [x] Vaccination (Added by @carina29 ) - Till now if the IMMUNIZATION_EDIT right was missing, the buttons ( discard, save, edit) did not appear at all. It was agreed with @MateStrysewske to display/enable/disable the buttons in the same way as we have for Additional Tests.
- [x] Entries
- [x] Campaigns (added by @adinaflorea9 and @carina29)
- [x] Campaign Form Data  (added by @adinaflorea9 and @carina29) - (Added by @carina29 ) There was no editAllowed flag on Campaign Form Data component. It was added the isEditAllowed flag as we have it in case of other entities ( when the user has edit right will be able to edit the component)

**Note:** In this ticket the changes related to mSERS (Aggregated Reports), Messages and Child Entities (Prescription, Follow-up, Treatment, Clinical course, Pathogen test ) and the changes related to the mobile app will not be handled.

**Note**: If the entity was deleted, instead of the Delete button the Undo Deletion will remain enabled.

Take into account that when deleting an entity, the user should also have the correct jurisdiction. The validation should be done on BE and FE.

### PR DESCRIPTION
**Pull request by carina29**
Fixes #11509

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java [hunk 1]
```diff
@@ -979,6 +984,31 @@ public void setDirty(boolean dirty) {
...
+			}
+		}
+	}
+
+	public boolean isDeleteAllowed(UserRight deleteRight) {
+		return UserProvider.getCurrent().hasUserRight(deleteRight);
+	}
+
+	public boolean isEditAllowed(UserRight editRight, EditPermissionType editPermissionType) {
+		if (editPermissionType != null) {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CommitDiscardWrapperComponent.java:1005]: this can be simplified to 
```
UserProvider.getCurrent().hasUserRight(editRight) && (editPermissionType == null || editPermissionType == EditPermissionType.ALLOWED)
```

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleDataView.java [hunk 2]
```diff
@@ -156,7 +156,8 @@ protected void initView(String params) {
 		final boolean deleted = FacadeProvider.getSampleFacade().isDeleted(uuid);
 
 		if (deleted) {
-			editComponent.setEditable(false, CommitDiscardWrapperComponent.DELETE_UNDELETE);
+			editComponent.addButtonToExcludedList(CommitDiscardWrapperComponent.DELETE_UNDELETE);
+			editComponent.setEditable(false, editComponent.getExcludedButtons().stream().toArray(String[]::new));
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleDataView.java:160]: would be better to have a method in CommitDiscard component tthat disablesIt with the excluded buttons so there would be no need to expose `getExcludedButtons` and here you just would call something like `editComponent.setNonEditable()`

File: sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationDataView.java [hunk 3]
```diff
@@ -72,9 +72,11 @@ protected void initView(String params) {
 		final boolean deleted = FacadeProvider.getImmunizationFacade().isDeleted(uuid);
 
 		if (deleted) {
-			layout.disable(CommitDiscardWrapperComponent.DELETE_UNDELETE);
+			editComponent.addButtonToExcludedList(CommitDiscardWrapperComponent.DELETE_UNDELETE);
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/ImmunizationDataView.java:75]: would be better to introduce a method in LayoutWithSidePanel that handles all this if/elseif-s so it would not be duplicated in all View classes

**Review by leventegal-she — CHANGES_REQUESTED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545

**Review by leventegal-she — APPROVED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11545
