### PR TITLE
[#10110] call validate for events and move unecessary checks to DTO

### LINKED ISSUE #10110: The missing reporting user validation is not triggered for creating Event
### Bug Description
The missing reporting user validation is not triggered for creating Event

### Steps to Reproduce
1. Make a POST for the endpoint to created event( env_url/sormas-rest/events/push)
2. In the body of the request don't add the attribute : reporting user 
[
    {
        "eventTitle": "JustFromAPI",
        "eventLocation": {
            "uuid": "e8ed5a4e-c5af-4ef9-ac6f-3004f2c4eba8",
            "pseudonymized": false,
            "region": {
                "uuid": "XD5CCG-2K2NRA-E7VK75-ME622CX4",
                "caption": "First Region"
            }
        },
        "eventStatus": "EVENT",
        "eventInvestigationStatus": "PENDING",
        "reportDateTime": 1653385889240
    }
]

### Actual Behavior

The request responds with the status code 200 and response body
[
    "TRANSACTION_ROLLED_BACK_EXCEPTION"
]
### Expected Behavior

The request should responds with the status code 400 and response body
"Invalid data",
    "errors": {
        "reportingUser": "You have to specify a valid user from the SORMAS database"
    }

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #10110

### CODE REVIEW

**Comment by JonasCir** [comment]
HTTP status code is still 200 in case of error...

File: sormas-api/src/main/java/de/symeda/sormas/api/event/EventDto.java [hunk 1]
```diff
@@ -120,11 +122,11 @@ public class EventDto extends SormasToSormasShareableDto {
 	public static final String OTHER_DELETION_REASON = "otherDeletionReason";
 
 	private EventReferenceDto superordinateEvent;
-
-	@Required
+	@NotNull(message = Validations.validEventStatus)
```
Comment (MartinWahnschaffe) [inline sormas-api/src/main/java/de/symeda/sormas/api/event/EventDto.java:125]: The `@Required` annotation is currently used in EntityColumn.getRequired. It's ok to replace it here, but then we also have to extend this method to check for both annotations.

I'd also suggest to add a comment to the Required annotation to use NotNull instead and maybe even deprecate it.

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]

File: sormas-api/src/main/java/de/symeda/sormas/api/event/EventDto.java (hunk 1 above)
Comment (JonasCir) [reply sormas-api/src/main/java/de/symeda/sormas/api/event/EventDto.java:125]: I deprecated `@Required`. I wanted to do this for two years now... :smile:

File: sormas-backend/src/main/java/de/symeda/sormas/backend/info/EntityColumn.java [hunk 2]
```diff
@@ -49,7 +51,7 @@ public enum EntityColumn {
 	DATA_PROTECTION(256 * 30, EntityColumn::getDataProtection, false, true, false),
 	CAPTION(256 * 30, EntityColumn::getCaption, false, true, false),
 	DESCRIPTION(256 * 60, EntityColumn::getDescription, true, true, false),
-	REQUIRED(256 * 10, EntityColumn::getRequired, false, true, false),
```
Comment (MartinWahnschaffe) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/info/EntityColumn.java:52]: Let's keep the enum name "REQUIRED" otherwise translation will have to be updated.

**Comment by JonasCir** [comment]
fixed

**Comment by MartinWahnschaffe** [comment]
@JonasCir Sorry, two last things:
1. The Android CI didn't run through for 24 and 25. This may just be a CI thing, so I have now trigger a re-run of 24. Please check the results. 
2. Please execute DataDictionaryGenerator to update the data dictionary with the latest changes (e.g. eventInvestigationStatus and eventTitle should now be marked as required in the excel file).

**Comment by MartinWahnschaffe** [comment]
@JonasCir Please double check. Looks like the included dictionary still doesn't list Event.eventInvestigationStatus as required.

**Comment by JonasCir** [comment]
@MartinWahnschaffe fixed now, you can review the last commit :)

**Review by MartinWahnschaffe — APPROVED** [review]
