### PR TITLE
#6327 fixed NPE and initialization of unspecifc custom enums + unit test

### LINKED ISSUE #6327: Race condition populating CustomizableEnum caches
### Bug Description

In `CustomizableEnumFacadeEjb` the values are cached in several static `HashMap`s.
They are cleared and populated in `CustomizableEnumFacadeEjb::loadData`.
The pool of `CustomizableEnumFacade`s is adjusted dynamically, especially when under load.
Spawning new instances may result in a 
`RuntimeException: Invalid enum value [...] for customizable enum type DISEASE_VARIANT`.

### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version: 1.61.2
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information

Please get rid of current violation of Java naming convention for variables when fixing this ticket.

### PR DESCRIPTION
**Pull request by MartinWahnschaffe**
Fixes #6327

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java [hunk 1]
```diff
@@ -204,7 +204,7 @@ public boolean hasEnumValues(CustomizableEnumType type, Disease disease) {
 				.stream()
 				.filter(
 					e -> !disease.isPresent() && CollectionUtils.isEmpty(e.getDiseases())
-							|| e.getDiseases() != null && e.getDiseases().contains(disease.get()))
+							|| disease.isPresent() && e.getDiseases() != null && e.getDiseases().contains(disease.get()))
```
Comment (HolgerReiseVSys) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java:207]: Seems to be e bit too much logic for one expression
`if (disease.isPresent())…`?

File: sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java [hunk 2]
```diff
@@ -143,24 +138,19 @@
...
-				enumValue.setProperties(enumProperties.get(type).get(value));
-				enumValues.add(enumValue);
-			} catch (InstantiationException | IllegalAccessException | NoSuchMethodException | InvocationTargetException e) {
-				throw new RuntimeException(e);
-			}
-		});
+		Stream<String> diseaseValuesStream;
+		if (innerDisease.isPresent()) {
+			// combine specific and unspecific values
+			diseaseValuesStream = Stream.concat(
```
Comment (HolgerReiseVSys) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java:144]: Frankly, I do not completely understand what how this is working, but can't we get two enties for the same value now?

File: sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java [hunk 3]
```diff
@@ -169,46 +159,71 @@ public boolean hasEnumValues(CustomizableEnumType type, Disease disease) {
...
-					enumValues.putIfAbsent(customizableEnumValue.getValue(), customizableEnumValue.getCaption());
+		// may have already been put by another thread while this one was waiting (synchronized)
+		if (enumValuesByLanguage.get(enumClass).containsKey(language)) {
+			return;
+		}
+
+		boolean isCountryLanguage = StringUtils.equals(configFacade.getCountryLocale(), language.getLocale().toString());
+
+		Map<String, String> languageEnumValues = new HashMap<>();
+		for (CustomizableEnumValue customizableEnumValue : enumValueEntities.get(type)) {
```
Comment (HolgerReiseVSys) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java:184]: It might be a bit cleaner to stream enumValueEntities then collected in a map

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
~~Disease variants with diseases == null are not shown in the UI~~

File: sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java (hunk 3 above)
Comment (MartinWahnschaffe) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java:184]: I'd leave it as-is.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java (hunk 2 above)
Comment (MartinWahnschaffe) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/customizableenum/CustomizableEnumFacadeEjb.java:144]: No, enum values are unique per data type, so it's not possible that the same value is in the steam twice.

**Review by MateStrysewske — APPROVED** [review]
