### PR TITLE
#6643 [S2S] Editing entities with handed over ownership automatically returns them

### LINKED ISSUE #6643: [S2S] Editing entities with handed over ownership automatically returns them
### Bug Description

When editing handed over data sets after they have already been accepted, they're automatically returned.
### Steps to Reproduce

1. Send a data set with Sormas A and hand over the ownership. Stay on the form.
2. Accept the data set with Sormas B
3. Edit the data set in Sormas A and save
4. Refresh data set in Sormas B

### Expected Behavior

When the data set has been accepted in Sormas B, the data set should no longer be editable in Sormas A and especially get not automatically returned.
### Screenshots

Sending in Sormas A:
s2sHandingOver

Accepted in Sormas B:
s2sHandingOver2

Editing in Sormas A:
s2sHandingOver3

Refreshing in Sormas B:
s2sHandingOver4

Refreshing in Sormas A:
s2sHandingOver5

### System Details

* Device:
* SORMAS version: 1.64-SNAPSHOT
* Android version/Browser: firefox
* Server URL: test-de1.sormas.netzlink.com; test-de2.sormas.netzlink.com
* User Role: admin, national user

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #6643

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 1]
```diff
@@ -1552,45 +1554,50 @@ private void updateCaseWithBulkData(
...
 
-	private CaseDataDto saveCase(@Valid CaseDataDto dto, boolean handleChanges, boolean checkChangeDate) throws ValidationRuntimeException {
-
+	public CaseDataDto saveCase(@Valid CaseDataDto dto, boolean handleChanges, boolean checkChangeDate) {
 		return saveCase(dto, handleChanges, checkChangeDate, true);
 	}
 
-	public CaseDataDto saveCase(@Valid CaseDataDto dto, boolean handleChanges, boolean checkChangeDate, boolean syncShares)
+	public CaseDataDto saveCase(@Valid CaseDataDto dto, boolean handleChanges, boolean checkChangeDate, boolean internal)
 		throws ValidationRuntimeException {
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:1562]: I don't really like the paramter name `internal`, but I couldn't find a better name, If you know a better one I would change it.

It is used to skip edit allowed check and don't sync with other instances in case the update comes from another sormas instance.
