### PR TITLE
fixes #10041

### LINKED ISSUE #10041: User Role - No dropdown appearing if right for "Has associated district user" is checked
### Bug Description
Having a role with the right selected "Has associated district user", at User edit/create will not appear any dropdown to select user from district

### Steps to Reproduce
1. Have a Role with this right selected: "Has associated district user"
2. Create a user with the Role above
3. Check in the create/edit form of the User if a dropdown with users appears

### Expected Behavior
A dropdown with users assigned to a district should appear

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by ChristopherRiedel**
Fixes #10041

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java [hunk 1]
```diff
@@ -219,11 +219,13 @@ private void updateFieldsByUserRole() {
...
+        Set<UserRoleDto> userRoleDtos = userRolesFieldValue.stream().map(userRole -> userRoleMap.get(userRole)).collect(Collectors.toSet());
+        final JurisdictionLevel jurisdictionLevel = UserRoleDto.getJurisdictionLevel(userRoleDtos);
 
-		final boolean hasAssociatedDistrictUser = UserProvider.getCurrent().hasAssociatedDistrictUser();
-		final boolean hasOptionalHealthFacility = UserProvider.getCurrent().hasOptionalHealthFacility();
-		final boolean isPortHealthUser = UserProvider.getCurrent().isPortHealthUser();
+        UserRoleFacade userRoleFacade = FacadeProvider.getUserRoleFacade();
+        final boolean hasAssociatedDistrictUser = userRoleFacade.hasAssociatedDistrictUser(userRoleDtos);
+		final boolean hasOptionalHealthFacility = userRoleFacade.hasOptionalHealthFacility(userRoleDtos);
+		final boolean isPortHealthUser = userRoleFacade.isPortHealthUser(userRoleDtos);
```
Comment (carina29) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java:229]: Please align the associate officer dropdown with district: 
image

**Review by carina29 — CHANGES_REQUESTED** [review]

File: sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java (hunk 1 above)
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java:229]: There is a field (point of entry) in the gap. Basically it would make sense to have only the fields you need in the layout, but since that can change by the choice of user roles, major rebuilding would be needed here. I will not implement this in the context of a bug.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java [hunk 2]
```diff
@@ -219,11 +219,13 @@ private void updateFieldsByUserRole() {
...
 
         Set<UserRoleReferenceDto> userRolesFieldValue = (Set<UserRoleReferenceDto>) userRolesField.getValue();
-        final JurisdictionLevel jurisdictionLevel = UserRoleDto.getJurisdictionLevel(userRolesFieldValue.stream().map(userRole -> userRoleMap.get(userRole)).collect(Collectors.toSet()));
+        Set<UserRoleDto> userRoleDtos = userRolesFieldValue.stream().map(userRole -> userRoleMap.get(userRole)).collect(Collectors.toSet());
+        final JurisdictionLevel jurisdictionLevel = UserRoleDto.getJurisdictionLevel(userRoleDtos);
 
-		final boolean hasAssociatedDistrictUser = UserProvider.getCurrent().hasAssociatedDistrictUser();
-		final boolean hasOptionalHealthFacility = UserProvider.getCurrent().hasOptionalHealthFacility();
-		final boolean isPortHealthUser = UserProvider.getCurrent().isPortHealthUser();
+        UserRoleFacade userRoleFacade = FacadeProvider.getUserRoleFacade();
```
[the remark this answers is not in the document]
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserEditForm.java:225]: Sure

**Review by carina29 — APPROVED** [review]
