### PR TITLE
#9334 - Fix inconsistent task user filter logic and usage

### LINKED ISSUE #9334: Task - The task created from Event page by combination of the roles Surveillance Officer+Contact Officer is not visible in the Event form
### Bug Description
Task - The task created from Event page by combination of the roles Surveillance Officer+Contact Officer is not visible in the Event form

### Steps to Reproduce
1. As user having the roles Surveillance Officer+Contact Officer in combination open in edit mode an event
2. Create a task for the opened event
3. Look in the event form for the task created
4. Go to Task page and make a filter for the event context task

### Actual Behavior
Event task are not visible for this combination of role

### Expected Behavior
The task created should be visible at step 3
The task belongig to the context event should be visible at step 4

### System Details

* Device:
* SORMAS version: 1.73.0
* Android version/Browser:
* Server URL:
* User Role:

### Additional Information
The same issue appears if task is created from Travel Entry

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #9334

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java [hunk 1]
```diff
@@ -187,30 +205,40 @@ public Predicate createUserFilter(TaskQueryContext taskQueryContext, TaskCriteri
 		Predicate filter = cb.equal(taskPath.get(Task.CREATOR_USER), currentUser);
 		filter = cb.or(filter, cb.equal(taskPath.get(Task.ASSIGNEE_USER), currentUser));
 
-		Predicate caseFilter = caseService.createUserFilter(
-			new CaseQueryContext(cb, cq, joins.getCaseJoins()),
-			taskCriteria != null
-				? new CaseUserFilterCriteria().excludeLimitedSyncRestrictions(taskCriteria.isExcludeLimitedSyncRestrictions())
-				: null);
+		Predicate caseFilter = isContextCriteriaOrHasNoContext(taskCriteria, TaskContext.CASE)
```
Comment (sergiupacurariu) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java:208]: this method is always false when is called from either Case, Contact, Event, or TravelEntry. taskCriteria.taskContext is never populated. Due to this situation, some of the tasks are not shown.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java [hunk 2]
```diff
@@ -187,30 +205,40 @@ public Predicate createUserFilter(TaskQueryContext taskQueryContext, TaskCriteri
...
+				new CaseQueryContext(cb, cq, joins.getCaseJoins()),
+				taskCriteria != null
+					? new CaseUserFilterCriteria().excludeLimitedSyncRestrictions(taskCriteria.isExcludeLimitedSyncRestrictions())
+					: null)
+			: null;
 		if (caseFilter != null) {
 			filter = cb.or(filter, caseFilter);
 		}
-		Predicate contactFilter = contactService.createUserFilter(new ContactQueryContext(cb, cq, joins.getContactJoins()));
+		Predicate contactFilter = isContextCriteriaOrHasNoContext(taskCriteria, TaskContext.CONTACT)
```
Comment (sergiupacurariu) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java:218]: same as above taskContext is not populated

File: sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java [hunk 3]
```diff
@@ -187,30 +205,40 @@ public Predicate createUserFilter(TaskQueryContext taskQueryContext, TaskCriteri
...
+			? contactService.createUserFilter(new ContactQueryContext(cb, cq, joins.getContactJoins()))
+			: null;
 		if (contactFilter != null) {
 			filter = cb.or(
 				filter,
 				CriteriaBuilderHelper
 					.or(cb, contactFilter, createAssigneeOrObserverFilter(cb, joins.getAssignee(), joins.getTaskObservers(), currentUser)));
 		}
-		Predicate eventFilter = eventService.createUserFilter(new EventQueryContext(cb, cq, joins.getEventJoins()));
+		Predicate eventFilter = isContextCriteriaOrHasNoContext(taskCriteria, TaskContext.EVENT)
```
Comment (sergiupacurariu) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java:227]: same as above taskContext is not populated

File: sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java [hunk 4]
```diff
@@ -187,30 +205,40 @@ public Predicate createUserFilter(TaskQueryContext taskQueryContext, TaskCriteri
...
+			? eventService.createUserFilter(new EventQueryContext(cb, cq, joins.getEventJoins()))
+			: null;
 		if (eventFilter != null) {
 			filter = cb.or(filter, eventFilter);
 		}
-		Predicate travelEntryFilter = travelEntryService.createUserFilter(new TravelEntryQueryContext(cb, cq, joins.getTravelEntryJoins()));
+		Predicate travelEntryFilter = isContextCriteriaOrHasNoContext(taskCriteria, TaskContext.TRAVEL_ENTRY)
```
Comment (sergiupacurariu) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/task/TaskService.java:233]: same as above taskContext is not populated

**Review by sergiupacurariu — CHANGES_REQUESTED** [review]
