### PR TITLE
#4276 Add date and dose validators for vaccinations

### LINKED ISSUE #4276: Vaccination Fields should have validations
### Steps to Reproduce
1. Create a Case with Vaccination
2. Set the dates of the first and last vaccination the wrong way. Use dates from a year when Covid was not existent for example. 
3. Use a float number like 1.345 for the Vaccine dose field

### Expected Behavior
These fields should have validations for this kind of scenario.
### Screenshots
image

### System Details
* Device:Windows
* SORMAS version: Sormas version 1.55.0-snapshot
* Android version/Browser: chrome
* Server URL: Localhost
* User Role: NatUser

### Additional Information
this ticket is related to #4137

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
Closes #4276

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java [hunk 1]
```diff
@@ -627,14 +627,31 @@ protected void addFields() {
...
+					.getValidationError(Validations.beforeDate, firstVaccinationDateField.getCaption(), lastVaccinationDateField.getCaption())));
+		lastVaccinationDateField.addValidator(
+			new DateComparisonValidator(
+				lastVaccinationDateField,
+				firstVaccinationDateField,
+				false,
+				false,
+				I18nProperties
+					.getValidationError(Validations.afterDate, lastVaccinationDateField.getCaption(), firstVaccinationDateField.getCaption())));
+		System.out.println(firstVaccinationDateField.getValidators().size());
```
Comment (MateStrysewske) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:654]: Remove this line

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/NumberValidator.java [hunk 2]
```diff
@@ -28,9 +28,11 @@
...
 	private BigDecimal minValue;
 	private BigDecimal maxValue;
+	private boolean decimalAllowed;
 
 	public NumberValidator(String errorMessage) {
 		super(errorMessage);
+		decimalAllowed = true;
 	}
 
 	public NumberValidator(String errorMessage, Number minValue, Number maxValue) {
```
Comment (MateStrysewske) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/NumberValidator.java:38]: You can remove the code from this constructor and instead call the new one like this to avoid redundancies:

`this(errorMessage, minValue, maxValue, true);`

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Seems like the label wasn't added to the issue, but this also needs to be done in the mobile app, otherwise there might be wrong data coming in from there.

**Review by MateStrysewske — APPROVED** [review]
