### PR TITLE
#9883 - Proper annotations for contact category

### LINKED ISSUE #9883: contactCategory is not correctly documented in data dictionary
### Bug Description

Based on https://github.com/hzi-braunschweig/SORMAS-Project/issues/1635, the `contactCategory` field is hidden on non-de servers and only applicable for COVID-19. This is not correctly documented in the data dictionary.
### Steps to Reproduce

1. Create a new contact
2. Select COVID-19
3. Check for the contact category field
4. Download the data dictionary and check `contactCategory`

### Expected Behavior

- The data dictionary documentation should depict that this field is exclusive or ignored on some instances and specific for COVID-19
### Screenshots

contactCategoryInt2
contactCategoryInt

### System Details

* Device:
* SORMAS version: 1.73.2
* Android version/Browser: chrome
* Server URL: release-international.sormas.netzlink.com
* User Role: admin, national user

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #9883

### CODE REVIEW

File: sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java [hunk 1]
```diff
@@ -197,9 +197,13 @@ public class ContactDto extends SormasToSormasShareableDto {
 	@Size(max = FieldConstraints.CHARACTER_LIMIT_DEFAULT, message = Validations.textTooLong)
 	private String tracingAppDetails;
 	private ContactProximity contactProximity;
+	@HideForCountriesExcept
 	@SensitiveData
 	@Size(max = FieldConstraints.CHARACTER_LIMIT_DEFAULT, message = Validations.textTooLong)
 	private String contactProximityDetails;
```
Comment (BarnaBartha) [inline sormas-api/src/main/java/de/symeda/sormas/api/contact/ContactDto.java:203]: is the proximity details field also something specific to Germany ?
i don't se this in the ticket

**Review by BarnaBartha — APPROVED** [review]
