### PR TITLE
bug/10538_disable_user_are_showed

### LINKED ISSUE #10538: Disabled user roles are displayed in the list when 'Enabled' appears selected by default
### Bug Description
When an admin user accesses the Users Directory -> User Roles, 'Enabled' appears to be set to default. However, the list of user roles contain both enabled and disabled user roles.
If 'Enabled' is selected manually, the disabled user roles are no longer displayed in the list.

### Steps to Reproduce

1. Log in with an Admin user;
2. Open the Users Directory and select the User Roles tab;
3. Make sure you have at least one or two disabled user roles;
4. Inspect the list of user roles and search if the disabled user roles are displayed;

### Expected Behavior
The disabled user roles should not be displayed; should be displayed only when 'Disabled' is selected;

### Screenshots
image
image

### System Details

* Device: Windows 10
* SORMAS version: 1.76.0 - SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local server
* User Role: admin

### PR DESCRIPTION
**Pull request by dinua**
Fixes #10538

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRolesView.java [hunk 1]
```diff
@@ -120,7 +121,7 @@ public HorizontalLayout createStatusFilterBar() {
 		enabledFilter.setId(UserRoleDto.ENABLED);
 		enabledFilter.setWidth(200, Unit.PIXELS);
 		enabledFilter.setInputPrompt(I18nProperties.getPrefixCaption(UserRoleDto.I18N_PREFIX, UserRoleDto.ENABLED));
-		enabledFilter.addItems(ENABLED_FILTER, DISABLED_FILTER);
+		enabledFilter.addItems(ALL_FILTER, ENABLED_FILTER, DISABLED_FILTER);
```
Comment (sergiupacurariu) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/user/UserRolesView.java:124]: instead of adding a new item could you explore if we could just add a "Boolean.TRUE" instead of null in criteria enabled logic?

**Review by sergiupacurariu — APPROVED** [review]
