### PR TITLE
bug/8208_user_can_not_readd_deleted_event_participant

### LINKED ISSUE #8208: [Event Participants] Users can not re-add deleted event participants
### Bug Description

If a user deletes an event participant from an event, and then they try to re-add the same person as an event participant to the same event, a warning message appears stating that 'Please check input data. The person you have selected is already defined as an event participant of this event'.

### Steps to Reproduce

1. Open an existing event or create one;
2. Navigate to the 'Event Participants' tab and open the 'Add new event participant' form;
3. Use the person search option to search for an existing person or manually add the details of an already existing person (i.e. a person that is associated with another entity such as case, contact or immunization);
4. Delete the 'Event participant' added at step 3;
5. Re-open the 'Add new event participant' form and search for or add manually the details of the person used at step 3;
6. Click 'Save' in the form.

### Actual Behavior

A warning message appears and the user is not able to save the 'Event Participant'.

### Expected Behavior

No error message appears and the user is able to save the 'Event Participant'.

### Screenshots

Delete event participant

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT(19c54c2)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, NatUser

### Additional Information

Note regarding the person used in the steps to reproduce - the person needs to have another associated entity so that when the user deletes them from the 'Event Participants' list, the person does not get deleted from the system (i.e. from the 'Persons' directory).

### PR DESCRIPTION
**Pull request by dinua**
Fixes #8208

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipant.java [hunk 1]
```diff
@@ -77,6 +78,7 @@
 	private SormasToSormasOriginInfo sormasToSormasOriginInfo;
 	private List<SormasToSormasShareInfo> sormasToSormasShares = new ArrayList<>(0);
 	private VaccinationStatus vaccinationStatus;
+	private boolean deleted;
```
Comment (sergiupacurariu) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventParticipant.java:81]: please remove "deleted" field from EventParticipant. This field already exists on DeletableAdo which is extended by this entity class.
