### PR TITLE
National User can no longer edit multiple sections from cases #10547

### LINKED ISSUE #10547: National User can no longer edit multiple sections from cases
### Bug Description

A National User is no longer able to edit multiple sections from a case's page
See description for point I in https://github.com/hzi-braunschweig/SORMAS-Project/issues/10474
### Steps to Reproduce

1.
2.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #10547

Pseudonymization of not personal and/or sensitive data will not mark the DTO as pseudonymized.
The pseudonymized flag is used to mark sensitive and/or personal fields on the UI. The other inaccessible fields are not shown on the UI

The solution was discussed with @MateStrysewske

### CODE REVIEW

File: sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java [hunk 1]
```diff
@@ -191,12 +191,16 @@ private <DTO> boolean pseudonymizeDto(
...
 
 		for (Field field : pseudonymizableFields) {
-			if (!getFieldAccessCheckers(inJurisdiction).isAccessible(field, pseudonymizeMandatoryFields)) {
+			FieldAccessCheckers fieldAccessCheckers = getFieldAccessCheckers(inJurisdiction);
+			if (!fieldAccessCheckers.isAccessible(field, pseudonymizeMandatoryFields)) {
 				pseudonymizeField(dto, field, defaultPseudonymizerClass);
-				didPseudonymization = true;
+				// only personal and sensitive data pseudonymization needs special handling on the client side
+				// other not accessible data is hidden on the client side, so just cleanup and don't mark the DTO as pseudonymized
+				didPersonalOrSensitiveDataPseudonymization = !fieldAccessCheckers
```
Comment (MartinWahnschaffe) [inline sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java:202]: I think this has to be "|=" instead of "="

File: sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java [hunk 2]
```diff
@@ -229,14 +233,14 @@ private <DTO> boolean pseudonymizeDto(
...
-			((Pseudonymizable) dto).setPseudonymized(didPseudonymization);
+			((Pseudonymizable) dto).setPseudonymized(didPersonalOrSensitiveDataPseudonymization);
 		}
 
 		if (customPseudonymization != null) {
 			customPseudonymization.pseudonymize(dto);
 		}
 
-		return didPseudonymization;
+		return didPersonalOrSensitiveDataPseudonymization;
```
Comment (MartinWahnschaffe) [inline sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java:243]: Please add a comment to PseudonymizableDto pseudonymized field.

File: sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java (hunk 1 above)
Comment (MartinWahnschaffe) [reply sormas-api/src/main/java/de/symeda/sormas/api/utils/pseudonymization/DtoPseudonymizer.java:202]: Better: Only do logic when didPersonalOrSensitiveDataPseudonymization is still false

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]

**Review by MartinWahnschaffe — APPROVED** [review]
Looks good to me.  Please ask QA team to also check whether accessing a case outside the own jurisdiction is still pseudonymizing the data as expected.
