### PR TITLE
fixes #6296

### LINKED ISSUE #6296: Test result positive for contacts in DEMIS lab messages is saved as pending
### Bug Description
Processing DEMIS lab messages with a positive test result for contacts can be saved but are saved as "pending".

### Steps to Reproduce

1. choose a lab message for a contact
2. start processing 
3. choose the contact 
4. document the sample, test result positive was automatically set to positive (right!) 
5. save the sample
6. open the contact form
7. sample is shown as pending 

This accounts only for contacts!

### Expected Behavior
Positive test results of samples should be mapped correctly during DEMIS lab message processing. 

### Screenshots

C127E322-C2BE-4D0C-9755-74F35C63515F_1_105_c

### System Details

* Device:
* SORMAS version: 1.62.1
* Android version/Browser: chrome
* Server URL: https://test1402.sormas-oegd.de reproduced here: https://test1402.sormas-oegd.de/sormas-ui/#!contacts/data/R7YUDT-SJ3M5W-2O6B2C-NXDCCM7Y 
* User Role: admin

### PR DESCRIPTION
**Pull request by ChristopherRiedel**
Fixes #6296

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java [hunk 1]
```diff
@@ -685,6 +685,7 @@ private FacilityReferenceDto getLabReference(LabMessageDto labMessageDto) {
 		if (!testReportDtos.isEmpty()) {
 			TestReportDto testReportDto = testReportDtos.get(0);
 			((ComboBox) sampleCreateComponent.getWrappedComponent().getField(PathogenTestDto.TEST_RESULT)).setValue(testReportDto.getTestResult());
+			((ComboBox) sampleCreateComponent.getWrappedComponent().getField(SampleDto.PATHOGEN_TEST_RESULT)).setValue(testReportDto.getTestResult());
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java:688]: This does not align with the specification of the ticket (handling of several test reports). But I since the processing of multiple lab messages is currently not supported at all, this probably needs to go to another issue.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java [hunk 2]
```diff
@@ -151,7 +152,8 @@ protected void addCommonFields() {
 		addField(SampleDto.SHIPPED, CheckBox.class);
 		addField(SampleDto.RECEIVED, CheckBox.class);
 
-		addField(SampleDto.PATHOGEN_TEST_RESULT, ComboBox.class);
+		ComboBox testResultField = addField(SampleDto.PATHOGEN_TEST_RESULT, ComboBox.class);
+		testResultField.removeItem(PathogenTestResultType.NOT_DONE);
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java:156]: Why did you remove `PathogenTestResultType.NOT_DONE` here?

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleCreateForm.java [hunk 3]
```diff
@@ -186,7 +186,6 @@ protected void addFields() {
 			defaultValueChangeListener();
 			final NullableOptionGroup samplePurposeField = (NullableOptionGroup) getField(SampleDto.SAMPLE_PURPOSE);
 			samplePurposeField.setValue(SamplePurpose.EXTERNAL);
-			getField(SampleDto.PATHOGEN_TEST_RESULT).setVisible(false);
```
Comment (FredrikSchaeferVitagroup) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleCreateForm.java:189]: I find the layout a little confusing like that, probably because there is the final result field, and two rows below the test result field. 
Usually, when creating a pathogen test while creating a sample, the user has to click a checkbox labelled "Create a test result for this sample now", and only after that the test result field shows. When processing a lab message, the test result field shows right away.
I suggest to add a thin horizontal line here:
image
This emphasizes that the final result belongs to the sample, and the test result belong to the pathogen test.

**Review by FredrikSchaeferVitagroup — CHANGES_REQUESTED** [review]

File: sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java (hunk 1 above)
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/labmessage/LabMessageController.java:688]: I agree

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java (hunk 2 above)
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/samples/AbstractSampleForm.java:156]: Because it's removed in every occasion PathogetTestType in a ComboBox

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleCreateForm.java (hunk 3 above)
Comment (ChristopherRiedel) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/samples/SampleCreateForm.java:189]: Ok, I'll do so.

**Comment by ChristopherRiedel** [comment]
Screenshot_021
new horizontal rule

**Review by MateStrysewske — APPROVED** [review]
