### PR TITLE
#8807 allow relevant method calls with EXTERNAL_VISITS right

### LINKED ISSUE #8807: Climedo doesn't sync correctly (EJBAccessException)
### Bug Description

There seems to be a user rights or authentication problem when trying to sync climedo with SORMAS. 
The error in logs says: "Client not authorized for this invocation"

### Steps to Reproduce

Register SMS as well as by e-mail, enter the symptoms and submit. 
No error message, but the system does not show the entry, neither under "Follow-up" nor in the "Follow-up view".

Doesn't work with "ExternalVisitDto #personUUID: XXGMVF-AF3BDN-6D2DPY-ECW4KG2I" on https://test1402.sormas.netzlink.com/

### System Details

* Device: 
* SORMAS version: 1.70.2
* Android version/Browser: 
* Server URL: 1402
* User Role:

### Additional Information

Log excerpt [Climedo_User_Not_Authorized.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8479129/Climedo_User_Not_Authorized.txt)

```bash
Caused by: javax.ejb.EJBAccessException: Client not authorized for this invocation
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2397)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2183)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2104)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy665.toDto(Unknown Source)
	at de.symeda.sormas.backend.caze.__EJB31_Generated__CaseFacadeEjb$CaseFacadeEjbLocal__Intf____Bean__.toDto(Unknown Source)
	at de.symeda.sormas.backend.visit.VisitFacadeEjb.onVisitChanged(VisitFacadeEjb.java:622)
```

### PR DESCRIPTION
**Pull request by FredrikSchaeferVitagroup**
Fixes #8807

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 1]
```diff
@@ -2609,6 +2610,7 @@ public CaseReferenceDto convertToReferenceDto(Case source) {
 		return dto;
 	}
 
+	@RolesAllowed(UserRight._EXTERNAL_VISITS)
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:2613]: This only allows `UserRight._EXTERNAL_VISITS` to use this method.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java [hunk 2]
```diff
@@ -1606,6 +1606,7 @@ public static ContactReferenceDto toReferenceDto(Contact source) {
 		return source.toReference();
 	}
 
+	@RolesAllowed(UserRight._EXTERNAL_VISITS)
```
Comment (StefanKock) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java:1609]: This only allows `UserRight._EXTERNAL_VISITS` to use this method.

**Review by StefanKock — CHANGES_REQUESTED** [review]
I suppose the permissions from the class need to be added for `toDto` methods to not break "regular" usages.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java (hunk 1 above)
Comment (FredrikSchaeferVitagroup) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:2613]: It should, but it doesn't seem to. I am about to add a comment to the PR listing some of my own open questions. Maybe we can then use this as a basis for discussion.

**Comment by FredrikSchaeferVitagroup** [comment]
The current suggested changes seem to solve the problem. However, there are some things still not clear to me.

1. (Why) is it necessary to add the RolesAllowed-annotation to the toDto of the Case- and ContactFacadeEjb? It seems that other roles can access this method without having a right annotated here.
2. Should we make sure that the External_Visits-right is not forgotten when the RolesAllowed-annotation is introduced to the VisitFacadeEjb and (maybe) the FeatureConfigurationFacadeEjb? Methods there can be triggered by saving an external visit.

**Review by StefanKock — APPROVED** [review]
Remarked findings were solved

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 3]
```diff
@@ -1378,7 +1378,8 @@ public CaseDataDto save(@Valid @NotNull CaseDataDto dto) throws ValidationRuntim
 	@Override
 	@RolesAllowed({
 		UserRight._CASE_CREATE,
-		UserRight._CASE_EDIT })
+		UserRight._CASE_EDIT,
+		UserRight._EXTERNAL_VISITS })
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:1382]: I would introduce a new method for handling case updates by external visits and should not allow save for external visit right

**Comment by leventegal-she** [comment]
> 1. (Why) is it necessary to add the RolesAllowed-annotation to the toDto of the Case- and ContactFacadeEjb? It seems that other roles can access this method without having a right annotated here.

I would suggest to use the static toDto methods like `toCaseDto` and `toContactDto` and keep the toDto methods not annotated

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java (hunk 3 above)
Comment (StefanKock) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:1382]: Somehow the method is already for that purpose that @leventegal-she suggested: It's only used by `VisitFacade.saveVisit` but from a variety of origins.

grafik

Comment (leventegal-she) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:1382]: But then why the `save` should be allowed for UserRight._EXTERNAL_VISITS?

Comment (StefanKock) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:1382]: Looking again on this I think we should maybe exclude the `CaseFacadeEjb.save(CaseDataDto, boolean)` from the `CaseFacade` and change it to private and remove the permissions since it's only internally called by CaseFacadeEjb itself (at least on my mostly updated `development` branch).

**Review by StefanKock — CHANGES_REQUESTED** [review]
We need to discuss the changes and approach.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java (hunk 3 above)
Comment (StefanKock) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:1382]: Discussed with @FredrikSchaeferVitagroup: The state on 1.70.x is different: saveVisit calls directly `CaseFacade.save(caseDataDto, boolean)` and therefore needs that annotation. In #8508 the new method `CaseFacade.updateSymptomsByVisit` was introduced and makes annotations on `CaseFacade.save(caseDataDto, boolean)` superfluous (the usage of that method could be reduced in that ticket or afterwards).

**Review by StefanKock — APPROVED** [review]
