### PR TITLE
Bugfix/bug 8014 merge cases and contacts

### LINKED ISSUE #8014: [Cases and Contacts] Error message 'A problem has occurred' appears when trying to merge two cases/contacts that have vaccinations
### Bug Description

An error message 'A problem has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it' appears when trying to merge 2 cases or contacts that have vaccinations associated.

### Steps to Reproduce

1. Create two new cases, with the exact same data for all the mandatory fields (when the person duplicate detection is triggered when the second case is created, select 'Create new person');
2. Add vaccinations to the 2 cases;
3. In the 'Cases' directory, click on the 'More' button and select 'Merge duplicates' from the dropdown;
4. Click 'Confirm' in the filters section on the 'Merge Duplicate Cases' page;
5. Click 'Merge' on one of the cases created at step 1;
6. In the 'Confirm Your Choice' pop-up click 'Confirm'.

### Actual Behavior

An error message appears stating: 'A problem has occurred. An unexpected error occurred. Please contact your supervisor or administrator and inform them about it' and the 2 cases are not merged.

### Expected Behavior

No error message appears and the 2 cases are merged.

### Screenshots

image

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### Additional Information

If one of the cases or contacts does not have a vaccination, and the user clicks 'Merge' on it in the 'Merge Duplicate Cases'/'Merge Duplicate Contacts' page, the error message appears after they click 'Confirm' in the 'Confirm Your Choice' pop-up. 
However, if the user clicks 'Merge' on the case or contact that has the vaccination information, the merge is successful. 

Logs from reproducing the error message:
[logs for error when merging 2 cases with vaccinations.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8072309/logs.for.error.when.merging.2.cases.with.vaccinations.txt)

### PR DESCRIPTION
**Pull request by carina29**
Fixes #8014

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java [hunk 1]
```diff
@@ -461,6 +471,19 @@ protected Immunization fillOrBuildEntity(@NotNull ImmunizationDto source, Immuni
 		target.setValidUntil(source.getValidUntil());
 		target.setRelatedCase(caseService.getByReferenceDto(source.getRelatedCase()));
 
+		//In case of merge the copyVaccinations will be false
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java:474]: unnecassary comment.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java [hunk 2]
```diff
@@ -586,10 +603,16 @@ public void syncSharesAsync(Immunization immunization) {
 	public void copyImmunizationsToLeadPerson(ImmunizationDto immunizationDto, PersonDto leadPerson) {
 		Immunization newImmunization = new Immunization();
 		newImmunization.setUuid(DataHelper.createUuid());
-		newImmunization = fillOrBuildEntity(immunizationDto, newImmunization, false);
+
+		// add new param with false in other cases with true
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java:607]: unnecessary comment

File: sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java [hunk 3]
```diff
@@ -586,10 +603,16 @@ public void syncSharesAsync(Immunization immunization) {
...
+		newImmunization = fillOrBuildEntity(immunizationDto, newImmunization, false, false);
 
 		newImmunization.setPerson(personService.getByReferenceDto(leadPerson.toReference()));
-		newImmunization.setVaccinations(new ArrayList<>());
+		// newImmunization.setVaccinations(new ArrayList<>());
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/immunization/ImmunizationFacadeEjb.java:611]: please remove commented code

File: sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java [hunk 4]
```diff
@@ -823,6 +805,87 @@ public void testMergePerson() {
...
+
+		PersonDto otherPerson = createPersonWithImmunizationAndVaccination("firstName2", "lastName2");
+		List<ImmunizationDto> otherPersonImmunizationDto = getImmunizationFacade().getByPersonUuids(Collections.singletonList(otherPerson.getUuid()));
+		List<VaccinationDto> otherPersonVaccinations = otherPersonImmunizationDto.get(0).getVaccinations();
+
+		getPersonFacade().mergePerson(leadPerson, otherPerson);
+		List<ImmunizationDto> mergedPersonImmunizationDtoList =
+			getImmunizationFacade().getByPersonUuids(Collections.singletonList(leadPerson.getUuid()));
+
+		//TODO after solving bug #8333: check the immunizations and vaccinations list and number
```
Comment (leventegal-she) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java:846]: Unnecessary comment, most probably the test will fail after fixing 8333

File: sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java [hunk 5]
```diff
@@ -823,6 +805,87 @@ public void testMergePerson() {
...
+	public void testMergePersonWithoutVaccinationWithPersonWithVaccination() {
+		PersonDto leadPersonWithoutVaccination = creator.createPerson("firstName5", "lastName5");
+		PersonDto otherPersonWithVaccination = createPersonWithImmunizationAndVaccination("firstName6", "lastName6");
+
+		getPersonFacade().mergePerson(leadPersonWithoutVaccination, otherPersonWithVaccination);
+		List<ImmunizationDto> immunizationDtoList =
+			getImmunizationFacade().getByPersonUuids(Collections.singletonList(leadPersonWithoutVaccination.getUuid()));
+
+		Assert.assertEquals(immunizationDtoList.size(), 1);
+		//TODO after solving bug #8333: assert the number of vaccinations too
```
Comment (leventegal-she) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java:873]: unnecessary comment

File: sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java [hunk 6]
```diff
@@ -235,6 +239,16 @@ public void init() {
 		creator.createUser(null, null, null, "ad", "min", UserRole.ADMIN, UserRole.NATIONAL_USER);
 		when(MockProducer.getPrincipal().getName()).thenReturn("admin");
 
+		rdcf = creator.createRDCF("Region 1", "District 1", "Community 1", "Facility 1", "Point of entry 1");
```
Comment (leventegal-she) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/AbstractBeanTest.java:242]: This is super class of a lot of other classes and none of them needs these variables except PersonFacadeEjbTest. Please override the init method in PersonFacadeEjbTest and move these variables there

**Review by leventegal-she — CHANGES_REQUESTED** [review]
There are a few classes where only the formatting was changed please revert those changes.

File: sormas-api/src/test/java/de/symeda/sormas/api/utils/InfoProviderTest.java [hunk 7]
```diff
@@ -124,9 +124,9 @@ public void testIsSnapshotVersion() {
 	public void testIsSnapshot() {
 
 		InfoProvider cut = InfoProvider.get();
-		assertTrue(cut.isSnapshot("1.69.0-SNAPSHOT"));
-		assertTrue(cut.isSnapshot("1.69.1-SNAPSHOT"));
-		assertFalse(cut.isSnapshot("1.69.0"));
-		assertFalse(cut.isSnapshot("1.69.1"));
+		assertTrue(cut.isSnapshot("1.70.0-SNAPSHOT"));
```
Comment (leventegal-she) [inline sormas-api/src/test/java/de/symeda/sormas/api/utils/InfoProviderTest.java:127]: should not be changed

**Review by leventegal-she — CHANGES_REQUESTED** [review]
There are still a lot of changes that are only formatting related

File: sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java [hunk 8]
```diff
@@ -63,16 +68,47 @@
...
+	protected UserDto nationalUser;
+
+	/**
+	 * Resets mocks to their initial state so that mock configurations are not
+	 * shared between tests.
+	 */
+
+	@Before
+	@Override
+	public void init() {
```
Comment (leventegal-she) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/person/PersonFacadeEjbTest.java:89]: it's not needed to be annotated with @Before because the super method is already annotated and you can call super.init() instead of duplicating it's content here

**Review by leventegal-she — CHANGES_REQUESTED** [review]
