### PR TITLE
#5549 Add doubleclick timer to showDetailsListener

### LINKED ISSUE #5549: Multiple clicks on edit icons in tables/grids open many pop-up windows
### Bug Description
Implementation of #5227 should prevent being able to double-click buttons. However, clicking edit icons in grids multiple times opens many forms which stack on top of each other.

### Steps to Reproduce

1. Go to e.g. the user section or configurations and click any edit button  many times in quick succession.
2. Check how many windows were opened.

### Expected Behavior
Buttons should not be able to be double-clicked

### Screenshots
doubleClickError

### System Details

* Device:
* SORMAS version: 1.60
* Android version/Browser: firefox
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

### PR DESCRIPTION
**Pull request by DavidBaldsiefen**
Fixes #5549

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java [hunk 1]
```diff
@@ -19,6 +21,8 @@
 	private final boolean showOnDoubleClick;
 	private final Consumer<T> itemHandler;
 
+	private DateTime lastHandlingTimestamp;
```
Comment (StefanKock) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java:24]: Use Java Time API, not Joda Time

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java [hunk 2]
```diff
@@ -45,6 +49,7 @@ public ShowDetailsListener(String detailsColumnId, boolean showOnDoubleClick, Co
 		this.detailsColumnId = detailsColumnId;
 		this.showOnDoubleClick = showOnDoubleClick;
 		this.itemHandler = itemHandler;
+		this.lastHandlingTimestamp = DateTime.now().minusSeconds(1);
```
Comment (StefanKock) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java:52]: just take "now", why subtracting a second?

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java [hunk 3]
```diff
@@ -70,11 +75,14 @@ public boolean isShowOnDoubleClick() {
 
 	@Override
 	public void itemClick(ItemClick<T> event) {
-
 		if (event.getItem() != null
 			&& ((event.getColumn() != null && detailsColumnId.equals(event.getColumn().getId()))
 				|| (showOnDoubleClick && event.getMouseEventDetails().isDoubleClick()))) {
-			handleItemClick(event);
+			// if the last invocation of the itemHandler is less than 1 second ago, ignore the event
+			if (DateTime.now().minusSeconds(1).isAfter(lastHandlingTimestamp)) {
```
Comment (StefanKock) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java:82]: just take "now", why subtracting a second?

**Review by StefanKock — CHANGES_REQUESTED** [review]
I generally like the approach, looks good to solve the problem. But don't use joda-time and remove superfluous substraction.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java (hunk 2 above)
Comment (StefanKock) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java:52]: I got it: It's the initialization to avoid `null` check later. Maybe a code comment would help

Comment (DavidBaldsiefen) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java:52]: It's necessary so the columns can be clicked from the beginning on, and not just after 1 second has passed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java (hunk 3 above)
Comment (DavidBaldsiefen) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java:82]: agreed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java [hunk 4]
```diff
@@ -49,7 +48,7 @@ public ShowDetailsListener(String detailsColumnId, boolean showOnDoubleClick, Co
 		this.detailsColumnId = detailsColumnId;
 		this.showOnDoubleClick = showOnDoubleClick;
 		this.itemHandler = itemHandler;
-		this.lastHandlingTimestamp = DateTime.now().minusSeconds(1);
+		this.lastHandlingTimestamp = LocalDateTime.now().minusSeconds(1); // make sure the columns are clickable from the beginning
```
Comment (StefanKock) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ShowDetailsListener.java:51]: Don't mix code and comment in one line, put it before. See rule: https://sonarqube.sormas.netzlink.com/coding_rules?languages=java&open=java%3AS139&q=comment

**Review by StefanKock — CHANGES_REQUESTED** [review]

**Comment by StefanKock** [comment]
Only one finding. I highly suggest to squash the changes when merging (keep the first commit message) because the commit history has no longterm value.
