### PR TITLE
#9386 - [User Rights] POE National User gets and error message when h…

### LINKED ISSUE #9386: [User Rights] POE National User gets and error message when he downloads Sample Export from the Cases Directory
### Bug Description
When the POE National user tries to download the Sample Export table from the Cases Directory, he gets an error message. 
Possibly because he doesn't have a Sample Directory and Sample related user rights.

Stacktrace: 
[stacktrace sample export.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8814103/stacktrace.sample.export.txt)

### Steps to Reproduce

1. Log in with a POE National User.
2. Navigate to the Cases Directory and download the 'Sample Export' table.

### Actual Behavior
The user gets an error message.

### Expected Behaviour
The Export button should not be visible in the first place for users that don't have Sample view rights.

### Screenshots
sample export POE NAT USER

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.72.1
* Android version/Browser: Chrome
* Server URL: test1402.sormas.netzlink.com and local machine
* User Role: POE National User

### PR DESCRIPTION
**Pull request by cazacmarin**
Fixes #9386

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java [hunk 1]
```diff
@@ -127,6 +127,7 @@ public class CasesView extends AbstractView {
 	private final boolean caseFollowUpEnabled;
 	private final boolean hasClinicalCourseRight;
 	private final boolean hasTherapyRight;
+	private final boolean hasExportSamples;
```
Comment (carina29) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CasesView.java:130]: please change this boolean to hasExportSamplesRight

**Review by carina29 — APPROVED** [review]
