### PR TITLE
Bugfix 7608 extend creator calculation

### LINKED ISSUE #7608: Edit and create rights not initialised in task edit form
### Bug Description

The edit and create rights are not properly initialised in the task edit form.

### Steps to Reproduce

1.
2.

### Expected Behavior

The variable should be set to TASK_CREATE or TASK_EDIT, depending on whether `create` is true or not.

### System Details

* Device:
* SORMAS version:
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by alexcaruntu-vita**
Fixes #7608

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java [hunk 1]
```diff
@@ -331,9 +331,12 @@ private void updateByCreatingAndAssignee() {
 			boolean creating = value.getCreationDate() == null;
 
 			UserDto user = UserProvider.getCurrent().getUser();
-			boolean creator = user.equals(value.getCreatorUser());
+			boolean creator = value.getCreatorUser() == null
+				? UserRole.getJurisdictionLevel(user.getUserRoles()) == JurisdictionLevel.NATION
+				: user.equals(value.getCreatorUser());
 			boolean supervisor = UserRole.isSupervisor(user.getUserRoles());
 			boolean assignee = user.equals(getFieldGroup().getField(TaskDto.ASSIGNEE_USER).getValue());
+			boolean observer = user.equals(getFieldGroup().getField(TaskDto.OBSERVER_USERS).getValue());
```
Comment (MateStrysewske) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/task/TaskEditForm.java:339]: That's not what I meant :) Remove this line, and instead add the `TaskDto.OBSERVER_USERS` field to the list of fields in the third setReadOnly call below (where you now added the `observer` boolean check)

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Review by MateStrysewske — APPROVED** [review]
