### PR TITLE
#5049 handle demis adapter configuration exception more gracefully

### LINKED ISSUE #5049: [DEMIS Interface] The uuid and message date of lab message can be edited when the message is not properly displayed
### Bug Description
When lab messages are not properly displayed, the uuid and the message date can be edited and sent to other organizations that are reachable via Sormas 2 Sormas. However, the uuid and message date does not seem to change upon sending.
### Steps to Reproduce
1. Improperly configure the lab message interface so that messages are not properly displayed
2. View the lab message
3. Change the uuid and the message date
4. send entry via Sormas 2 Sormas

### Expected Behavior
The uuid and message date should not be editable.
### Screenshots
labMessageDisplayError
labMessageDisplayError2

**After "Sent to another organization" was selected:**
labMessageDisplayError3

**Lab message in other instance**
labMessageDisplayError4

### System Details
* Device:
* SORMAS version: 1.59.0 - SNAPSHOT
* Android version/Browser: firefox
* Server URL: test-de1.sormas.netzlink.com
* User Role: admin, national user

### PR DESCRIPTION
**Pull request by FredrikSchaeferVitagroup**
closes #5049

### CODE REVIEW

File: sormas-api/src/main/java/de/symeda/sormas/api/FacadeProvider.java [hunk 1]
```diff
@@ -407,7 +407,7 @@ public static ExternalLabResultsFacade getExternalLabResultsFacade() {
 				return (ExternalLabResultsFacade) get().ic.lookup(jndiName);
 			}
 		} catch (NamingException e) {
-			throw new RuntimeException(e.getMessage(), e);
```
Comment (leventegal-she) [inline sormas-api/src/main/java/de/symeda/sormas/api/FacadeProvider.java:410]: It doesn't make sense to catch the exception if you just trow it. Please remove the try catch.

**Review by leventegal-she — CHANGES_REQUESTED** [review]

**Review by leventegal-she — APPROVED** [review]
