### PR TITLE
#6080 persist case completeness without changedate

### LINKED ISSUE #6080: CaseService.updateCompleteness: Persist calculated completeness without updating the Case.changeDate [1]
### Problem Description

Follow up to #5543: When sending data from SurvNet (initial import), the last change imposes two severe problems:

1. When the completeness is calculated, the Case.changeDate is updated. This causes that the case is then implicitly marked to be sent to SurvNet. This needs to be avoided.
2. The asynchronuous calculation can clash with an OptimisticLockException while the import from SurvNet is still running.

### Proposed Change

Discussed with @MartinWahnschaffe and @HolgerReiseVSys: The completeness value is a calculated value that shall not trigger anymore the changeDate to be updated. This avoids unneeded sync roundtrips towards the reporting tool and the android app.

How: Write the completeness value directly via SQL, not via JPA Entity mechanisms.

### PR DESCRIPTION
**Pull request by StefanKock**
Fixes #6080 

Side effect: Auditlog is not triggered (the same with batch archive/dearchive of cases).

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java [hunk 1]
```diff
@@ -1318,8 +1318,20 @@ public void updateCompleteness(List<String> caseUuids) {
 	}
 
 	public void updateCompleteness(Case caze) {
```
Comment (MartinWahnschaffe) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java:1320]: Please add a comment that this does not trigger the audit log

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java (hunk 1 above)
Comment (StefanKock) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java:1320]: Added in the code comment
