### PR TITLE
#7430 trigger diseaseVariantFieldUpdate when adding fields

### LINKED ISSUE #7430: [DEMIS2SORMAS] Disease variant field and details field are missing when processin lab messages
### Bug Description

The disease variant field and the disease variant details fields are missing when processing lab messages.
### Steps to Reproduce

1. Upload and fetch a lab message
2. Process the lab message
3. The the pathogen tests for the disease variant and disease variant details fields

### Expected Behavior

disease variant and disease variant details fields should be available when processing lab messages
### Screenshots

diseaseVariantFieldMissingDEMIS

### System Details

* Device:
* SORMAS version: 1.66.0
* Android version/Browser: chrome
* Server URL: test1402.sormas.netzlink.com
* User Role: admin, national user

### PR DESCRIPTION
**Pull request by FredrikSchaeferVitagroup**
Fixes #7430

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java [hunk 1]
```diff
@@ -222,13 +222,20 @@ protected void addFields() {
 			Arrays.asList(PathogenTestType.CQ_VALUE_DETECTION),
 			true);
 
-		diseaseField.addValueChangeListener((ValueChangeListener) valueChangeEvent -> {
-			Disease disease = (Disease) valueChangeEvent.getProperty().getValue();
+		Consumer<Disease> updateDiseaseVariantField = disease -> {
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java:225]: Is there a specific reason to have a `Consumer` here instead of a method `PathogenTestForm.updateDiseaseVariantField`?

**Review by syntakker — APPROVED** [review]

**Comment by syntakker** [comment]
Comment https://github.com/hzi-braunschweig/SORMAS-Project/pull/7439#discussion_r762464129 is just a remark. Changes are fine, PR is ready to merge.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java (hunk 1 above)
Comment (FredrikSchaeferVitagroup) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/samples/PathogenTestForm.java:225]: I preferred a Consumer because

- the code fragment is short (only three statements)
- it's just used in one method
- with a consumer, the logic is all in one place
