### PR TITLE
Bugfix 7404 confirm navigation

### LINKED ISSUE #7404: [Immunizations] Case edit page cannot be saved if Vaccination is created and then edited
### Bug Description
If a Vaccination is created, and then edited, the Case edit page cannot be saved.

### Steps to Reproduce

1. Open a Case.
2. Create a Vaccination. 
3. Edit the Vaccination.
4. Save the Case Edit page.

### Actual Behavior
The user gets an error message.

### Expected Behavior
The Case Edit page should be successfully saved.

### Screenshots
image

### System Details

* Device: Windows 10
* SORMAS version: 1.66.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

### Additional Information
#7105

### PR DESCRIPTION
**Pull request by alexcaruntu-vita**
Fixes #7404

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponentField.java [hunk 1]
```diff
@@ -27,4 +32,13 @@ public SideComponentField() {
 	public void addComponentToField(Component component) {
 		mainLayout.addComponent(component);
 	}
+
+	public void adEditButton(String id, Button.ClickListener editClickListener) {
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponentField.java:36]: Typo: `addEditButton`

Comment (syntakker) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/components/sidecomponent/SideComponentField.java]: Additionally, this method moved here from `VaccinationList`. It is also implemented in the following classes derived from `SideComponentField`:
- `TravelEntryListEntry`
- `CaseListEntry`
- `ImmunizationListEntry`
- `ContactListEntry`
The respected methods `addEditListener` can be omitted and `SideComponentField.addEditButton` used instead.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListComponent.java [hunk 2]
```diff
@@ -63,67 +65,63 @@ public VaccinationListComponent(
...
-		boolean showCreateButton,
-		Runnable refreshCallback,
-		Function<Integer, List<VaccinationListEntryDto>> entriesListSupplier) {
+		Function<Integer, List<VaccinationListEntryDto>> entriesListSupplier,
+		AbstractDetailView<? extends ReferenceDto> view) {
 		super(I18nProperties.getString(Strings.entityVaccinations));
 
+		this.view = view;
+
 		VaccinationList vaccinationList = new VaccinationList(criteria.getDisease(), entriesListSupplier);
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/vaccination/list/VaccinationListComponent.java:121]: This code is a duplicate of the code in the first constructor (l.55 ff). Better call this constructor first and call `createNewVaccinationButton` after.

**Review by syntakker — APPROVED** [review]
