### PR TITLE
bug/9350_surv_sup_suer_cannot_be_assigned

### LINKED ISSUE #9350: Admin Surveillance Supervisor and Surveillance Supervisor can not be assigned as CASE_RESPONSIBLE
### Bug Description

Admin Surveillance Supervisor has the CASE_RESPONSIBLE user right = Yes; however, they can not assign themselves or be assigned by other users as 'Responsible Surveillance Officer'.

The Admin Surveillance Supervisor can only be automatically assigned by the system when they create a new case, but if the 'Responsible Surveillance Officer' dropdown is opened and another selection is made, the Admin Surveillance Supervisor is no longer selectable as responsible for the case.

### Steps to Reproduce

I:
1. Log in with an Admin and create a case;
2. Observe the 'Responsible Surveillance Officer' field and its dropdown.
->**Actual Behavior:** The Admin Surveillance Supervisor is not visible in the dropdown.

II:
1. Log in with an Admin Surveillance Supervisor and create a case;
2. Observe the 'Responsible Surveillance Officer' field and its dropdown.
->**Actual behavior:** The Admin Surveillance Supervisor is listed in the field 'Responsible Surveillance Officer'; if the dropdown is opened, or another selection is made, the Admin Surveillance Supervisor is not visible in the list.

### Expected Behavior

The Admin Surveillance Supervisor can be selected as the 'Responsible Surveillance Officer' for cases that are within their jurisdiction.

### System Details

* Device: Windows 10
* SORMAS version: 1.73.0-SNAPSHOT(7bff1b7) and 1.72.1.
* Android version/Browser: Chrome
* Server URL: local machine and release-international.sormas.netzlink.com
* User Role: Admin Surveillance Supervisor

### Additional Information

Reproducible for Surveillance Supervisor as well.

### PR DESCRIPTION
**Pull request by dinua**
Fixes #9350

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java [hunk 1]
```diff
@@ -268,7 +268,13 @@ public List<UserReference> getUserReferences(
...
 		if (CollectionUtils.isNotEmpty(districtUuids)) {
 			Join<User, District> districtJoin = userRoot.join(User.DISTRICT, JoinType.LEFT);
-			filter = CriteriaBuilderHelper.and(cb, filter, cb.in(districtJoin.get(AbstractDomainObject.UUID)).value(districtUuids));
+			Join<User, Region> userRegionJoin = userRoot.join(User.REGION, JoinType.LEFT);
+			Join<Region, District> districtRegionJoin = userRegionJoin.join(Region.DISTRICTS, JoinType.LEFT);
+
+			Predicate districtFilter = cb.or(cb.in(districtJoin.get(AbstractDomainObject.UUID)).value(districtUuids),
+					cb.in(districtRegionJoin.get(AbstractDomainObject.UUID)).value(districtUuids));
+
+			filter = CriteriaBuilderHelper.and(cb, filter, districtFilter);
```
Comment (sergiupacurariu) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java:277]: the update of the filter adds the users from all the districts in the region of the case which is incorrect; the "responsible surveillance officer" dropdown should contain only users from the case district or users that have the same region jurisdiction as the case

**Review by sergiupacurariu — APPROVED** [review]

**Review by sergiupacurariu — APPROVED** [review]
