### PR TITLE
#10156 - Clear recovery dates when hidden

### LINKED ISSUE #10156: Information related to the 'Recovery' section of an immunization is not cleared
### Bug Description

If the 'Means of immunization' for an immunization are updated, and the 'Recovery' section is no longer displayed, the information that was related to the 'Recovery' section is stored  and is displayed again (if the 'Means of immunization' is updated again).

### Steps to Reproduce

1. Create an immunization with the 'Means of immunization' set to 'Recovery';
2. On the immunization's page, in the 'Recovery' section fill in the information for: 'Date of first positive test result' and 'Date of recovery';
3. Save the changes;
4. Navigate to the main list of immunizations and observe the column 'Date of Recovery';
-> it is populated with the date set at step 2.
5. Navigate back to the immunization's page, and update the 'Means of immunization' to 'Vaccination';
6. Navigate back to the main list of immunizations and observe the column 'Date of recovery';
-> it is still populated with the date that was set at step 2.
7. Navigate again to the immunization's page and change the 'Means of immunization' to 'Recovery';
8. Observe the 'Recovery' section.

### Actual Behavior

The information that was inputted in the section 'Recovery' of the immunization remains stored and it is displayed both on the immunization's page and in the main list of immunizations - column - 'Date of recovery'.

### Expected Behavior

The information that was inputted in the section 'Recovery' of the immunization should be cleared (both on the immunization page and in the main list of immunizations - column 'Date of recovery') when the 'Means of immunization' is updated and the page no longer displays the section ''Recovery'.

### Screenshots

GIF of the steps to reproduce:
Recovery

### System Details

* Device: Windows 10
* SORMAS version: 1.75.0-SNAPSHOT(5663e12)
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin+NatUser

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #10156

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java [hunk 1]
```diff
@@ -369,6 +369,11 @@ protected void onCancel() {
 			recoveryHeadingLabel.setVisible(isRecoveryVisible);
 			positiveTestResultDate.setVisible(isRecoveryVisible);
 			recoveryDate.setVisible(isRecoveryVisible);
+
```
Comment (syntakker) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/immunization/components/form/ImmunizationDataForm.java:372]: Same problem occurs for vaccination related field "number of doses".
Better use `FieldHelper.setVisbleWhen` with `clearOnHidden = true`.

**Review by syntakker — CHANGES_REQUESTED** [review]

**Review by syntakker — APPROVED** [review]
