### PR TITLE
fix android tests #6714

### LINKED ISSUE #6714: Fix failing AndroidTests
### Bug Description
A number of android tests fail
androidTests2
androidTests1

Some of the tests do not reflect the current state of the implementation:
- `CaseBackendTest..shouldUpdateCaseAndAssociatedEntitiesOnMove()` manipulates `Case.district`. However, task reassignment is triggered by a change of `Case.responsibleDistrict` or - if `responsibleDistrict` is null, which is not the case here - by a change of `district`. Thus, neither assignment of a new `surveillanceOfficer` nor a reassignment of tasks occur in the course of the test. Equallly, hospitalizations are not updated as expected in the test.

Some of the tests fail depending of other tests run before:
- `CaseBackendTest.shouldCreateCase()` succeeds in the first run with no tests run before, but fails in a second run.

### Steps to Reproduce

Run android tests in android studio, either one by one or all together

### Expected Behavior
Android tests should succeed, test result should be independent of other tests run  before.
Database and other persistent states should be cleaned and prepared before each test.

### System Details

* Device:
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser:
* Server URL:
* User Role:

### PR DESCRIPTION
**Pull request by syntakker**
Fixes #6714

To the reviewer: This fix affects a number of processes in SORMAS. Please have a close eye on possible alterations of processes and double check if implementation and test expectations still meet the intended behaviour.

### CODE REVIEW

File: sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java [hunk 1]
```diff
@@ -272,9 +274,14 @@ public void shouldUpdateCaseAndAssociatedEntitiesOnMove() throws DaoException {
 		Task doneTask = TestEntityCreator.createCaseTask(caze, TaskStatus.DONE, user);
 
 		Case existingCase = caseDao.queryUuidWithEmbedded(caze.getUuid());
-		caze.setDistrict(DatabaseHelper.getDistrictDao().queryUuid(TestHelper.SECOND_DISTRICT_UUID));
-		caze.setCommunity(DatabaseHelper.getCommunityDao().queryUuid(TestHelper.SECOND_COMMUNITY_UUID));
+		District secondDistrict = DatabaseHelper.getDistrictDao().queryUuid(TestHelper.SECOND_DISTRICT_UUID);
```
Comment (MartinWahnschaffe) [inline sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java:277]: I'd suggest to only set the responsible... instead of both.

This means that we also have to fix the TestEntityCreator.createCase() method to assign responsible... instead of the old infrastructure region,district,community fields that are only relevant when the home/place of stay differs from the responsible region/district/community.

File: sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java [hunk 2]
```diff
@@ -420,19 +427,23 @@ public void testEditCasePermissionWhenRegionMatch() throws DaoException, SQLExce
 	}
 
 	@Test
-	public void testEditCasePermissionWhenRegionDoesNotMatchAndCaseNotCreatedByUser() throws DaoException, SQLException {
+	public void testEditCasePermissionWhenDistrictDoesNotMatchAndCaseNotCreatedByUser() throws DaoException, SQLException {
 		Case caze = TestEntityCreator.createCase();
-		caze.setRegion(null);
-		caze.setDistrict(null);
+		caze.setRegion(DatabaseHelper.getRegionDao().queryUuid(TestHelper.REGION_UUID));
```
Comment (MartinWahnschaffe) [inline sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java:432]: No need to set this again

File: sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java [hunk 3]
```diff
@@ -420,19 +427,23 @@ public void testEditCasePermissionWhenRegionMatch() throws DaoException, SQLExce
...
+		District secondDistrict = DatabaseHelper.getDistrictDao().queryUuid(TestHelper.SECOND_DISTRICT_UUID);
+		caze.setDistrict(secondDistrict);
+		caze.setResponsibleDistrict(secondDistrict);
 		caze.setHealthFacility(null);
 
-		UserRole userRole = UserRole.HOSPITAL_INFORMANT;
```
Comment (MartinWahnschaffe) [inline sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java:429]: Not sure why it's necessary to switch this - should also work with the HOSPITAL_INFORMANT

File: sormas-app/app/src/androidTest/java/de/symeda/sormas/app/FacilityBackendTest.java [hunk 4]
```diff
@@ -45,16 +52,45 @@ public void initTest() {
...
-			DatabaseHelper.getFacilityDao().getActiveHealthFacilitiesByDistrictAndType(district, FacilityType.HOSPITAL, true, true).size(),
-			is(3));
+			DatabaseHelper.getFacilityDao().getActiveHealthFacilitiesByDistrictAndType(district, FacilityType.HOSPITAL, false, false).size(),
+			is(1));
+
+		List<Facility> activeHealthFacilitiesByDistrictAndType =
+			DatabaseHelper.getFacilityDao().getActiveHealthFacilitiesByDistrictAndType(district, null, true, true);
+		assertThat(activeHealthFacilitiesByDistrictAndType.size(), is(2));
+
+		Facility otherFacility = new Facility();
```
Comment (MartinWahnschaffe) [inline sormas-app/app/src/androidTest/java/de/symeda/sormas/app/FacilityBackendTest.java:72]: Please move the creation of OTHER/NONE facilities into a new method in TestHelper that is called by TestHelper.insertInfrastructureData. To be realistic, we should always have those available.

I'd like to have one additional assertion that tests (district, FacilityType.HOSPITAL, true, true) -> should be 3

File: sormas-app/app/src/androidTest/java/de/symeda/sormas/app/TestHelper.java [hunk 5]
```diff
@@ -53,9 +53,10 @@
 
 	public static void initTestEnvironment(boolean setInformantAsActiveUser) {
 		// Initialize a testing context to not operate on the actual database
-		RenamingDelegatingContext context = new RenamingDelegatingContext(InstrumentationRegistry.getTargetContext(), "test_");
+		Context context = InstrumentationRegistry.getInstrumentation().getTargetContext();
```
Comment (MartinWahnschaffe) [inline sormas-app/app/src/androidTest/java/de/symeda/sormas/app/TestHelper.java:56]: This will always use the existing db on the emulator and afterwards delete it. Would be good to somehow wrap this to use another database location.

Comment (MartinWahnschaffe) [reply sormas-app/app/src/androidTest/java/de/symeda/sormas/app/TestHelper.java:56]: In the worst case we could mock DatabaseHelper.DATABASE_NAME to provide a different name when testing,

**Review by MartinWahnschaffe — CHANGES_REQUESTED** [review]

File: sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java (hunk 2 above)
Comment (syntakker) [reply sormas-app/app/src/androidTest/java/de/symeda/sormas/app/CaseBackendTest.java]: removed.

File: sormas-app/app/src/androidTest/java/de/symeda/sormas/app/TestHelper.java (hunk 5 above)
Comment (syntakker) [reply sormas-app/app/src/androidTest/java/de/symeda/sormas/app/TestHelper.java:57]: DatabaseHelper is used with a prefixed test database now.

File: sormas-app/app/src/androidTest/java/de/symeda/sormas/app/FacilityBackendTest.java (hunk 4 above)
Comment (syntakker) [reply sormas-app/app/src/androidTest/java/de/symeda/sormas/app/FacilityBackendTest.java]: done.
