### PR TITLE
#10517 Facility is not pre-filled

### LINKED ISSUE #10517: Facility is not pre-filled for users with an optional health facility
### Bug Description

When the checkbox " Has optional health facility" is checked and the user is related to a certain health faciliy this health facility should be prefilled when the user is for example creating a new case.
### Steps to Reproduce

1.create a new user role
2. check the checkbox "Has optional health facility"
3. create a new user
4. link the user to the created user role and the facility
5.create a case

### Expected Behavior

facility should be prefilled
### Screenshots

image

### System Details

* Device:
* SORMAS version: 1.75.2
* Android version/Browser:
* Server URL: test1402
* User Role: admin

### PR DESCRIPTION
**Pull request by valentinmikleuvg**
Added a certain health facility when a user with optional health facility permission created a new case

Fixes #10517

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java [hunk 1]
```diff
@@ -332,31 +332,46 @@ protected void addFields() {
...
-				}
 
-				if (facilityType.getValue() != null) {
-					updateFacility();
-				}
+			boolean hasOptionalHealthFacility = UserProvider.getCurrent().hasOptionalHealthFacility();
+			if (hasOptionalHealthFacility) {
+				String facilityId = UserProvider.getCurrent().getUser().getHealthFacility().getUuid();
+				FacilityDto facilityDto = FacadeProvider.getFacilityFacade().getByUuid(facilityId);
+				FacilityType facilityUserType = facilityDto.getType();
```
Comment (carina29) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseCreateForm.java:340]: I've also tested another case , changing a Surveillance Officer user role and checking the  "Has optional health facility" checkbox but after logging in with Surveillance Officer user , the same error appeared due to null healthFacility. 
image

image


image

**Review by carina29 — CHANGES_REQUESTED** [review]

**Review by carina29 — APPROVED** [review]
