### PR TITLE
Bug/8017 disease users can be associated to entities related to other diseases

### LINKED ISSUE #8017: Limited disease users can be associated to entities related to other diseases
### Bug Description
A limited disease User (ex. Dengue Fever) can be associated to an entity with a different disease (ex. a task related to a Covid-19 Case).
This issue applies to:
- [ ] 'Assigned to' users (Tasks)
- [ ] 'Observed by' users (Tasks)
- [ ] Responsible users

### Steps to Reproduce

1. Create at least one limited disease User for a disease other than 'Covid-19'
2. Create a Case with 'Covid-19' set as 'Disease'.
3. Click on 'New Task'.
4. Inspect the 'Assigned to' dropdown in the Task form.
5. Inspect the 'Observed by' dropdown in the Task form.
6. Inspect the 'Responsible Surveillance Supervisor' dropdown on Case page.

### Actual Behavior
The limited disease users (Dengue Fever) are visible in the dropdown, even if the Case has Covid-19 as disease.

### Expected Behavior
The limited disease users should not be visible in the dropdown if they have other disease associated to them.

### Screenshots
image

image

image

image

### System Details

* Device: Windows 10
* SORMAS version: 1.69.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: local machine
* User Role: Admin, National User

### Additional Information

### PR DESCRIPTION
**Pull request by dinua**
Fixes #8017

### CODE REVIEW

**Comment by MateStrysewske** [comment]
@dinua Please make sure to connect your PRs with the respective issue by adding the issue number to the PR description (so, in this case, it would be "Fixes #8017") - this way, the automation will make sure that when a PR is merged, the connected issue is closed and automatically moved to the Testing lane. :)

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java [hunk 1]
```diff
@@ -592,11 +592,11 @@ private void updateResponsibleUserFieldItems() {
 	private void updateResponsibleUserFieldItems(DistrictReferenceDto district, RegionReferenceDto region) {
 		final List<UserReferenceDto> items = new ArrayList<>();
 		if (district != null) {
-			items.addAll(FacadeProvider.getUserFacade().getUserRefsByDistrict(district, false, UserRole.SURVEILLANCE_OFFICER));
-			items.addAll(FacadeProvider.getUserFacade().getUsersByRegionAndRoles(region, UserRole.SURVEILLANCE_SUPERVISOR));
+			items.addAll(FacadeProvider.getUserFacade().getUserRefsByDistrict(district, false, null, UserRole.SURVEILLANCE_OFFICER));
+			items.addAll(FacadeProvider.getUserFacade().getUsersByRegionAndRoles(region, null, UserRole.SURVEILLANCE_SUPERVISOR));
```
Comment (sergiupacurariu) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java:596]: how ResponsibleUser filter will work on events since we know that on an event the disease is not mandatory

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java [hunk 2]
```diff
@@ -592,11 +592,11 @@ private void updateResponsibleUserFieldItems() {
...
 		} else {
 			items.addAll(
-				FacadeProvider.getUserFacade().getUsersByRegionAndRoles(region, UserRole.SURVEILLANCE_SUPERVISOR, UserRole.SURVEILLANCE_OFFICER));
+				FacadeProvider.getUserFacade().getUsersByRegionAndRoles(region, null, UserRole.SURVEILLANCE_SUPERVISOR, UserRole.SURVEILLANCE_OFFICER));
```
Comment (sergiupacurariu) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventsFilterForm.java:599]: same here: how Responsible User filter will work?

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/BulkCaseDataForm.java [hunk 3]
```diff
@@ -206,8 +207,18 @@ protected void addFields() {
 				Arrays.asList(CaseBulkEditData.SURVEILLANCE_OFFICER),
 				Arrays.asList(true),
 				null);
-			List<UserReferenceDto> assignableCaseResponsibles =
-				FacadeProvider.getUserFacade().getUserRefsByDistrict(singleSelectedDistrict, UserRight.CASE_RESPONSIBLE);
+			List<Disease> selectedDiseases = this.selectedCases.stream().map(c -> c.getDisease()).collect(Collectors.toList());
+			List<UserReferenceDto> assignableCaseResponsibles = null;
+
+			if (selectedDiseases.size() == 1) {
```
Comment (sergiupacurariu) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/BulkCaseDataForm.java:213]: please review this logic, it does not seem to work when multiple cases having the same disease are selected

**Review by sergiupacurariu — CHANGES_REQUESTED** [review]
