### PR TITLE
#10803 reinfection related checkboxes on case page remain unchecked

### LINKED ISSUE #10803: [Cases - Reinfection] Reinfection related checkboxes on case page remain unchecked when the user discards their changes
### Bug Description

On a case page, the checkboxes related to reinfection get cleared even if the user clicked discard changes.

### Steps to Reproduce

1. Open a case and select 'Yes' in the 'Reinfection' section;
2. Check a couple of the checkboxes related to reinfection and set 'Previous infection date';
3. Click 'Save' at the bottom of the page;
4. Then click either 'No' or 'Unknown' in the 'Reinfection' section;
5. Then click 'Discard' at the bottom of the page.

### Actual Behavior
 
The 'Reinfection status' and 'Previous infection date' values have remained saved. The checkboxes associated with reinfection were cleared.

### Expected Behavior

The checkboxes associated with reinfection are not cleared if the user did not save the changes made on the page at step 4.

### Screenshots

GIF of the behavior:
Reinfection

### System Details

* Device: Windows 10
* SORMAS version: 1.77.0-SNAPSHOT(9d301af); 1.76.0
* Android version/Browser: Chrome
* Server URL: local machine, https://test1402.sormas.netzlink.com/
* User Role: Admin+NatUser

### PR DESCRIPTION
**Pull request by valentinmikleuvg**
The checkboxes associated with reinfection are cleared only if the user save the changes made.

Fixes #10803

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java [hunk 1]
```diff
@@ -530,6 +530,12 @@ private CaseDataDto findCase(String uuid) {
 
 	protected CaseDataDto saveCase(CaseDataDto cazeDto) {
 
+		if (cazeDto.getReInfection() == YesNoUnknown.NO || cazeDto.getReInfection() == YesNoUnknown.UNKNOWN) {
```
Comment (carina29) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseController.java:533]: Can be checked directly if cazeDto.getReInfection() != YesNoUnknown.Yes instead of the above 2 conditions

**Review by carina29 — CHANGES_REQUESTED** [review]

**Comment by carina29** [comment]
I also tested the PR and everything works as it was requested :) After solving the added comment, we can merge it :)

**Review by carina29 — APPROVED** [review]

**Comment by StefanKock** [comment]
The ticket was not linked in the commit, that's against the rules (it's already merged, so too late).

**Comment by carina29** [comment]
@StefanKock  Ah yes, good point I did not see it till now.
@valentinmikleuvg You have to add the number of the ticket in the commit message too 
image

**Comment by StefanKock** [comment]
For next time

**Comment by valentinmikleuvg** [comment]
Sorry for this, I will link the ticket next time
