### PR TITLE
#10631 Disable the creation buttons if missing rights

### LINKED ISSUE #10631: Hide "NEW ..." buttons if the right to create is not selected
### Bug Description

Although the user does not have permission to create a prescription, treatment or clinical assessment the buttons are displayed. 
Nwe-Button

image

### Steps to Reproduce

1.   Create a user role without the rights to create or edit  prescription, treatment or clinical assessment 
2.   Assign it to a user  and login with this user
 

### Expected Behavior

Please hide the buttons. 

### System Details

* Device: Laptop
* SORMAS version: 1.75.4
* Android version/Browser: Chrome
* Server URL:   release-international.sormas.netzlink.com     -     On the previously mentioned test1401 the functions will be disabled via Feature Configuration.  
* User Role: Admin and individual role

### PR DESCRIPTION
**Pull request by andrei7bal**
- if user doesn't have rights to create Prescription, Treatment or Clinical Assessment, then the buttons are disabled
- hide the Create Treatement button from Prescription Grid if missing rights

Fixes #10631

### CODE REVIEW

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Hey! Please use brackets in your if conditions in order to adhere to the codestyle guidelines. Apart from that, the code looks fine. I agree with being consistent with the rest of the app, i.e. disabling the buttons instead of hiding them.

File: sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/PrescriptionGrid.java [hunk 1]
```diff
@@ -90,6 +90,9 @@ public Class<String> getType() {
 
 		getColumn(DOCUMENT_TREATMENT_BTN_ID).setHidden(isPseudonymized || !isEditAllowed);
 
+		if (!UserProvider.getCurrent().hasUserRight(UserRight.TREATMENT_CREATE)) {
```
Comment (MateStrysewske) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/PrescriptionGrid.java:93]: You can integrate this statement into the code in line 91, i.e. (isPseudonymized || !isEditAllowed || !UserProvider.getCurrent().hasUserRight(UserRight.TREATMENT_CREATE))

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

File: sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/PrescriptionGrid.java (hunk 1 above)
Comment (andrei7bal) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/therapy/PrescriptionGrid.java]: Done

**Review by MateStrysewske — APPROVED** [review]
