### PR TITLE
#7849 - Make date filter work for events without date

### LINKED ISSUE #7849: [Events] System crashes when user tries to filter the events in the table during select a subordinate event flow
### Bug Description
When the user has an event without a 'Date of Event' and goes through the select a subordinate event flow, if he filters the events in the events table by Date or by Epi Week, when he clicks on 'Date of event from epi week', the system crashes, throwing a message stating that 'An unexpected error occurred'

### Steps to Reproduce

1. Open or create an event that has no 'Date of Event', only 'Report Date'
2. Click on 'Link Event' in the 'Subordinate Events' card.
3. Filter the events by 'Date of event from epi week'

### Actual Behavior
When selecting the Epi Week or the date, an error occurs stating that 'An unexpected error occurred'

### Expected Behavior
No system crash error should appear.

### Screenshots
image

### System Details

* Device: Windows 10
* SORMAS version: 1.68.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de1.sormas.netzlink.com
* User Role: NatUser

### Additional Information

This is also reproductible when linking an superordinate event and selecting the '...to epi week'

### PR DESCRIPTION
**Pull request by alexcaruntu-vita**
Fixes #7849

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventLink/EventSelectionField.java [hunk 1]
```diff
@@ -183,8 +182,11 @@ private static void prepareSubordinateFilters(
 		EventSelectionField eventSelectionField,
 		Date selectedFromDate,
 		AbstractComponent component) {
-		boolean isSelectedDateBeforeEventDate =
-			selectedFromDate == null || selectedFromDate.after(EventHelper.getStartOrEndDate(eventDto.getStartDate(), eventDto.getEndDate()));
+		boolean isSelectedDateBeforeEventDate = true;
+		Date startOfEndEventDate = EventHelper.getStartOrEndDate(eventDto.getStartDate(), eventDto.getEndDate());
```
Comment (MateStrysewske) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/events/eventLink/EventSelectionField.java:186]:
```suggestion
		Date eventStartOrEndDate = EventHelper.getStartOrEndDate(eventDto.getStartDate(), eventDto.getEndDate());
```

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
The same bug appears when trying to link a superordinate event, can you fix it there as well? :)

**Review by MateStrysewske — APPROVED** [review]
