### PR TITLE
Change 7423 vac migration no relevance date

### LINKED ISSUE #7423: Vaccinations migration does not set everything as expected
### Bug Description

- When two vaccine doses are entered but only the `lastVaccinationDate` was collected, the first vaccination has a date of vaccination entered even though it was never collected. This might also happen if the `vaccineDoses` > 1 and either `firstVaccinationDate` or `lastVaccinationDate` is missing
### Steps to Reproduce

1. Create entities as mentioned in the "created entities file" on version 1.63.1
2. Update from version 1.63.1 to version 1.66.0

### Expected Behavior

- The vaccination should not have a vaccination date after migration if it wasn't collected
### System Details

* Device:
* SORMAS version: 1.63.1 > 1.66.0
* Android version/Browser:  chrome
* Server URL: survnet-import-test.sormas.netzlink.com
* User Role: admin, national user

### Additional Information

created entities (as custom export with relevant fields):
[vaccination_migration_test_211201 (1).csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7650210/vaccination_migration_test_211201.1.csv)

failed tests and actual results:
[vaccination_migration_test_211202_findings.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7650204/vaccination_migration_test_211202_findings.csv)

vaccination db table:
[vaccination_migration_test_211202_findings_dbVaccinations.csv](https://github.com/hzi-braunschweig/SORMAS-Project/files/7650223/vaccination_migration_test_211202_findings_dbVaccinations.csv)

### Development Specifications
What this means is that we have to remove the fallback to the relevance date from each piece of migration code where we use it to fill the vaccination date (e.g. every coalesce from first vaccination date OR last vaccination date to relevance date). This includes the new logic that updates the vaccination date of the first vaccination of a person (e.g. `sormas_schema.sql::8175` and its equivalent in the Android app). 

The fallback from last vaccination date to first vaccination date for vaccinations where number of doses == 1 can remain (because that makes sense).

**Make sure to test this, also for the Android app!** In the Android app, you'll need to set up a new backend database, check out version 1.63.1, start your server, connect your mobile app to it and log in; afterwards set your device to flight mode, create data that allows you to test these changes, THEN check out your branch where you did these changes again, restart your server, restart your mobile app (so that the database migration is executed), turn off flight mode, and synchronize with the server. The reason is that the Android app only migrates new data that hasn't been sent to the backend yet.

### PR DESCRIPTION
**Pull request by BarnaBartha**
Fixes #7423

### CODE REVIEW

File: sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java [hunk 1]
```diff
@@ -3046,16 +3046,42 @@ private void migrateVaccinationInfo() throws SQLException {
...
+			final List<Object[]> objectList = caseInfoByDisease.get(Disease.valueOf((String) objects[2]));
+			/* set earliest report date */
+				objectList
 					.stream()
 					.sorted(comparator.reversed())
 					.findFirst()
 					.ifPresent(earliestObject -> {
 						if (earliestObject[12] != null && objects[12] != null && (int) earliestObject[12] <= (int) objects[12]) {
-							objects[10] = earliestObject[10] == null ? earliestObject[4] : earliestObject[10];
+							objects[10] = earliestObject[10];
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java:3058]: Shouldn't the report date be set here instead of the first vaccination date?

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Review by MateStrysewske — APPROVED** [review]
