### PR TITLE
#9274-notice survnet about cases/events archivation/dearchivation

### LINKED ISSUE #9274: Report automatically when a case or an event was archived to the reporting system (SurvNet) the status "abgeschlossen"
### Situation Description
Currently SurvNet is not automatically informed, when a case or an event was archived in SORMAS.
As this might lead to wrong numbers in the reporting system, we would need to inform Survnet about the status.
As we did when a case was deceased, we need to do it automatically, when a case or an event was archived.

### Feature Description
With different events, we need to trigger automatically the SurvNet Converter to generate a transportfile, which can be read and imported in SurvNet
- archiving cases
- archiving events

Single archiving and bulk archiving for cases and events should be considered.

=> Should only be executed when the SurvNet Interface is configured

### Additional Information
SurvNet Interface Issue: https://github.com/hzi-braunschweig/sormas-survnet-interface/issues/309

### PR DESCRIPTION
**Pull request by carina29**
…d/dearchived

Fixes #9274

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ArchivingController.java [hunk 1]
```diff
@@ -53,13 +53,13 @@ public void archiveEntity(EntityDto coreEntityDto, F entityFacade, CoreEntityArc
...
 					doArchive(entityFacade, coreEntityDto.getUuid(), DateHelper8.toDate(endOfProcessingDate.getValue()));
-
 					Notification.show(
 						String.format(
 							I18nProperties.getString(archiveMessages.getMessageEntityArchived()),
 							I18nProperties.getString(archiveMessages.getEntityName())),
 						Notification.Type.ASSISTIVE_NOTIFICATION);
-					callback.run();
+
+                    callback.run();
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ArchivingController.java:62]: please reformat the code

File: sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoService.java [hunk 2]
```diff
@@ -169,6 +188,29 @@ public List<ExternalShareInfoCountAndLatestDate> getShareCountAndLatestDate(List
...
+		Subquery<Integer> survToolShareSubQuery = cq.subquery(Integer.class);
+		Root<ExternalShareInfo> survToolShareRoot = survToolShareSubQuery.from(ExternalShareInfo.class);
+		survToolShareSubQuery.select(survToolShareRoot.get(associatedObjectName));
+		Predicate deletedFilter = cb.equal(survToolShareRoot.get(ExternalShareInfo.STATUS), ExternalShareStatus.DELETED);
+		survToolShareSubQuery.where(deletedFilter);
+
+		Predicate entityUuidsFilter = associatedObjectJoin.get(AbstractDomainObject.UUID).in(entityUuids);
+
+		Predicate filter =
+			CriteriaBuilderHelper.and(cb, entityUuidsFilter, associatedObjectJoin.get(AbstractDomainObject.ID).in(survToolShareSubQuery).not());
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/share/ExternalShareInfoService.java:207]: please move the `.not()` before `.in(survToolShareSubQuery)`. it's confusing

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 3]
```diff
@@ -2575,6 +2577,36 @@ public void dearchive(List<String> entityUuids, String dearchiveReason, boolean
 		}
 	}
 
+	@Override
+	@RolesAllowed(UserRight._CASE_ARCHIVE)
+	public void setArchiveInExternalSurveillanceToolForEntity(String entityUuid, boolean archived) throws ExternalSurveillanceToolException {
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:2582]: these methods should be moved to the service

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java [hunk 4]
```diff
@@ -2575,6 +2577,36 @@ public void dearchive(List<String> entityUuids, String dearchiveReason, boolean
...
+	@Override
+	@RolesAllowed(UserRight._CASE_ARCHIVE)
+	public void setArchiveInExternalSurveillanceToolForEntities(List<String> entityUuids, boolean archived) throws ExternalSurveillanceToolException {
+		if (externalSurveillanceToolGatewayFacade.isFeatureEnabled()) {
+			List<String> filteredEntityUuids = externalShareInfoService.getSharedCaseUuidsWithoutDeletedStatus(entityUuids);
+			externalSurveillanceToolGatewayFacade.sendCases(filteredEntityUuids, archived);
+		}
+	}
+
+	public boolean hasExternalId(String entityUuid) {
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java:2605]: I think this can be removed

File: sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java [hunk 5]
```diff
@@ -914,6 +918,31 @@ public void dearchive(List<String> eventUuids, String dearchiveReason) {
 		eventParticipantService.dearchive(eventParticipantList, dearchiveReason);
 	}
 
+	@Override
+	@RolesAllowed(UserRight._EVENT_ARCHIVE)
+	public void setArchiveInExternalSurveillanceToolForEntity(String eventUuid, boolean archived) throws ExternalSurveillanceToolException {
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java:923]: these methods should be moved to the service

**Review by leventegal-she — CHANGES_REQUESTED** [review]

**Comment by carina29** [comment]
The requested changes were committed.

File: sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java [hunk 6]
```diff
@@ -203,6 +205,8 @@ public class CaseService extends AbstractCoreAdoService<Case> {
 	private SurveillanceReportService surveillanceReportService;
 	@EJB
 	private DocumentService documentService;
+    @EJB
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java:208]: formatting issue

File: sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java [hunk 7]
```diff
@@ -160,6 +162,8 @@ public class EventFacadeEjb extends AbstractCoreFacadeEjb<Event, EventDto, Event
 	private SormasToSormasEventFacadeEjbLocal sormasToSormasEventFacade;
 	@EJB
 	private EventParticipantService eventParticipantService;
+	@EJB
+	private EventService eventService;
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventFacadeEjb.java:166]: seems it's not used so it can be removed, pleas also remove unused imports

File: sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java [hunk 8]
```diff
@@ -111,6 +115,10 @@ public class EventService extends AbstractCoreAdoService<Event> {
 	private SormasToSormasShareInfoService sormasToSormasShareInfoService;
 	@EJB
 	private ExternalShareInfoService externalShareInfoService;
+    @EJB
+    private EventFacadeEjb.EventFacadeEjbLocal eventFacade;
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/event/EventService.java:119]: formatting issue

File: sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java [hunk 9]
```diff
@@ -65,19 +66,31 @@ public boolean isFeatureEnabled() {
 	}
 
 	@Override
-	public void sendCases(List<String> caseUuids) throws ExternalSurveillanceToolException {
-		ExportParameters params = new ExportParameters();
-		params.setCaseUuids(caseUuids);
+	public void sendCases(List<String> caseUuids, boolean archived) throws ExternalSurveillanceToolException {
```
Comment (leventegal-she) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/externalsurveillancetool/ExternalSurveillanceToolGatewayFacadeEjb.java:69]: formatting issue

**Review by leventegal-she — CHANGES_REQUESTED** [review]
PLease reformat the changed classes and remove unused imports and fields

**Review by leventegal-she — APPROVED** [review]
