### PR TITLE
Bugfix 7471 place of stay home not set randomly

### LINKED ISSUE #7471: Place of stay "home" not set randomly on New Case creation
### Bug Description

When 
- creating a new case 
- the Place of Stay is set to "home"
- eventually a case will be created without Place of Stay. The case cannot be edited nor synced anymore.

### Steps to Reproduce

1. Create a case, choose "home" for place of stay
2. Enter mandatory data
3. Save the case
4. After around 10 attempts a case without a Facility will be saved
5. This case will not be accessible anymore and also could not be synced

### Expected Behavior

Place of stay should be saved correctly

### System Details

* Device: Android
* SORMAS version: 1.67.0
* Android version/Browser: API level 29
* Server URL: local
* User Role: Surveillance Officer

### PR DESCRIPTION
**Pull request by sergiupacurariu**
Fixes #7471

### CODE REVIEW

File: sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java [hunk 1]
```diff
@@ -249,6 +251,10 @@ public void onLayoutBinding(FragmentCaseNewLayoutBinding contentBinding) {
 			if (e.getValue() == TypeOfPlace.FACILITY) {
 				contentBinding.facilityTypeGroup.setValue(FacilityTypeGroup.MEDICAL_FACILITY);
 				contentBinding.caseDataFacilityType.setValue(FacilityType.HOSPITAL);
+				User user = ConfigProvider.getUser();
+				if (!user.hasUserRole(UserRole.HOSPITAL_INFORMANT)) {
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java:255]: Instead of checking the role, please check the user's jurisdiction level (which should be facility); that's more future-proof since we'll get rid of default user roles at some point

File: sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java [hunk 2]
```diff
@@ -653,7 +653,9 @@ public void onAfterLayoutBinding(final FragmentCaseEditLayoutBinding contentBind
 			contentBinding.facilityOrHome.setValue(TypeOfPlace.HOME);
 		} else {
 			contentBinding.facilityOrHome.setValue(TypeOfPlace.FACILITY);
-			contentBinding.facilityTypeGroup.setValue(record.getFacilityType().getFacilityTypeGroup());
+			if (record.getFacilityType()!=null){
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditFragment.java:656]: Please auto-format this file

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

File: sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java (hunk 1 above)
Comment (sergiupacurariu) [reply sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseNewFragment.java:255]: done

**Review by MateStrysewske — APPROVED** [review]
