### PR TITLE
#7163 - Use distinct when counting search results for contacts

### LINKED ISSUE #7163: Filtering for contacts from other jurisdictions leads to endless loading
### Bug Description

When searching the contact directory via the free text search field and subsequently filtering for contacts from other jurisdiction, the page loads endlessly
### Steps to Reproduce

1. Go to the contact directory
2. Seacrh for e.g. a name and apply filter
3. Expand more filters and filter for contacts from other jurisdictions

### Expected Behavior

Filtering should work in a reasonable amount of time

### Screenshots

otherJurisdictionFilter

### System Details

* Device:
* SORMAS version: 1.64.1
* Android version/Browser: chrome
* Server URL: test1401.sormas-oegd.de
* User Role: Surveillance Superviros, Contact Supervisor

### PR DESCRIPTION
**Pull request by alexcaruntu-vita**
Fixes #7163

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java [hunk 1]
```diff
@@ -995,6 +995,7 @@ public long count(ContactCriteria contactCriteria) {
 		}
 
 		cq.select(cb.count(root));
+		cq.distinct(true);
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactFacadeEjb.java:998]: I don't think that's gonna work; please check CaseFacadeEjb.count, you should do a countDistinct instead

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Review by MateStrysewske — APPROVED** [review]
