### PR TITLE
#8312 - fix duplication of automatic message on contact merge

### LINKED ISSUE #8312: [Contacts] 'Follow-up status comment' content is duplicated when merging contacts that have resulting cases
### Bug Description

The 'Follow-up status comment' content is duplicated in the preserved contact, when 2 duplicate contacts are merged, if one or both of them have a resulting case.

### Steps to Reproduce

1. Create 2 contacts with identical information ('Contact1' and 'Contact2') and set the same 'Source Case' for them;
2. Create a resulting case for 'Contact1';
3. Merge 'Contact 1' into 'Contact2';
4. Observe the 'Follow-up status comment' of the preserved contact ('Contact2').

### Actual Behavior

The 'Follow-up status comment' content is duplicated.

### Expected Behavior

The 'Follow-up status comment' content is not duplicated.

### Screenshots

image

GIF of the behavior:
Follow-up comment contact

### System Details

* Device: Windows 10
* SORMAS version: 1.70.0-SNAPSHOT(83ee062)
* Android version/Browser: Chrome
* Server URL: local machine and test-de2.sormas.netzlink.com
* User Role: Admin, NatUser

### PR DESCRIPTION
**Pull request by BarnaBartha**
Fixes #8312

### CODE REVIEW

File: sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java [hunk 1]
```diff
@@ -1440,6 +1440,79 @@ public void testGetContactsByPersonUuids() {
...
+
+		// 2. Merge
+
+		getContactFacade().mergeContact(leadContact.getUuid(), otherContact.getUuid());
+
+		// 3. Test
+
+		ContactDto mergedContact = getContactFacade().getByUuid(leadContact.getUuid());
+
+		assertEquals("[System] Follow-up automatically canceled because contact was converted to a case", mergedContact.getFollowUpComment());
```
Comment (sergiupacurariu) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/contact/ContactFacadeEjbTest.java:1513]: please change the string to the Strings variable
