### PR TITLE
#9035 - [User Rights] System crash error occurs when certain users pe…

### LINKED ISSUE #9035: [User Rights] System crash error occurs when certain users perform the Basic Export action for Event Participants
### Bug Description
When certain users want to download a Basic Export for the Event Participants, they receive a system crash error.

The issue can be reproduced with the following users:
- National User;
- Admin Surveillance Supervisor;
- Surveillance Officer;
- Hospital Informant;
- Community Officer;
- Community Informant;
- Clinician;
- Case Officer;
- Contact Officer; 
- Event Officer;
- Lab Officer;
- National Observer;
- Region Observer;
- District Observer;
- National Clinician;
- POE Supervisor;

The only users that can perform this action successfully are: Admin; Surveillance Supervisor and Contact Supervisor;

I attach the logs for this bug:
[logs for event participants basic export error.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/8602360/logs.for.event.participants.basic.export.error.txt)

### Steps to Reproduce

1. Log in with one of the users from above:
2. Navigate to the Events Directory;
3. Open an Event and navigate to the 'Event Participants' tab;
4. Click on 'Export' -> 'Basic Export'

### Expected Behavior
The export should get downloaded and no error should appear when the user closes the pop-up;

### Screenshots
export error

### System Details

* Device: Window 10
* SORMAS version: Sormas 1.71.0-SNAPSHOT (4f6e61b)
* Android version/Browser: Chrome
* Server URL: local server
* User Role: users from the bug description

### PR DESCRIPTION
**Pull request by cazacmarin**
…rform the Basic Export action for Event Participants

Fixes #9035 

getSelectedRows.get()-sometime-is-returig-Null

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/GridExportStreamResource.java [hunk 1]
```diff
@@ -129,6 +131,10 @@ public InputStream getStream() {
 
 				Set<?> selectedRows = getSelectedRows != null ? getSelectedRows.get() : Collections.emptySet();
 
+				if (isNull(selectedRows)) {
+					selectedRows = Collections.emptySet();
+				}
+
 				if (selectedRows.isEmpty()) {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/GridExportStreamResource.java:138]: Would be cleaner to use CollectionUtils.isEmpty(selectedRows)

**Review by leventegal-she — CHANGES_REQUESTED** [review]

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/GridExportStreamResource.java (hunk 1 above)
Comment (cazacmarin) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/GridExportStreamResource.java:138]: In this case if (CollectionUtils.isEmpty(selectedRows)) {
					selectedRows = Collections.emptySet();
				}
it will always comes in. And it was not what was expected.
However, I will adjust the changes.
