### PR TITLE
#3174 consider excluded countries when generating import templates

### LINKED ISSUE #3174: Import template for cases and contacts has few fields which are specific to Switzerland. [0.5]
### Bug Description
Import template for cases and contacts has swiss related fields such as "Has covid app" and "covid code generated".

### Steps to Reproduce
1. Login to sormas as admin
2. Select Cases and click on import at the top right
3. On the new window displayed, select download import template and look for the fields "has covid app" and "covid code generated" on the downloaded csv

### Expected Behavior
The swiss specific fields should not be displayed in the import template for international server.

### Screenshots
import template_contacts
import template_cases

### System Details
* Device:
* SORMAS version: 1.50.0-snapshot
* Android version/Browser: chrome and Firefox
* Server URL: https://test.sormas.netzlink.com/
* User Role: admin

### PR DESCRIPTION
**Pull request by vlad-ciucescu**
closes #3174

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java [hunk 1]
```diff
@@ -439,7 +442,23 @@ private void appendListOfFields(List<ImportColumn> importColumns, Class<?> clazz
 				continue;
 			}
 
-			Method readMethod = null;
```
Comment (vidi42) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java:442]: Instead of writing a new implementation for this, maybe you could use the `CountryFieldVisibilityChecker` which is already available in the `sormas-api` project

**Review by vidi42 — CHANGES_REQUESTED** [review]

File: sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java (hunk 1 above)
Comment (vlad-ciucescu) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java:442]: nice

**Review by vidi42 — APPROVED** [review]
