### PR TITLE
bug/9541_samples_validate_dtos

### LINKED ISSUE #9541: Samples can be created via API calls with empty uuid values for associated Case/Contact/Event Participant, laboratory etc.
### Bug Description
Samples can be pushed into the DB and UI through Postman via API calls with empty or inexistent values for laboratory and associated case / contact / event participant.
Linked to #9276 

### Steps to Reproduce

1. In the Sormas Collection in Postman, navigate to the POST Sample call;
2. Edit the body of the API call, but leave the "associatedCase" value empty; 
3. Send the API call;
4. Check the Response and the Response Status and also check in the UI if the Sample has been created;

### Expected Behavior
The Sample shouldn't be created.

### Actual Behavior
The Response Status is '200 OK' and the Sample gets created in the DB and the UI.

### Screenshots
image
image

### System Details

* Device: Windows 10
* SORMAS version: Sormas 1.73.0-SNAPSHOT (4863074)
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: admin

### Additional Information
If the associatedCase is completely missing from the body of the API call, Response is "ERROR" and the Sample doesn't get created.
image

### PR DESCRIPTION
**Pull request by dinua**
Fixes #9541

### CODE REVIEW

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java [hunk 1]
```diff
@@ -459,6 +459,32 @@ public void validate(SampleDto sample) throws ValidationRuntimeException {
...
+
+		if (checkAssociatedEntities) {
+			validateSampleAssociatedEntities(sample);
+		}
+
+	}
+
+	private void validateSampleAssociatedEntities(SampleDto sample) {
+		if (sample.getAssociatedCase() != null && !caseService.exists(sample.getAssociatedCase().getUuid())) {
+			throw new ValidationRuntimeException(I18nProperties.getValidationError(Validations.validCaseContactOrEventParticipant));
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java:471]: Please add individual error messages for cases, contacts, and event participants here:

"The database does not contain a {case/contact/event participant} with this UUID."

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java [hunk 2]
```diff
@@ -459,6 +459,32 @@ public void validate(SampleDto sample) throws ValidationRuntimeException {
...
+		}
+		if (sample.getAssociatedContact() != null && !contactService.exists(sample.getAssociatedContact().getUuid())) {
+			throw new ValidationRuntimeException(I18nProperties.getValidationError(Validations.validCaseContactOrEventParticipant));
+		}
+		if (sample.getAssociatedEventParticipant() != null && !eventParticipantService.exists(sample.getAssociatedEventParticipant().getUuid())) {
+			throw new ValidationRuntimeException(I18nProperties.getValidationError(Validations.validCaseContactOrEventParticipant));
+		}
+		if (sample.getLab() != null && !facilityService.exists(sample.getLab().getUuid())) {
+			throw new ValidationRuntimeException(
+				I18nProperties.getValidationError(Validations.required, I18nProperties.getPrefixCaption(SampleDto.I18N_PREFIX, SampleDto.LAB)));
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java:481]: Please use a different error message here, since the user specified a lab at this point:

"The database does not contain a laboratory with this UUID."

File: sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java [hunk 3]
```diff
@@ -459,6 +459,32 @@ public void validate(SampleDto sample) throws ValidationRuntimeException {
...
+		}
+		if (!userService.exists(sample.getReportingUser().getUuid())) {
+			throw new ValidationRuntimeException(
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/sample/SampleFacadeEjb.java:484]: Please use a different error message here, since the user specified a reporting user at this point:

"The database does not contain a user with the UUID specified for the reporting user field."

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

File: sormas-api/src/main/resources/validations.properties [hunk 4]
```diff
@@ -107,6 +107,11 @@ specifyYear = You have to specify the year
 specifyEpiWeek = You have to specify the epi week
 userNameNotUnique = User name is not unique!
 validCaseContactOrEventParticipant=You have to specify a valid case or contact from the SORMAS database
+validExistingCase=The database does not contain a case with this UUID.
```
Comment (MateStrysewske) [inline sormas-api/src/main/resources/validations.properties:110]: Please change the names to `noCaseWithUuid`, `noContactWithUuid` etc. - afterwards the PR can be merged :)

**Review by MateStrysewske — APPROVED** [review]
