### PR TITLE
Bugfix 6371 date range of follow up visits gets lost after opening contact or case

### LINKED ISSUE #6371: Date-range of follow-up-visits gets lost after opening contact/case
### Bug Description

If  a date range is selected in the follow-up-visit view, the selection is reset to default after opening an contact and coming back to the follow-up-visits

image

@ChristopherRiedel @Jan-Boehme

### PR DESCRIPTION
**Pull request by sergiupacurariu**
Fixes #6371

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java [hunk 1]
```diff
@@ -377,6 +380,21 @@ public VerticalLayout createFilterBar() {
 		});
 		filterLayout.addComponent(filterForm);
 
+		HorizontalLayout actionButtonsLayout = new HorizontalLayout();
+		actionButtonsLayout.setSpacing(true);
+		{
+			// Follow-up overview scrolling
+			if (ContactsViewType.FOLLOW_UP_VISITS_OVERVIEW.equals(viewConfiguration.getViewType())) {
+				filterLayout.setWidth(100, Unit.PERCENTAGE);
+				HorizontalLayout scrollLayout = buildScrollLayout();
```
Comment (BarnaBartha) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java:389]: this name is still misleading, no scroll layout is being built there, please change it

Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/contact/ContactsView.java]: the method name has been changed both on cases and contacts

**Review by BarnaBartha — APPROVED** [review]
